/* character.c generated by valac 0.16.0, the Vala compiler
 * generated from character.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <SDL.h>
#include <stdlib.h>
#include <string.h>
#include <SDL_image.h>
#include <gio/gio.h>
#include <SDL_ttf.h>


#define SYNERGIA_TYPE_ORIENTATION (synergia_orientation_get_type ())

#define STK_TYPE_WIDGET (stk_widget_get_type ())
#define STK_WIDGET(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), STK_TYPE_WIDGET, StkWidget))
#define STK_WIDGET_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), STK_TYPE_WIDGET, StkWidgetClass))
#define STK_IS_WIDGET(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), STK_TYPE_WIDGET))
#define STK_IS_WIDGET_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), STK_TYPE_WIDGET))
#define STK_WIDGET_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), STK_TYPE_WIDGET, StkWidgetClass))

typedef struct _StkWidget StkWidget;
typedef struct _StkWidgetClass StkWidgetClass;
typedef struct _StkWidgetPrivate StkWidgetPrivate;

#define SYNERGIA_TYPE_CHARACTER (synergia_character_get_type ())
#define SYNERGIA_CHARACTER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYNERGIA_TYPE_CHARACTER, SynergiaCharacter))
#define SYNERGIA_CHARACTER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYNERGIA_TYPE_CHARACTER, SynergiaCharacterClass))
#define SYNERGIA_IS_CHARACTER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYNERGIA_TYPE_CHARACTER))
#define SYNERGIA_IS_CHARACTER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYNERGIA_TYPE_CHARACTER))
#define SYNERGIA_CHARACTER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYNERGIA_TYPE_CHARACTER, SynergiaCharacterClass))

typedef struct _SynergiaCharacter SynergiaCharacter;
typedef struct _SynergiaCharacterClass SynergiaCharacterClass;
typedef struct _SynergiaCharacterPrivate SynergiaCharacterPrivate;
#define _SDL_FreeSurface0(var) ((var == NULL) ? NULL : (var = (SDL_FreeSurface (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

#define SYNERGIA_TYPE_NET_CONNECTOR (synergia_net_connector_get_type ())
#define SYNERGIA_NET_CONNECTOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYNERGIA_TYPE_NET_CONNECTOR, SynergiaNetConnector))
#define SYNERGIA_NET_CONNECTOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYNERGIA_TYPE_NET_CONNECTOR, SynergiaNetConnectorClass))
#define SYNERGIA_IS_NET_CONNECTOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYNERGIA_TYPE_NET_CONNECTOR))
#define SYNERGIA_IS_NET_CONNECTOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYNERGIA_TYPE_NET_CONNECTOR))
#define SYNERGIA_NET_CONNECTOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYNERGIA_TYPE_NET_CONNECTOR, SynergiaNetConnectorClass))

typedef struct _SynergiaNetConnector SynergiaNetConnector;
typedef struct _SynergiaNetConnectorClass SynergiaNetConnectorClass;
typedef struct _SynergiaNetConnectorPrivate SynergiaNetConnectorPrivate;

#define SYNERGIA_TYPE_EVENTS (synergia_events_get_type ())
#define SYNERGIA_EVENTS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYNERGIA_TYPE_EVENTS, SynergiaEvents))
#define SYNERGIA_EVENTS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYNERGIA_TYPE_EVENTS, SynergiaEventsClass))
#define SYNERGIA_IS_EVENTS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYNERGIA_TYPE_EVENTS))
#define SYNERGIA_IS_EVENTS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYNERGIA_TYPE_EVENTS))
#define SYNERGIA_EVENTS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYNERGIA_TYPE_EVENTS, SynergiaEventsClass))

typedef struct _SynergiaEvents SynergiaEvents;
typedef struct _SynergiaEventsClass SynergiaEventsClass;

typedef enum  {
	SYNERGIA_ORIENTATION_NORTH = 3,
	SYNERGIA_ORIENTATION_SOUTH = 0,
	SYNERGIA_ORIENTATION_EAST = 2,
	SYNERGIA_ORIENTATION_WEST = 1
} SynergiaOrientation;

struct _StkWidget {
	GObject parent_instance;
	StkWidgetPrivate * priv;
	SDL_Rect rect;
	gboolean focused;
};

struct _StkWidgetClass {
	GObjectClass parent_class;
	gboolean (*draw) (StkWidget* self, SDL_Surface* screen);
};

struct _SynergiaCharacter {
	StkWidget parent_instance;
	SynergiaCharacterPrivate * priv;
	SDL_Surface* sprite;
	SDL_Surface* nameSurface;
	SynergiaOrientation orientation;
	gint frame;
	SDL_Rect pos;
	SDL_Rect offset;
	gint id;
	gint16 motion;
	gchar* name;
	gint16 move_offset;
	SynergiaOrientation move_orientation;
};

struct _SynergiaCharacterClass {
	StkWidgetClass parent_class;
};

struct _SynergiaNetConnector {
	GTypeInstance parent_instance;
	volatile int ref_count;
	SynergiaNetConnectorPrivate * priv;
	gchar* address;
	gint port;
	GSocket* socket;
	SynergiaEvents* events;
};

struct _SynergiaNetConnectorClass {
	GTypeClass parent_class;
	void (*finalize) (SynergiaNetConnector *self);
};


static gpointer synergia_character_parent_class = NULL;
extern gint stk_stk_ticks;
extern TTF_Font* stk_stk_font;

GType synergia_orientation_get_type (void) G_GNUC_CONST;
GType stk_widget_get_type (void) G_GNUC_CONST;
GType synergia_character_get_type (void) G_GNUC_CONST;
enum  {
	SYNERGIA_CHARACTER_DUMMY_PROPERTY
};
gpointer synergia_net_connector_ref (gpointer instance);
void synergia_net_connector_unref (gpointer instance);
GParamSpec* synergia_param_spec_net_connector (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void synergia_value_set_net_connector (GValue* value, gpointer v_object);
void synergia_value_take_net_connector (GValue* value, gpointer v_object);
gpointer synergia_value_get_net_connector (const GValue* value);
GType synergia_net_connector_get_type (void) G_GNUC_CONST;
SynergiaCharacter* synergia_character_new (SynergiaNetConnector* net);
SynergiaCharacter* synergia_character_construct (GType object_type, SynergiaNetConnector* net);
StkWidget* stk_widget_new (void);
StkWidget* stk_widget_construct (GType object_type);
gpointer synergia_events_ref (gpointer instance);
void synergia_events_unref (gpointer instance);
GParamSpec* synergia_param_spec_events (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void synergia_value_set_events (GValue* value, gpointer v_object);
void synergia_value_take_events (GValue* value, gpointer v_object);
gpointer synergia_value_get_events (const GValue* value);
GType synergia_events_get_type (void) G_GNUC_CONST;
void synergia_character_ChangePosition (SynergiaCharacter* self, gchar** command, int command_length1);
static void _synergia_character_ChangePosition_synergia_events_position (SynergiaEvents* _sender, gchar** args, int args_length1, gpointer self);
void synergia_character_MoveLeft (SynergiaCharacter* self, gchar** command, int command_length1);
static void _synergia_character_MoveLeft_synergia_events_moveleft (SynergiaEvents* _sender, gchar** args, int args_length1, gpointer self);
void synergia_character_MoveUp (SynergiaCharacter* self, gchar** command, int command_length1);
static void _synergia_character_MoveUp_synergia_events_moveup (SynergiaEvents* _sender, gchar** args, int args_length1, gpointer self);
void synergia_character_MoveRight (SynergiaCharacter* self, gchar** command, int command_length1);
static void _synergia_character_MoveRight_synergia_events_moveright (SynergiaEvents* _sender, gchar** args, int args_length1, gpointer self);
void synergia_character_MoveDown (SynergiaCharacter* self, gchar** command, int command_length1);
static void _synergia_character_MoveDown_synergia_events_movedown (SynergiaEvents* _sender, gchar** args, int args_length1, gpointer self);
static gboolean synergia_character_real_draw (StkWidget* base, SDL_Surface* screen);
static void synergia_character_finalize (GObject* obj);


GType synergia_orientation_get_type (void) {
	static volatile gsize synergia_orientation_type_id__volatile = 0;
	if (g_once_init_enter (&synergia_orientation_type_id__volatile)) {
		static const GEnumValue values[] = {{SYNERGIA_ORIENTATION_NORTH, "SYNERGIA_ORIENTATION_NORTH", "north"}, {SYNERGIA_ORIENTATION_SOUTH, "SYNERGIA_ORIENTATION_SOUTH", "south"}, {SYNERGIA_ORIENTATION_EAST, "SYNERGIA_ORIENTATION_EAST", "east"}, {SYNERGIA_ORIENTATION_WEST, "SYNERGIA_ORIENTATION_WEST", "west"}, {0, NULL, NULL}};
		GType synergia_orientation_type_id;
		synergia_orientation_type_id = g_enum_register_static ("SynergiaOrientation", values);
		g_once_init_leave (&synergia_orientation_type_id__volatile, synergia_orientation_type_id);
	}
	return synergia_orientation_type_id__volatile;
}


static void _synergia_character_ChangePosition_synergia_events_position (SynergiaEvents* _sender, gchar** args, int args_length1, gpointer self) {
	synergia_character_ChangePosition (self, args, args_length1);
}


static void _synergia_character_MoveLeft_synergia_events_moveleft (SynergiaEvents* _sender, gchar** args, int args_length1, gpointer self) {
	synergia_character_MoveLeft (self, args, args_length1);
}


static void _synergia_character_MoveUp_synergia_events_moveup (SynergiaEvents* _sender, gchar** args, int args_length1, gpointer self) {
	synergia_character_MoveUp (self, args, args_length1);
}


static void _synergia_character_MoveRight_synergia_events_moveright (SynergiaEvents* _sender, gchar** args, int args_length1, gpointer self) {
	synergia_character_MoveRight (self, args, args_length1);
}


static void _synergia_character_MoveDown_synergia_events_movedown (SynergiaEvents* _sender, gchar** args, int args_length1, gpointer self) {
	synergia_character_MoveDown (self, args, args_length1);
}


SynergiaCharacter* synergia_character_construct (GType object_type, SynergiaNetConnector* net) {
	SynergiaCharacter * self = NULL;
	SDL_Surface* _tmp0_ = NULL;
	SDL_Surface* _tmp1_;
	SynergiaNetConnector* _tmp2_;
	SynergiaEvents* _tmp3_;
	SynergiaNetConnector* _tmp4_;
	SynergiaEvents* _tmp5_;
	SynergiaNetConnector* _tmp6_;
	SynergiaEvents* _tmp7_;
	SynergiaNetConnector* _tmp8_;
	SynergiaEvents* _tmp9_;
	SynergiaNetConnector* _tmp10_;
	SynergiaEvents* _tmp11_;
	g_return_val_if_fail (net != NULL, NULL);
	self = (SynergiaCharacter*) stk_widget_construct (object_type);
	memset (&self->pos, 0, sizeof (SDL_Rect));
	memset (&self->offset, 0, sizeof (SDL_Rect));
	self->orientation = SYNERGIA_ORIENTATION_SOUTH;
	self->frame = 0;
	_tmp0_ = IMG_Load ("gfx/charsets/player.png");
	_SDL_FreeSurface0 (self->sprite);
	self->sprite = _tmp0_;
	_tmp1_ = self->sprite;
	SDL_SetAlpha (_tmp1_, (guint32) 0, (guchar) 0);
	_tmp2_ = net;
	_tmp3_ = _tmp2_->events;
	g_signal_connect_object (_tmp3_, "position", (GCallback) _synergia_character_ChangePosition_synergia_events_position, self, 0);
	_tmp4_ = net;
	_tmp5_ = _tmp4_->events;
	g_signal_connect_object (_tmp5_, "moveleft", (GCallback) _synergia_character_MoveLeft_synergia_events_moveleft, self, 0);
	_tmp6_ = net;
	_tmp7_ = _tmp6_->events;
	g_signal_connect_object (_tmp7_, "moveup", (GCallback) _synergia_character_MoveUp_synergia_events_moveup, self, 0);
	_tmp8_ = net;
	_tmp9_ = _tmp8_->events;
	g_signal_connect_object (_tmp9_, "moveright", (GCallback) _synergia_character_MoveRight_synergia_events_moveright, self, 0);
	_tmp10_ = net;
	_tmp11_ = _tmp10_->events;
	g_signal_connect_object (_tmp11_, "movedown", (GCallback) _synergia_character_MoveDown_synergia_events_movedown, self, 0);
	return self;
}


SynergiaCharacter* synergia_character_new (SynergiaNetConnector* net) {
	return synergia_character_construct (SYNERGIA_TYPE_CHARACTER, net);
}


void synergia_character_MoveLeft (SynergiaCharacter* self, gchar** command, int command_length1) {
	gint _tmp0_;
	gchar** _tmp1_;
	gint _tmp1__length1;
	const gchar* _tmp2_;
	gint _tmp3_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->id;
	_tmp1_ = command;
	_tmp1__length1 = command_length1;
	_tmp2_ = _tmp1_[0];
	_tmp3_ = atoi (_tmp2_);
	if (_tmp0_ == _tmp3_) {
		gint16 _tmp4_;
		_tmp4_ = self->pos.x;
		self->pos.x = _tmp4_ - 1;
		self->orientation = SYNERGIA_ORIENTATION_WEST;
		self->motion = (gint16) 32;
	}
}


void synergia_character_MoveRight (SynergiaCharacter* self, gchar** command, int command_length1) {
	gint _tmp0_;
	gchar** _tmp1_;
	gint _tmp1__length1;
	const gchar* _tmp2_;
	gint _tmp3_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->id;
	_tmp1_ = command;
	_tmp1__length1 = command_length1;
	_tmp2_ = _tmp1_[0];
	_tmp3_ = atoi (_tmp2_);
	if (_tmp0_ == _tmp3_) {
		gint16 _tmp4_;
		_tmp4_ = self->pos.x;
		self->pos.x = _tmp4_ + 1;
		self->orientation = SYNERGIA_ORIENTATION_EAST;
		self->motion = (gint16) 32;
	}
}


void synergia_character_MoveUp (SynergiaCharacter* self, gchar** command, int command_length1) {
	gint _tmp0_;
	gchar** _tmp1_;
	gint _tmp1__length1;
	const gchar* _tmp2_;
	gint _tmp3_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->id;
	_tmp1_ = command;
	_tmp1__length1 = command_length1;
	_tmp2_ = _tmp1_[0];
	_tmp3_ = atoi (_tmp2_);
	if (_tmp0_ == _tmp3_) {
		gint16 _tmp4_;
		_tmp4_ = self->pos.y;
		self->pos.y = _tmp4_ - 1;
		self->orientation = SYNERGIA_ORIENTATION_NORTH;
		self->motion = (gint16) 32;
	}
}


void synergia_character_MoveDown (SynergiaCharacter* self, gchar** command, int command_length1) {
	gint _tmp0_;
	gchar** _tmp1_;
	gint _tmp1__length1;
	const gchar* _tmp2_;
	gint _tmp3_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->id;
	_tmp1_ = command;
	_tmp1__length1 = command_length1;
	_tmp2_ = _tmp1_[0];
	_tmp3_ = atoi (_tmp2_);
	if (_tmp0_ == _tmp3_) {
		gint16 _tmp4_;
		_tmp4_ = self->pos.y;
		self->pos.y = _tmp4_ + 1;
		self->orientation = SYNERGIA_ORIENTATION_SOUTH;
		self->motion = (gint16) 32;
	}
}


void synergia_character_ChangePosition (SynergiaCharacter* self, gchar** command, int command_length1) {
	gint _tmp0_;
	gchar** _tmp1_;
	gint _tmp1__length1;
	const gchar* _tmp2_;
	gint _tmp3_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->id;
	_tmp1_ = command;
	_tmp1__length1 = command_length1;
	_tmp2_ = _tmp1_[0];
	_tmp3_ = atoi (_tmp2_);
	if (_tmp0_ == _tmp3_) {
		gchar** _tmp4_;
		gint _tmp4__length1;
		const gchar* _tmp5_;
		gint _tmp6_ = 0;
		gchar** _tmp7_;
		gint _tmp7__length1;
		const gchar* _tmp8_;
		gint _tmp9_ = 0;
		_tmp4_ = command;
		_tmp4__length1 = command_length1;
		_tmp5_ = _tmp4_[1];
		_tmp6_ = atoi (_tmp5_);
		self->pos.x = (gint16) _tmp6_;
		_tmp7_ = command;
		_tmp7__length1 = command_length1;
		_tmp8_ = _tmp7_[2];
		_tmp9_ = atoi (_tmp8_);
		self->pos.y = (gint16) _tmp9_;
		self->motion = (gint16) 0;
	}
}


static gboolean synergia_character_real_draw (StkWidget* base, SDL_Surface* screen) {
	SynergiaCharacter * self;
	gboolean result = FALSE;
	SDL_Rect src = {0};
	SDL_Rect dst = {0};
	gint16 _tmp0_;
	gint _tmp4_;
	SynergiaOrientation _tmp5_;
	SDL_Rect _tmp6_;
	gint16 _tmp7_;
	SDL_Rect _tmp8_;
	gint16 _tmp9_;
	SDL_Rect _tmp10_;
	gint16 _tmp11_;
	SDL_Rect _tmp12_;
	gint16 _tmp13_;
	gint16 _tmp14_;
	gint16 _tmp24_;
	gboolean _tmp34_ = FALSE;
	gboolean _tmp35_ = FALSE;
	gboolean _tmp36_ = FALSE;
	SDL_Rect _tmp37_;
	gint16 _tmp38_;
	gboolean _tmp43_;
	gboolean _tmp46_;
	gboolean _tmp51_;
	SDL_Surface* _tmp52_;
	SDL_Surface* _tmp58_;
	SDL_Rect _tmp59_;
	SDL_Surface* _tmp60_;
	SDL_Rect _tmp61_;
	gint16 _tmp62_;
	SDL_Surface* _tmp63_;
	gint _tmp64_;
	SDL_Surface* _tmp65_;
	SDL_Surface* _tmp66_;
	SDL_Rect _tmp67_;
	gint16 _tmp68_;
	SDL_Surface* _tmp69_;
	gint _tmp70_;
	gint16 _tmp71_;
	SDL_Rect _tmp73_;
	gint16 _tmp74_;
	SDL_Rect _tmp75_;
	gint16 _tmp76_;
	self = (SynergiaCharacter*) base;
	g_return_val_if_fail (screen != NULL, FALSE);
	memset (&src, 0, sizeof (SDL_Rect));
	memset (&dst, 0, sizeof (SDL_Rect));
	src.w = (guint16) 32;
	src.h = (guint16) 32;
	dst.w = (guint16) 32;
	dst.h = (guint16) 32;
	_tmp0_ = self->motion;
	if (((gint) _tmp0_) > 0) {
		gint _tmp1_;
		_tmp1_ = stk_stk_ticks;
		self->frame = (_tmp1_ / 8) % 4;
	} else {
		gint _tmp2_;
		gint _tmp3_;
		_tmp2_ = stk_stk_ticks;
		_tmp3_ = stk_stk_ticks;
		if (((_tmp2_ / 8) % 4) != (((_tmp3_ - 1) / 8) % 4)) {
			self->frame = 0;
		}
	}
	_tmp4_ = self->frame;
	src.x = (gint16) (32 * _tmp4_);
	_tmp5_ = self->orientation;
	src.y = (gint16) (32 * _tmp5_);
	_tmp6_ = self->pos;
	_tmp7_ = _tmp6_.x;
	_tmp8_ = self->offset;
	_tmp9_ = _tmp8_.x;
	dst.x = (gint16) (32 * (_tmp7_ - _tmp9_));
	_tmp10_ = self->pos;
	_tmp11_ = _tmp10_.y;
	_tmp12_ = self->offset;
	_tmp13_ = _tmp12_.y;
	dst.y = (gint16) (32 * (_tmp11_ - _tmp13_));
	_tmp14_ = self->move_offset;
	if (((gint) _tmp14_) != 0) {
		SynergiaOrientation _tmp15_;
		_tmp15_ = self->move_orientation;
		switch (_tmp15_) {
			case SYNERGIA_ORIENTATION_NORTH:
			{
				gint16 _tmp16_;
				gint16 _tmp17_;
				_tmp16_ = dst.y;
				_tmp17_ = self->move_offset;
				dst.y = _tmp16_ - _tmp17_;
				break;
			}
			case SYNERGIA_ORIENTATION_SOUTH:
			{
				gint16 _tmp18_;
				gint16 _tmp19_;
				_tmp18_ = dst.y;
				_tmp19_ = self->move_offset;
				dst.y = _tmp18_ + _tmp19_;
				break;
			}
			case SYNERGIA_ORIENTATION_EAST:
			{
				gint16 _tmp20_;
				gint16 _tmp21_;
				_tmp20_ = dst.x;
				_tmp21_ = self->move_offset;
				dst.x = _tmp20_ + _tmp21_;
				break;
			}
			case SYNERGIA_ORIENTATION_WEST:
			{
				gint16 _tmp22_;
				gint16 _tmp23_;
				_tmp22_ = dst.x;
				_tmp23_ = self->move_offset;
				dst.x = _tmp22_ - _tmp23_;
				break;
			}
			default:
			break;
		}
	}
	_tmp24_ = self->motion;
	if (((gint) _tmp24_) != 0) {
		SynergiaOrientation _tmp25_;
		_tmp25_ = self->orientation;
		switch (_tmp25_) {
			case SYNERGIA_ORIENTATION_NORTH:
			{
				gint16 _tmp26_;
				gint16 _tmp27_;
				_tmp26_ = dst.y;
				_tmp27_ = self->motion;
				dst.y = _tmp26_ + _tmp27_;
				break;
			}
			case SYNERGIA_ORIENTATION_SOUTH:
			{
				gint16 _tmp28_;
				gint16 _tmp29_;
				_tmp28_ = dst.y;
				_tmp29_ = self->motion;
				dst.y = _tmp28_ - _tmp29_;
				break;
			}
			case SYNERGIA_ORIENTATION_EAST:
			{
				gint16 _tmp30_;
				gint16 _tmp31_;
				_tmp30_ = dst.x;
				_tmp31_ = self->motion;
				dst.x = _tmp30_ - _tmp31_;
				break;
			}
			case SYNERGIA_ORIENTATION_WEST:
			{
				gint16 _tmp32_;
				gint16 _tmp33_;
				_tmp32_ = dst.x;
				_tmp33_ = self->motion;
				dst.x = _tmp32_ + _tmp33_;
				break;
			}
			default:
			break;
		}
	}
	_tmp37_ = dst;
	_tmp38_ = _tmp37_.x;
	if (((gint) _tmp38_) < (-31)) {
		_tmp36_ = TRUE;
	} else {
		SDL_Rect _tmp39_;
		gint16 _tmp40_;
		SDL_Surface* _tmp41_;
		gint _tmp42_;
		_tmp39_ = dst;
		_tmp40_ = _tmp39_.x;
		_tmp41_ = screen;
		_tmp42_ = _tmp41_->w;
		_tmp36_ = ((gint) _tmp40_) > (_tmp42_ + 31);
	}
	_tmp43_ = _tmp36_;
	if (_tmp43_) {
		_tmp35_ = TRUE;
	} else {
		SDL_Rect _tmp44_;
		gint16 _tmp45_;
		_tmp44_ = dst;
		_tmp45_ = _tmp44_.y;
		_tmp35_ = ((gint) _tmp45_) < (-31);
	}
	_tmp46_ = _tmp35_;
	if (_tmp46_) {
		_tmp34_ = TRUE;
	} else {
		SDL_Rect _tmp47_;
		gint16 _tmp48_;
		SDL_Surface* _tmp49_;
		gint _tmp50_;
		_tmp47_ = dst;
		_tmp48_ = _tmp47_.y;
		_tmp49_ = screen;
		_tmp50_ = _tmp49_->h;
		_tmp34_ = ((gint) _tmp48_) > (_tmp50_ + 31);
	}
	_tmp51_ = _tmp34_;
	if (_tmp51_) {
		result = TRUE;
		return result;
	}
	_tmp52_ = self->nameSurface;
	if (_tmp52_ == NULL) {
		TTF_Font* _tmp53_;
		const gchar* _tmp54_;
		SDL_Color _tmp55_ = {0};
		SDL_Surface* _tmp56_ = NULL;
		SDL_Surface* _tmp57_;
		_tmp53_ = stk_stk_font;
		_tmp54_ = self->name;
		_tmp55_.r = (guchar) 255;
		_tmp55_.g = (guchar) 255;
		_tmp55_.b = (guchar) 255;
		_tmp55_.unused = (guchar) 255;
		_tmp56_ = TTF_RenderText_Blended (_tmp53_, _tmp54_, _tmp55_);
		_SDL_FreeSurface0 (self->nameSurface);
		self->nameSurface = _tmp56_;
		_tmp57_ = self->nameSurface;
		SDL_SetAlpha (_tmp57_, (guint32) 0, (guchar) 0);
	}
	_tmp58_ = self->sprite;
	_tmp59_ = src;
	_tmp60_ = screen;
	_tmp61_ = dst;
	SDL_UpperBlit (_tmp58_, &_tmp59_, _tmp60_, &_tmp61_);
	_tmp62_ = dst.y;
	_tmp63_ = self->nameSurface;
	_tmp64_ = _tmp63_->h;
	dst.y = _tmp62_ - ((gint16) _tmp64_);
	_tmp65_ = self->nameSurface;
	_tmp66_ = screen;
	_tmp67_ = dst;
	SDL_UpperBlit (_tmp65_, NULL, _tmp66_, &_tmp67_);
	_tmp68_ = dst.y;
	_tmp69_ = self->nameSurface;
	_tmp70_ = _tmp69_->h;
	dst.y = _tmp68_ + ((gint16) _tmp70_);
	_tmp71_ = self->motion;
	if (((gint) _tmp71_) > 0) {
		gint16 _tmp72_;
		_tmp72_ = self->motion;
		self->motion = _tmp72_ - 1;
	}
	_tmp73_ = dst;
	_tmp74_ = _tmp73_.x;
	((StkWidget*) self)->rect.x = _tmp74_;
	_tmp75_ = dst;
	_tmp76_ = _tmp75_.y;
	((StkWidget*) self)->rect.y = _tmp76_;
	((StkWidget*) self)->rect.w = (guint16) 32;
	((StkWidget*) self)->rect.h = (guint16) 32;
	result = TRUE;
	return result;
}


static void synergia_character_class_init (SynergiaCharacterClass * klass) {
	synergia_character_parent_class = g_type_class_peek_parent (klass);
	STK_WIDGET_CLASS (klass)->draw = synergia_character_real_draw;
	G_OBJECT_CLASS (klass)->finalize = synergia_character_finalize;
}


static void synergia_character_instance_init (SynergiaCharacter * self) {
	self->motion = (gint16) 0;
	self->move_offset = (gint16) 0;
}


static void synergia_character_finalize (GObject* obj) {
	SynergiaCharacter * self;
	self = SYNERGIA_CHARACTER (obj);
	_SDL_FreeSurface0 (self->sprite);
	_SDL_FreeSurface0 (self->nameSurface);
	_g_free0 (self->name);
	G_OBJECT_CLASS (synergia_character_parent_class)->finalize (obj);
}


GType synergia_character_get_type (void) {
	static volatile gsize synergia_character_type_id__volatile = 0;
	if (g_once_init_enter (&synergia_character_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (SynergiaCharacterClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) synergia_character_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (SynergiaCharacter), 0, (GInstanceInitFunc) synergia_character_instance_init, NULL };
		GType synergia_character_type_id;
		synergia_character_type_id = g_type_register_static (STK_TYPE_WIDGET, "SynergiaCharacter", &g_define_type_info, 0);
		g_once_init_leave (&synergia_character_type_id__volatile, synergia_character_type_id);
	}
	return synergia_character_type_id__volatile;
}



