/* chunk.c generated by valac 0.16.0, the Vala compiler
 * generated from chunk.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gobject/gvaluecollector.h>


#define SYNERGIA_TYPE_CHUNK (synergia_chunk_get_type ())
#define SYNERGIA_CHUNK(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYNERGIA_TYPE_CHUNK, SynergiaChunk))
#define SYNERGIA_CHUNK_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYNERGIA_TYPE_CHUNK, SynergiaChunkClass))
#define SYNERGIA_IS_CHUNK(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYNERGIA_TYPE_CHUNK))
#define SYNERGIA_IS_CHUNK_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYNERGIA_TYPE_CHUNK))
#define SYNERGIA_CHUNK_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYNERGIA_TYPE_CHUNK, SynergiaChunkClass))

typedef struct _SynergiaChunk SynergiaChunk;
typedef struct _SynergiaChunkClass SynergiaChunkClass;
typedef struct _SynergiaChunkPrivate SynergiaChunkPrivate;

#define SYNERGIA_TYPE_TILE (synergia_tile_get_type ())
typedef struct _SynergiaTile SynergiaTile;
typedef struct _SynergiaParamSpecChunk SynergiaParamSpecChunk;

struct _SynergiaTile {
	gchar* value;
	gboolean crossable;
	gboolean set;
};

struct _SynergiaChunk {
	GTypeInstance parent_instance;
	volatile int ref_count;
	SynergiaChunkPrivate * priv;
	SynergiaTile* data;
	gint data_length1;
	gint x;
	gint y;
};

struct _SynergiaChunkClass {
	GTypeClass parent_class;
	void (*finalize) (SynergiaChunk *self);
};

struct _SynergiaParamSpecChunk {
	GParamSpec parent_instance;
};


static gpointer synergia_chunk_parent_class = NULL;

gpointer synergia_chunk_ref (gpointer instance);
void synergia_chunk_unref (gpointer instance);
GParamSpec* synergia_param_spec_chunk (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void synergia_value_set_chunk (GValue* value, gpointer v_object);
void synergia_value_take_chunk (GValue* value, gpointer v_object);
gpointer synergia_value_get_chunk (const GValue* value);
GType synergia_chunk_get_type (void) G_GNUC_CONST;
GType synergia_tile_get_type (void) G_GNUC_CONST;
SynergiaTile* synergia_tile_dup (const SynergiaTile* self);
void synergia_tile_free (SynergiaTile* self);
void synergia_tile_copy (const SynergiaTile* self, SynergiaTile* dest);
void synergia_tile_destroy (SynergiaTile* self);
enum  {
	SYNERGIA_CHUNK_DUMMY_PROPERTY
};
static void _vala_SynergiaTile_array_free (SynergiaTile* array, gint array_length);
SynergiaChunk* synergia_chunk_new (gint x, gint y, SynergiaTile* data, int data_length1);
SynergiaChunk* synergia_chunk_construct (GType object_type, gint x, gint y, SynergiaTile* data, int data_length1);
static SynergiaTile* _vala_array_dup1 (SynergiaTile* self, int length);
static void synergia_chunk_finalize (SynergiaChunk* obj);


static void _vala_SynergiaTile_array_free (SynergiaTile* array, gint array_length) {
	if (array != NULL) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			synergia_tile_destroy (&array[i]);
		}
	}
	g_free (array);
}


static SynergiaTile* _vala_array_dup1 (SynergiaTile* self, int length) {
	SynergiaTile* result;
	int i;
	result = g_new0 (SynergiaTile, length);
	for (i = 0; i < length; i++) {
		SynergiaTile _tmp0_ = {0};
		synergia_tile_copy (&self[i], &_tmp0_);
		result[i] = _tmp0_;
	}
	return result;
}


SynergiaChunk* synergia_chunk_construct (GType object_type, gint x, gint y, SynergiaTile* data, int data_length1) {
	SynergiaChunk* self = NULL;
	SynergiaTile* _tmp0_;
	gint _tmp0__length1;
	SynergiaTile* _tmp1_;
	gint _tmp1__length1;
	gint _tmp2_;
	gint _tmp3_;
	self = (SynergiaChunk*) g_type_create_instance (object_type);
	_tmp0_ = data;
	_tmp0__length1 = data_length1;
	_tmp1_ = (_tmp0_ != NULL) ? _vala_array_dup1 (_tmp0_, _tmp0__length1) : ((gpointer) _tmp0_);
	_tmp1__length1 = _tmp0__length1;
	self->data = (_vala_SynergiaTile_array_free (self->data, self->data_length1), NULL);
	self->data = _tmp1_;
	self->data_length1 = _tmp1__length1;
	_tmp2_ = x;
	self->x = _tmp2_;
	_tmp3_ = y;
	self->y = _tmp3_;
	return self;
}


SynergiaChunk* synergia_chunk_new (gint x, gint y, SynergiaTile* data, int data_length1) {
	return synergia_chunk_construct (SYNERGIA_TYPE_CHUNK, x, y, data, data_length1);
}


static void synergia_value_chunk_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void synergia_value_chunk_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		synergia_chunk_unref (value->data[0].v_pointer);
	}
}


static void synergia_value_chunk_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = synergia_chunk_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer synergia_value_chunk_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* synergia_value_chunk_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		SynergiaChunk* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = synergia_chunk_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* synergia_value_chunk_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	SynergiaChunk** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = synergia_chunk_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* synergia_param_spec_chunk (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	SynergiaParamSpecChunk* spec;
	g_return_val_if_fail (g_type_is_a (object_type, SYNERGIA_TYPE_CHUNK), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer synergia_value_get_chunk (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, SYNERGIA_TYPE_CHUNK), NULL);
	return value->data[0].v_pointer;
}


void synergia_value_set_chunk (GValue* value, gpointer v_object) {
	SynergiaChunk* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, SYNERGIA_TYPE_CHUNK));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, SYNERGIA_TYPE_CHUNK));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		synergia_chunk_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		synergia_chunk_unref (old);
	}
}


void synergia_value_take_chunk (GValue* value, gpointer v_object) {
	SynergiaChunk* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, SYNERGIA_TYPE_CHUNK));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, SYNERGIA_TYPE_CHUNK));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		synergia_chunk_unref (old);
	}
}


static void synergia_chunk_class_init (SynergiaChunkClass * klass) {
	synergia_chunk_parent_class = g_type_class_peek_parent (klass);
	SYNERGIA_CHUNK_CLASS (klass)->finalize = synergia_chunk_finalize;
}


static void synergia_chunk_instance_init (SynergiaChunk * self) {
	self->ref_count = 1;
}


static void synergia_chunk_finalize (SynergiaChunk* obj) {
	SynergiaChunk * self;
	self = SYNERGIA_CHUNK (obj);
	self->data = (_vala_SynergiaTile_array_free (self->data, self->data_length1), NULL);
}


GType synergia_chunk_get_type (void) {
	static volatile gsize synergia_chunk_type_id__volatile = 0;
	if (g_once_init_enter (&synergia_chunk_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { synergia_value_chunk_init, synergia_value_chunk_free_value, synergia_value_chunk_copy_value, synergia_value_chunk_peek_pointer, "p", synergia_value_chunk_collect_value, "p", synergia_value_chunk_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (SynergiaChunkClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) synergia_chunk_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (SynergiaChunk), 0, (GInstanceInitFunc) synergia_chunk_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType synergia_chunk_type_id;
		synergia_chunk_type_id = g_type_register_fundamental (g_type_fundamental_next (), "SynergiaChunk", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&synergia_chunk_type_id__volatile, synergia_chunk_type_id);
	}
	return synergia_chunk_type_id__volatile;
}


gpointer synergia_chunk_ref (gpointer instance) {
	SynergiaChunk* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void synergia_chunk_unref (gpointer instance) {
	SynergiaChunk* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		SYNERGIA_CHUNK_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}



