/* connect_window.c generated by valac 0.16.0, the Vala compiler
 * generated from connect_window.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <SDL.h>
#include <gee.h>
#include <stdlib.h>
#include <string.h>


#define STK_TYPE_WIDGET (stk_widget_get_type ())
#define STK_WIDGET(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), STK_TYPE_WIDGET, StkWidget))
#define STK_WIDGET_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), STK_TYPE_WIDGET, StkWidgetClass))
#define STK_IS_WIDGET(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), STK_TYPE_WIDGET))
#define STK_IS_WIDGET_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), STK_TYPE_WIDGET))
#define STK_WIDGET_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), STK_TYPE_WIDGET, StkWidgetClass))

typedef struct _StkWidget StkWidget;
typedef struct _StkWidgetClass StkWidgetClass;
typedef struct _StkWidgetPrivate StkWidgetPrivate;

#define STK_TYPE_CONTAINER (stk_container_get_type ())
#define STK_CONTAINER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), STK_TYPE_CONTAINER, StkContainer))
#define STK_CONTAINER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), STK_TYPE_CONTAINER, StkContainerClass))
#define STK_IS_CONTAINER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), STK_TYPE_CONTAINER))
#define STK_IS_CONTAINER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), STK_TYPE_CONTAINER))
#define STK_CONTAINER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), STK_TYPE_CONTAINER, StkContainerClass))

typedef struct _StkContainer StkContainer;
typedef struct _StkContainerClass StkContainerClass;
typedef struct _StkContainerPrivate StkContainerPrivate;

#define STK_TYPE_WINDOW (stk_window_get_type ())
#define STK_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), STK_TYPE_WINDOW, StkWindow))
#define STK_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), STK_TYPE_WINDOW, StkWindowClass))
#define STK_IS_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), STK_TYPE_WINDOW))
#define STK_IS_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), STK_TYPE_WINDOW))
#define STK_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), STK_TYPE_WINDOW, StkWindowClass))

typedef struct _StkWindow StkWindow;
typedef struct _StkWindowClass StkWindowClass;
typedef struct _StkWindowPrivate StkWindowPrivate;

#define SYNERGIA_TYPE_CONNECT_WINDOW (synergia_connect_window_get_type ())
#define SYNERGIA_CONNECT_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYNERGIA_TYPE_CONNECT_WINDOW, SynergiaConnectWindow))
#define SYNERGIA_CONNECT_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYNERGIA_TYPE_CONNECT_WINDOW, SynergiaConnectWindowClass))
#define SYNERGIA_IS_CONNECT_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYNERGIA_TYPE_CONNECT_WINDOW))
#define SYNERGIA_IS_CONNECT_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYNERGIA_TYPE_CONNECT_WINDOW))
#define SYNERGIA_CONNECT_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYNERGIA_TYPE_CONNECT_WINDOW, SynergiaConnectWindowClass))

typedef struct _SynergiaConnectWindow SynergiaConnectWindow;
typedef struct _SynergiaConnectWindowClass SynergiaConnectWindowClass;
typedef struct _SynergiaConnectWindowPrivate SynergiaConnectWindowPrivate;

#define STK_TYPE_ENTRY (stk_entry_get_type ())
#define STK_ENTRY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), STK_TYPE_ENTRY, StkEntry))
#define STK_ENTRY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), STK_TYPE_ENTRY, StkEntryClass))
#define STK_IS_ENTRY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), STK_TYPE_ENTRY))
#define STK_IS_ENTRY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), STK_TYPE_ENTRY))
#define STK_ENTRY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), STK_TYPE_ENTRY, StkEntryClass))

typedef struct _StkEntry StkEntry;
typedef struct _StkEntryClass StkEntryClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define STK_TYPE_HBOX (stk_hbox_get_type ())
#define STK_HBOX(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), STK_TYPE_HBOX, StkHBox))
#define STK_HBOX_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), STK_TYPE_HBOX, StkHBoxClass))
#define STK_IS_HBOX(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), STK_TYPE_HBOX))
#define STK_IS_HBOX_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), STK_TYPE_HBOX))
#define STK_HBOX_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), STK_TYPE_HBOX, StkHBoxClass))

typedef struct _StkHBox StkHBox;
typedef struct _StkHBoxClass StkHBoxClass;

#define STK_TYPE_BUTTON (stk_button_get_type ())
#define STK_BUTTON(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), STK_TYPE_BUTTON, StkButton))
#define STK_BUTTON_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), STK_TYPE_BUTTON, StkButtonClass))
#define STK_IS_BUTTON(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), STK_TYPE_BUTTON))
#define STK_IS_BUTTON_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), STK_TYPE_BUTTON))
#define STK_BUTTON_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), STK_TYPE_BUTTON, StkButtonClass))

typedef struct _StkButton StkButton;
typedef struct _StkButtonClass StkButtonClass;

#define STK_TYPE_LABEL (stk_label_get_type ())
#define STK_LABEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), STK_TYPE_LABEL, StkLabel))
#define STK_LABEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), STK_TYPE_LABEL, StkLabelClass))
#define STK_IS_LABEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), STK_TYPE_LABEL))
#define STK_IS_LABEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), STK_TYPE_LABEL))
#define STK_LABEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), STK_TYPE_LABEL, StkLabelClass))

typedef struct _StkLabel StkLabel;
typedef struct _StkLabelClass StkLabelClass;
typedef struct _StkEntryPrivate StkEntryPrivate;

#define STK_TYPE_ALIGNMENT (stk_alignment_get_type ())
typedef struct _StkLabelPrivate StkLabelPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))

struct _StkWidget {
	GObject parent_instance;
	StkWidgetPrivate * priv;
	SDL_Rect rect;
	gboolean focused;
};

struct _StkWidgetClass {
	GObjectClass parent_class;
	gboolean (*draw) (StkWidget* self, SDL_Surface* screen);
};

struct _StkContainer {
	StkWidget parent_instance;
	StkContainerPrivate * priv;
	GeeList* widgets;
};

struct _StkContainerClass {
	StkWidgetClass parent_class;
};

struct _StkWindow {
	StkContainer parent_instance;
	StkWindowPrivate * priv;
	SDL_Color background;
	SDL_Color titlebg;
	SDL_Color border;
	gchar* title;
	guchar opacity;
	gboolean bubble;
};

struct _StkWindowClass {
	StkContainerClass parent_class;
};

struct _SynergiaConnectWindow {
	StkWindow parent_instance;
	SynergiaConnectWindowPrivate * priv;
};

struct _SynergiaConnectWindowClass {
	StkWindowClass parent_class;
};

struct _SynergiaConnectWindowPrivate {
	StkEntry* usernameEntry;
	StkEntry* passwordEntry;
};

struct _StkEntry {
	StkWidget parent_instance;
	StkEntryPrivate * priv;
	SDL_Color border;
	SDL_Color background;
	gchar* text;
	gboolean hidden;
};

struct _StkEntryClass {
	StkWidgetClass parent_class;
};

typedef enum  {
	STK_ALIGNMENT_LEFT,
	STK_ALIGNMENT_RIGHT,
	STK_ALIGNMENT_CENTER,
	STK_ALIGNMENT_TOP,
	STK_ALIGNMENT_MIDDLE,
	STK_ALIGNMENT_BOTTOM
} StkAlignment;

struct _StkLabel {
	StkWidget parent_instance;
	StkLabelPrivate * priv;
	gchar* text;
	gboolean translucent;
	SDL_Color color;
	StkAlignment halign;
	StkAlignment valign;
};

struct _StkLabelClass {
	StkWidgetClass parent_class;
};


static gpointer synergia_connect_window_parent_class = NULL;

GType stk_widget_get_type (void) G_GNUC_CONST;
GType stk_container_get_type (void) G_GNUC_CONST;
GType stk_window_get_type (void) G_GNUC_CONST;
GType synergia_connect_window_get_type (void) G_GNUC_CONST;
GType stk_entry_get_type (void) G_GNUC_CONST;
#define SYNERGIA_CONNECT_WINDOW_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), SYNERGIA_TYPE_CONNECT_WINDOW, SynergiaConnectWindowPrivate))
enum  {
	SYNERGIA_CONNECT_WINDOW_DUMMY_PROPERTY,
	SYNERGIA_CONNECT_WINDOW_USERNAME,
	SYNERGIA_CONNECT_WINDOW_PASSWORD
};
SynergiaConnectWindow* synergia_connect_window_new (void);
SynergiaConnectWindow* synergia_connect_window_construct (GType object_type);
StkWindow* stk_window_new (void);
StkWindow* stk_window_construct (GType object_type);
StkEntry* stk_entry_new (void);
StkEntry* stk_entry_construct (GType object_type);
StkHBox* stk_hbox_new (void);
StkHBox* stk_hbox_construct (GType object_type);
GType stk_hbox_get_type (void) G_GNUC_CONST;
StkButton* stk_button_new_with_text (const gchar* text);
StkButton* stk_button_construct_with_text (GType object_type, const gchar* text);
GType stk_button_get_type (void) G_GNUC_CONST;
StkLabel* stk_label_new_with_text (const gchar* text);
StkLabel* stk_label_construct_with_text (GType object_type, const gchar* text);
GType stk_label_get_type (void) G_GNUC_CONST;
GType stk_alignment_get_type (void) G_GNUC_CONST;
void stk_container_add (StkContainer* self, StkWidget* w);
StkLabel* stk_label_new (void);
StkLabel* stk_label_construct (GType object_type);
void stk_window_set_size (StkWindow* self, gint width, gint height);
void stk_window_set_position (StkWindow* self, gint x, gint y);
void synergia_connect_window_onConnectClick (SynergiaConnectWindow* self);
static void _synergia_connect_window_onConnectClick_stk_button_clicked (StkButton* _sender, gpointer self);
void synergia_connect_window_onQuitClick (SynergiaConnectWindow* self);
static void _synergia_connect_window_onQuitClick_stk_button_clicked (StkButton* _sender, gpointer self);
const gchar* synergia_connect_window_get_username (SynergiaConnectWindow* self);
void synergia_connect_window_set_username (SynergiaConnectWindow* self, const gchar* value);
const gchar* synergia_connect_window_get_password (SynergiaConnectWindow* self);
void synergia_connect_window_set_password (SynergiaConnectWindow* self, const gchar* value);
static void synergia_connect_window_finalize (GObject* obj);
static void _vala_synergia_connect_window_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_synergia_connect_window_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


static void _synergia_connect_window_onConnectClick_stk_button_clicked (StkButton* _sender, gpointer self) {
	synergia_connect_window_onConnectClick (self);
}


static void _synergia_connect_window_onQuitClick_stk_button_clicked (StkButton* _sender, gpointer self) {
	synergia_connect_window_onQuitClick (self);
}


SynergiaConnectWindow* synergia_connect_window_construct (GType object_type) {
	SynergiaConnectWindow * self = NULL;
	StkEntry* _tmp0_;
	StkEntry* _tmp1_;
	StkHBox* _tmp2_;
	StkHBox* usernameBox;
	StkHBox* _tmp3_;
	StkHBox* passwordBox;
	StkHBox* _tmp4_;
	StkHBox* buttonBox;
	StkButton* _tmp5_;
	StkButton* connect;
	StkButton* _tmp6_;
	StkButton* quit;
	StkLabel* _tmp7_;
	StkLabel* usernameLbl;
	StkLabel* _tmp8_;
	StkLabel* passwordLbl;
	StkEntry* _tmp9_;
	StkEntry* _tmp10_;
	StkLabel* _tmp11_;
	StkLabel* _tmp12_;
	StkEntry* _tmp13_;
	StkLabel* _tmp14_;
	StkLabel* _tmp15_;
	StkLabel* _tmp16_;
	StkLabel* _tmp17_;
	StkLabel* _tmp18_;
	StkLabel* _tmp19_;
	StkLabel* _tmp20_;
	StkLabel* _tmp21_;
	gchar* _tmp22_;
	self = (SynergiaConnectWindow*) stk_window_construct (object_type);
	_tmp0_ = stk_entry_new ();
	_g_object_unref0 (self->priv->usernameEntry);
	self->priv->usernameEntry = _tmp0_;
	_tmp1_ = stk_entry_new ();
	_g_object_unref0 (self->priv->passwordEntry);
	self->priv->passwordEntry = _tmp1_;
	_tmp2_ = stk_hbox_new ();
	usernameBox = _tmp2_;
	_tmp3_ = stk_hbox_new ();
	passwordBox = _tmp3_;
	_tmp4_ = stk_hbox_new ();
	buttonBox = _tmp4_;
	_tmp5_ = stk_button_new_with_text ("Connect");
	connect = _tmp5_;
	_tmp6_ = stk_button_new_with_text ("Quit");
	quit = _tmp6_;
	_tmp7_ = stk_label_new_with_text ("Username :");
	usernameLbl = _tmp7_;
	_tmp8_ = stk_label_new_with_text ("Password :");
	passwordLbl = _tmp8_;
	_tmp9_ = self->priv->passwordEntry;
	_tmp9_->hidden = TRUE;
	usernameLbl->halign = STK_ALIGNMENT_RIGHT;
	passwordLbl->halign = STK_ALIGNMENT_RIGHT;
	stk_container_add ((StkContainer*) usernameBox, (StkWidget*) usernameLbl);
	_tmp10_ = self->priv->usernameEntry;
	stk_container_add ((StkContainer*) usernameBox, (StkWidget*) _tmp10_);
	_tmp11_ = stk_label_new ();
	_tmp12_ = _tmp11_;
	stk_container_add ((StkContainer*) usernameBox, (StkWidget*) _tmp12_);
	_g_object_unref0 (_tmp12_);
	stk_container_add ((StkContainer*) passwordBox, (StkWidget*) passwordLbl);
	_tmp13_ = self->priv->passwordEntry;
	stk_container_add ((StkContainer*) passwordBox, (StkWidget*) _tmp13_);
	_tmp14_ = stk_label_new ();
	_tmp15_ = _tmp14_;
	stk_container_add ((StkContainer*) passwordBox, (StkWidget*) _tmp15_);
	_g_object_unref0 (_tmp15_);
	_tmp16_ = stk_label_new ();
	_tmp17_ = _tmp16_;
	stk_container_add ((StkContainer*) buttonBox, (StkWidget*) _tmp17_);
	_g_object_unref0 (_tmp17_);
	stk_container_add ((StkContainer*) buttonBox, (StkWidget*) connect);
	stk_container_add ((StkContainer*) buttonBox, (StkWidget*) quit);
	_tmp18_ = stk_label_new ();
	_tmp19_ = _tmp18_;
	stk_container_add ((StkContainer*) buttonBox, (StkWidget*) _tmp19_);
	_g_object_unref0 (_tmp19_);
	stk_container_add ((StkContainer*) self, (StkWidget*) usernameBox);
	stk_container_add ((StkContainer*) self, (StkWidget*) passwordBox);
	stk_container_add ((StkContainer*) self, (StkWidget*) buttonBox);
	_tmp20_ = stk_label_new ();
	_tmp21_ = _tmp20_;
	stk_container_add ((StkContainer*) self, (StkWidget*) _tmp21_);
	_g_object_unref0 (_tmp21_);
	stk_window_set_size ((StkWindow*) self, 400, 200);
	stk_window_set_position ((StkWindow*) self, 120, 240);
	_tmp22_ = g_strdup ("Connect");
	_g_free0 (((StkWindow*) self)->title);
	((StkWindow*) self)->title = _tmp22_;
	((StkWindow*) self)->opacity = (guchar) 0;
	g_signal_connect_object (connect, "clicked", (GCallback) _synergia_connect_window_onConnectClick_stk_button_clicked, self, 0);
	g_signal_connect_object (quit, "clicked", (GCallback) _synergia_connect_window_onQuitClick_stk_button_clicked, self, 0);
	_g_object_unref0 (passwordLbl);
	_g_object_unref0 (usernameLbl);
	_g_object_unref0 (quit);
	_g_object_unref0 (connect);
	_g_object_unref0 (buttonBox);
	_g_object_unref0 (passwordBox);
	_g_object_unref0 (usernameBox);
	return self;
}


SynergiaConnectWindow* synergia_connect_window_new (void) {
	return synergia_connect_window_construct (SYNERGIA_TYPE_CONNECT_WINDOW);
}


void synergia_connect_window_onQuitClick (SynergiaConnectWindow* self) {
	g_return_if_fail (self != NULL);
	g_signal_emit_by_name (self, "quit");
}


void synergia_connect_window_onConnectClick (SynergiaConnectWindow* self) {
	g_return_if_fail (self != NULL);
	g_signal_emit_by_name (self, "validate");
}


const gchar* synergia_connect_window_get_username (SynergiaConnectWindow* self) {
	const gchar* result;
	StkEntry* _tmp0_;
	const gchar* _tmp1_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->usernameEntry;
	_tmp1_ = _tmp0_->text;
	result = _tmp1_;
	return result;
}


void synergia_connect_window_set_username (SynergiaConnectWindow* self, const gchar* value) {
	StkEntry* _tmp0_;
	const gchar* _tmp1_;
	gchar* _tmp2_;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->usernameEntry;
	_tmp1_ = value;
	_tmp2_ = g_strdup (_tmp1_);
	_g_free0 (_tmp0_->text);
	_tmp0_->text = _tmp2_;
	g_object_notify ((GObject *) self, "username");
}


const gchar* synergia_connect_window_get_password (SynergiaConnectWindow* self) {
	const gchar* result;
	StkEntry* _tmp0_;
	const gchar* _tmp1_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->passwordEntry;
	_tmp1_ = _tmp0_->text;
	result = _tmp1_;
	return result;
}


void synergia_connect_window_set_password (SynergiaConnectWindow* self, const gchar* value) {
	StkEntry* _tmp0_;
	const gchar* _tmp1_;
	gchar* _tmp2_;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->passwordEntry;
	_tmp1_ = value;
	_tmp2_ = g_strdup (_tmp1_);
	_g_free0 (_tmp0_->text);
	_tmp0_->text = _tmp2_;
	g_object_notify ((GObject *) self, "password");
}


static void synergia_connect_window_class_init (SynergiaConnectWindowClass * klass) {
	synergia_connect_window_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (SynergiaConnectWindowPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_synergia_connect_window_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_synergia_connect_window_set_property;
	G_OBJECT_CLASS (klass)->finalize = synergia_connect_window_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), SYNERGIA_CONNECT_WINDOW_USERNAME, g_param_spec_string ("username", "username", "username", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SYNERGIA_CONNECT_WINDOW_PASSWORD, g_param_spec_string ("password", "password", "password", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_signal_new ("quit", SYNERGIA_TYPE_CONNECT_WINDOW, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
	g_signal_new ("validate", SYNERGIA_TYPE_CONNECT_WINDOW, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
}


static void synergia_connect_window_instance_init (SynergiaConnectWindow * self) {
	self->priv = SYNERGIA_CONNECT_WINDOW_GET_PRIVATE (self);
}


static void synergia_connect_window_finalize (GObject* obj) {
	SynergiaConnectWindow * self;
	self = SYNERGIA_CONNECT_WINDOW (obj);
	_g_object_unref0 (self->priv->usernameEntry);
	_g_object_unref0 (self->priv->passwordEntry);
	G_OBJECT_CLASS (synergia_connect_window_parent_class)->finalize (obj);
}


GType synergia_connect_window_get_type (void) {
	static volatile gsize synergia_connect_window_type_id__volatile = 0;
	if (g_once_init_enter (&synergia_connect_window_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (SynergiaConnectWindowClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) synergia_connect_window_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (SynergiaConnectWindow), 0, (GInstanceInitFunc) synergia_connect_window_instance_init, NULL };
		GType synergia_connect_window_type_id;
		synergia_connect_window_type_id = g_type_register_static (STK_TYPE_WINDOW, "SynergiaConnectWindow", &g_define_type_info, 0);
		g_once_init_leave (&synergia_connect_window_type_id__volatile, synergia_connect_window_type_id);
	}
	return synergia_connect_window_type_id__volatile;
}


static void _vala_synergia_connect_window_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	SynergiaConnectWindow * self;
	self = SYNERGIA_CONNECT_WINDOW (object);
	switch (property_id) {
		case SYNERGIA_CONNECT_WINDOW_USERNAME:
		g_value_set_string (value, synergia_connect_window_get_username (self));
		break;
		case SYNERGIA_CONNECT_WINDOW_PASSWORD:
		g_value_set_string (value, synergia_connect_window_get_password (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_synergia_connect_window_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	SynergiaConnectWindow * self;
	self = SYNERGIA_CONNECT_WINDOW (object);
	switch (property_id) {
		case SYNERGIA_CONNECT_WINDOW_USERNAME:
		synergia_connect_window_set_username (self, g_value_get_string (value));
		break;
		case SYNERGIA_CONNECT_WINDOW_PASSWORD:
		synergia_connect_window_set_password (self, g_value_get_string (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



