/* events.c generated by valac 0.16.0, the Vala compiler
 * generated from events.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gobject/gvaluecollector.h>


#define SYNERGIA_TYPE_EVENTS (synergia_events_get_type ())
#define SYNERGIA_EVENTS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYNERGIA_TYPE_EVENTS, SynergiaEvents))
#define SYNERGIA_EVENTS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYNERGIA_TYPE_EVENTS, SynergiaEventsClass))
#define SYNERGIA_IS_EVENTS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYNERGIA_TYPE_EVENTS))
#define SYNERGIA_IS_EVENTS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYNERGIA_TYPE_EVENTS))
#define SYNERGIA_EVENTS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYNERGIA_TYPE_EVENTS, SynergiaEventsClass))

typedef struct _SynergiaEvents SynergiaEvents;
typedef struct _SynergiaEventsClass SynergiaEventsClass;
typedef struct _SynergiaEventsPrivate SynergiaEventsPrivate;
typedef struct _SynergiaParamSpecEvents SynergiaParamSpecEvents;

struct _SynergiaEvents {
	GTypeInstance parent_instance;
	volatile int ref_count;
	SynergiaEventsPrivate * priv;
};

struct _SynergiaEventsClass {
	GTypeClass parent_class;
	void (*finalize) (SynergiaEvents *self);
};

struct _SynergiaParamSpecEvents {
	GParamSpec parent_instance;
};


static gpointer synergia_events_parent_class = NULL;

gpointer synergia_events_ref (gpointer instance);
void synergia_events_unref (gpointer instance);
GParamSpec* synergia_param_spec_events (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void synergia_value_set_events (GValue* value, gpointer v_object);
void synergia_value_take_events (GValue* value, gpointer v_object);
gpointer synergia_value_get_events (const GValue* value);
GType synergia_events_get_type (void) G_GNUC_CONST;
enum  {
	SYNERGIA_EVENTS_DUMMY_PROPERTY
};
void synergia_events_raise (SynergiaEvents* self, const gchar* eventName, gchar** command, int command_length1);
SynergiaEvents* synergia_events_new (void);
SynergiaEvents* synergia_events_construct (GType object_type);
static void g_cclosure_user_marshal_VOID__BOXED_INT (GClosure * closure, GValue * return_value, guint n_param_values, const GValue * param_values, gpointer invocation_hint, gpointer marshal_data);
static void g_cclosure_user_marshal_VOID__INT_STRING (GClosure * closure, GValue * return_value, guint n_param_values, const GValue * param_values, gpointer invocation_hint, gpointer marshal_data);
static void synergia_events_finalize (SynergiaEvents* obj);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);


void synergia_events_raise (SynergiaEvents* self, const gchar* eventName, gchar** command, int command_length1) {
	const gchar* _tmp0_;
	const gchar* _tmp1_;
	GQuark _tmp3_ = 0U;
	static GQuark _tmp2_label0 = 0;
	static GQuark _tmp2_label1 = 0;
	static GQuark _tmp2_label2 = 0;
	static GQuark _tmp2_label3 = 0;
	static GQuark _tmp2_label4 = 0;
	static GQuark _tmp2_label5 = 0;
	static GQuark _tmp2_label6 = 0;
	static GQuark _tmp2_label7 = 0;
	static GQuark _tmp2_label8 = 0;
	static GQuark _tmp2_label9 = 0;
	static GQuark _tmp2_label10 = 0;
	static GQuark _tmp2_label11 = 0;
	static GQuark _tmp2_label12 = 0;
	g_return_if_fail (self != NULL);
	g_return_if_fail (eventName != NULL);
	_tmp0_ = eventName;
	_tmp1_ = _tmp0_;
	_tmp3_ = (NULL == _tmp1_) ? 0 : g_quark_from_string (_tmp1_);
	if (_tmp3_ == ((0 != _tmp2_label0) ? _tmp2_label0 : (_tmp2_label0 = g_quark_from_static_string ("ping")))) {
		switch (0) {
			default:
			{
				gchar** _tmp4_;
				gint _tmp4__length1;
				_tmp4_ = command;
				_tmp4__length1 = command_length1;
				g_signal_emit_by_name (self, "ping", _tmp4_, _tmp4__length1);
				break;
			}
		}
	} else if (_tmp3_ == ((0 != _tmp2_label1) ? _tmp2_label1 : (_tmp2_label1 = g_quark_from_static_string ("connect")))) {
		switch (0) {
			default:
			{
				gchar** _tmp5_;
				gint _tmp5__length1;
				_tmp5_ = command;
				_tmp5__length1 = command_length1;
				g_signal_emit_by_name (self, "connect", _tmp5_, _tmp5__length1);
				break;
			}
		}
	} else if (_tmp3_ == ((0 != _tmp2_label2) ? _tmp2_label2 : (_tmp2_label2 = g_quark_from_static_string ("error")))) {
		switch (0) {
			default:
			{
				gchar** _tmp6_;
				gint _tmp6__length1;
				const gchar* _tmp7_;
				gint _tmp8_ = 0;
				gchar** _tmp9_;
				gint _tmp9__length1;
				const gchar* _tmp10_;
				_tmp6_ = command;
				_tmp6__length1 = command_length1;
				_tmp7_ = _tmp6_[0];
				_tmp8_ = atoi (_tmp7_);
				_tmp9_ = command;
				_tmp9__length1 = command_length1;
				_tmp10_ = _tmp9_[1];
				g_signal_emit_by_name (self, "error", _tmp8_, _tmp10_);
				break;
			}
		}
	} else if (_tmp3_ == ((0 != _tmp2_label3) ? _tmp2_label3 : (_tmp2_label3 = g_quark_from_static_string ("player-character")))) {
		switch (0) {
			default:
			{
				gchar** _tmp11_;
				gint _tmp11__length1;
				_tmp11_ = command;
				_tmp11__length1 = command_length1;
				g_signal_emit_by_name (self, "player-character", _tmp11_, _tmp11__length1);
				break;
			}
		}
	} else if (_tmp3_ == ((0 != _tmp2_label4) ? _tmp2_label4 : (_tmp2_label4 = g_quark_from_static_string ("change-tileset")))) {
		switch (0) {
			default:
			{
				gchar** _tmp12_;
				gint _tmp12__length1;
				_tmp12_ = command;
				_tmp12__length1 = command_length1;
				g_signal_emit_by_name (self, "change-tileset", _tmp12_, _tmp12__length1);
				break;
			}
		}
	} else if (_tmp3_ == ((0 != _tmp2_label5) ? _tmp2_label5 : (_tmp2_label5 = g_quark_from_static_string ("position")))) {
		switch (0) {
			default:
			{
				gchar** _tmp13_;
				gint _tmp13__length1;
				_tmp13_ = command;
				_tmp13__length1 = command_length1;
				g_signal_emit_by_name (self, "position", _tmp13_, _tmp13__length1);
				break;
			}
		}
	} else if (_tmp3_ == ((0 != _tmp2_label6) ? _tmp2_label6 : (_tmp2_label6 = g_quark_from_static_string ("character")))) {
		switch (0) {
			default:
			{
				gchar** _tmp14_;
				gint _tmp14__length1;
				_tmp14_ = command;
				_tmp14__length1 = command_length1;
				g_signal_emit_by_name (self, "character", _tmp14_, _tmp14__length1);
				break;
			}
		}
	} else if (_tmp3_ == ((0 != _tmp2_label7) ? _tmp2_label7 : (_tmp2_label7 = g_quark_from_static_string ("character-out")))) {
		switch (0) {
			default:
			{
				gchar** _tmp15_;
				gint _tmp15__length1;
				_tmp15_ = command;
				_tmp15__length1 = command_length1;
				g_signal_emit_by_name (self, "character-out", _tmp15_, _tmp15__length1);
				break;
			}
		}
	} else if (_tmp3_ == ((0 != _tmp2_label8) ? _tmp2_label8 : (_tmp2_label8 = g_quark_from_static_string ("chunk")))) {
		switch (0) {
			default:
			{
				gchar** _tmp16_;
				gint _tmp16__length1;
				_tmp16_ = command;
				_tmp16__length1 = command_length1;
				g_signal_emit_by_name (self, "chunk", _tmp16_, _tmp16__length1);
				break;
			}
		}
	} else if (_tmp3_ == ((0 != _tmp2_label9) ? _tmp2_label9 : (_tmp2_label9 = g_quark_from_static_string ("moveleft")))) {
		switch (0) {
			default:
			{
				gchar** _tmp17_;
				gint _tmp17__length1;
				_tmp17_ = command;
				_tmp17__length1 = command_length1;
				g_signal_emit_by_name (self, "moveleft", _tmp17_, _tmp17__length1);
				break;
			}
		}
	} else if (_tmp3_ == ((0 != _tmp2_label10) ? _tmp2_label10 : (_tmp2_label10 = g_quark_from_static_string ("moveup")))) {
		switch (0) {
			default:
			{
				gchar** _tmp18_;
				gint _tmp18__length1;
				_tmp18_ = command;
				_tmp18__length1 = command_length1;
				g_signal_emit_by_name (self, "moveup", _tmp18_, _tmp18__length1);
				break;
			}
		}
	} else if (_tmp3_ == ((0 != _tmp2_label11) ? _tmp2_label11 : (_tmp2_label11 = g_quark_from_static_string ("moveright")))) {
		switch (0) {
			default:
			{
				gchar** _tmp19_;
				gint _tmp19__length1;
				_tmp19_ = command;
				_tmp19__length1 = command_length1;
				g_signal_emit_by_name (self, "moveright", _tmp19_, _tmp19__length1);
				break;
			}
		}
	} else if (_tmp3_ == ((0 != _tmp2_label12) ? _tmp2_label12 : (_tmp2_label12 = g_quark_from_static_string ("movedown")))) {
		switch (0) {
			default:
			{
				gchar** _tmp20_;
				gint _tmp20__length1;
				_tmp20_ = command;
				_tmp20__length1 = command_length1;
				g_signal_emit_by_name (self, "movedown", _tmp20_, _tmp20__length1);
				break;
			}
		}
	} else {
		switch (0) {
			default:
			{
				const gchar* _tmp21_;
				gchar* _tmp22_;
				gchar** _tmp23_ = NULL;
				gchar** _tmp24_;
				gint _tmp24__length1;
				_tmp21_ = eventName;
				_tmp22_ = g_strdup (_tmp21_);
				_tmp23_ = g_new0 (gchar*, 1 + 1);
				_tmp23_[0] = _tmp22_;
				_tmp24_ = _tmp23_;
				_tmp24__length1 = 1;
				g_signal_emit_by_name (self, "not-found", _tmp24_, 1);
				_tmp24_ = (_vala_array_free (_tmp24_, _tmp24__length1, (GDestroyNotify) g_free), NULL);
				break;
			}
		}
	}
}


SynergiaEvents* synergia_events_construct (GType object_type) {
	SynergiaEvents* self = NULL;
	self = (SynergiaEvents*) g_type_create_instance (object_type);
	return self;
}


SynergiaEvents* synergia_events_new (void) {
	return synergia_events_construct (SYNERGIA_TYPE_EVENTS);
}


static void g_cclosure_user_marshal_VOID__BOXED_INT (GClosure * closure, GValue * return_value, guint n_param_values, const GValue * param_values, gpointer invocation_hint, gpointer marshal_data) {
	typedef void (*GMarshalFunc_VOID__BOXED_INT) (gpointer data1, gpointer arg_1, gint arg_2, gpointer data2);
	register GMarshalFunc_VOID__BOXED_INT callback;
	register GCClosure * cc;
	register gpointer data1;
	register gpointer data2;
	cc = (GCClosure *) closure;
	g_return_if_fail (n_param_values == 3);
	if (G_CCLOSURE_SWAP_DATA (closure)) {
		data1 = closure->data;
		data2 = param_values->data[0].v_pointer;
	} else {
		data1 = param_values->data[0].v_pointer;
		data2 = closure->data;
	}
	callback = (GMarshalFunc_VOID__BOXED_INT) (marshal_data ? marshal_data : cc->callback);
	callback (data1, g_value_get_boxed (param_values + 1), g_value_get_int (param_values + 2), data2);
}


static void g_cclosure_user_marshal_VOID__INT_STRING (GClosure * closure, GValue * return_value, guint n_param_values, const GValue * param_values, gpointer invocation_hint, gpointer marshal_data) {
	typedef void (*GMarshalFunc_VOID__INT_STRING) (gpointer data1, gint arg_1, const char* arg_2, gpointer data2);
	register GMarshalFunc_VOID__INT_STRING callback;
	register GCClosure * cc;
	register gpointer data1;
	register gpointer data2;
	cc = (GCClosure *) closure;
	g_return_if_fail (n_param_values == 3);
	if (G_CCLOSURE_SWAP_DATA (closure)) {
		data1 = closure->data;
		data2 = param_values->data[0].v_pointer;
	} else {
		data1 = param_values->data[0].v_pointer;
		data2 = closure->data;
	}
	callback = (GMarshalFunc_VOID__INT_STRING) (marshal_data ? marshal_data : cc->callback);
	callback (data1, g_value_get_int (param_values + 1), g_value_get_string (param_values + 2), data2);
}


static void synergia_value_events_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void synergia_value_events_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		synergia_events_unref (value->data[0].v_pointer);
	}
}


static void synergia_value_events_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = synergia_events_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer synergia_value_events_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* synergia_value_events_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		SynergiaEvents* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = synergia_events_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* synergia_value_events_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	SynergiaEvents** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = synergia_events_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* synergia_param_spec_events (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	SynergiaParamSpecEvents* spec;
	g_return_val_if_fail (g_type_is_a (object_type, SYNERGIA_TYPE_EVENTS), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer synergia_value_get_events (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, SYNERGIA_TYPE_EVENTS), NULL);
	return value->data[0].v_pointer;
}


void synergia_value_set_events (GValue* value, gpointer v_object) {
	SynergiaEvents* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, SYNERGIA_TYPE_EVENTS));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, SYNERGIA_TYPE_EVENTS));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		synergia_events_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		synergia_events_unref (old);
	}
}


void synergia_value_take_events (GValue* value, gpointer v_object) {
	SynergiaEvents* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, SYNERGIA_TYPE_EVENTS));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, SYNERGIA_TYPE_EVENTS));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		synergia_events_unref (old);
	}
}


static void synergia_events_class_init (SynergiaEventsClass * klass) {
	synergia_events_parent_class = g_type_class_peek_parent (klass);
	SYNERGIA_EVENTS_CLASS (klass)->finalize = synergia_events_finalize;
	g_signal_new ("ping", SYNERGIA_TYPE_EVENTS, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_user_marshal_VOID__BOXED_INT, G_TYPE_NONE, 2, G_TYPE_STRV, G_TYPE_INT);
	g_signal_new ("connect", SYNERGIA_TYPE_EVENTS, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_user_marshal_VOID__BOXED_INT, G_TYPE_NONE, 2, G_TYPE_STRV, G_TYPE_INT);
	g_signal_new ("not_found", SYNERGIA_TYPE_EVENTS, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_user_marshal_VOID__BOXED_INT, G_TYPE_NONE, 2, G_TYPE_STRV, G_TYPE_INT);
	g_signal_new ("player_character", SYNERGIA_TYPE_EVENTS, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_user_marshal_VOID__BOXED_INT, G_TYPE_NONE, 2, G_TYPE_STRV, G_TYPE_INT);
	g_signal_new ("change_tileset", SYNERGIA_TYPE_EVENTS, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_user_marshal_VOID__BOXED_INT, G_TYPE_NONE, 2, G_TYPE_STRV, G_TYPE_INT);
	g_signal_new ("character_out", SYNERGIA_TYPE_EVENTS, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_user_marshal_VOID__BOXED_INT, G_TYPE_NONE, 2, G_TYPE_STRV, G_TYPE_INT);
	g_signal_new ("position", SYNERGIA_TYPE_EVENTS, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_user_marshal_VOID__BOXED_INT, G_TYPE_NONE, 2, G_TYPE_STRV, G_TYPE_INT);
	g_signal_new ("character", SYNERGIA_TYPE_EVENTS, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_user_marshal_VOID__BOXED_INT, G_TYPE_NONE, 2, G_TYPE_STRV, G_TYPE_INT);
	g_signal_new ("chunk", SYNERGIA_TYPE_EVENTS, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_user_marshal_VOID__BOXED_INT, G_TYPE_NONE, 2, G_TYPE_STRV, G_TYPE_INT);
	g_signal_new ("moveleft", SYNERGIA_TYPE_EVENTS, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_user_marshal_VOID__BOXED_INT, G_TYPE_NONE, 2, G_TYPE_STRV, G_TYPE_INT);
	g_signal_new ("moveup", SYNERGIA_TYPE_EVENTS, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_user_marshal_VOID__BOXED_INT, G_TYPE_NONE, 2, G_TYPE_STRV, G_TYPE_INT);
	g_signal_new ("moveright", SYNERGIA_TYPE_EVENTS, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_user_marshal_VOID__BOXED_INT, G_TYPE_NONE, 2, G_TYPE_STRV, G_TYPE_INT);
	g_signal_new ("movedown", SYNERGIA_TYPE_EVENTS, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_user_marshal_VOID__BOXED_INT, G_TYPE_NONE, 2, G_TYPE_STRV, G_TYPE_INT);
	g_signal_new ("error", SYNERGIA_TYPE_EVENTS, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_user_marshal_VOID__INT_STRING, G_TYPE_NONE, 2, G_TYPE_INT, G_TYPE_STRING);
}


static void synergia_events_instance_init (SynergiaEvents * self) {
	self->ref_count = 1;
}


static void synergia_events_finalize (SynergiaEvents* obj) {
	SynergiaEvents * self;
	self = SYNERGIA_EVENTS (obj);
}


GType synergia_events_get_type (void) {
	static volatile gsize synergia_events_type_id__volatile = 0;
	if (g_once_init_enter (&synergia_events_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { synergia_value_events_init, synergia_value_events_free_value, synergia_value_events_copy_value, synergia_value_events_peek_pointer, "p", synergia_value_events_collect_value, "p", synergia_value_events_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (SynergiaEventsClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) synergia_events_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (SynergiaEvents), 0, (GInstanceInitFunc) synergia_events_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType synergia_events_type_id;
		synergia_events_type_id = g_type_register_fundamental (g_type_fundamental_next (), "SynergiaEvents", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&synergia_events_type_id__volatile, synergia_events_type_id);
	}
	return synergia_events_type_id__volatile;
}


gpointer synergia_events_ref (gpointer instance) {
	SynergiaEvents* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void synergia_events_unref (gpointer instance) {
	SynergiaEvents* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		SYNERGIA_EVENTS_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



