/* main.c generated by valac 0.16.0, the Vala compiler
 * generated from main.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <SDL.h>
#include <gee.h>
#include <stdlib.h>
#include <string.h>
#include <gio/gio.h>
#include <SDL_ttf.h>
#include <stdio.h>
#include <gobject/gvaluecollector.h>


#define SYNERGIA_TYPE_MAIN (synergia_main_get_type ())
#define SYNERGIA_MAIN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYNERGIA_TYPE_MAIN, SynergiaMain))
#define SYNERGIA_MAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYNERGIA_TYPE_MAIN, SynergiaMainClass))
#define SYNERGIA_IS_MAIN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYNERGIA_TYPE_MAIN))
#define SYNERGIA_IS_MAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYNERGIA_TYPE_MAIN))
#define SYNERGIA_MAIN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYNERGIA_TYPE_MAIN, SynergiaMainClass))

typedef struct _SynergiaMain SynergiaMain;
typedef struct _SynergiaMainClass SynergiaMainClass;
typedef struct _SynergiaMainPrivate SynergiaMainPrivate;

#define SYNERGIA_TYPE_NET_CONNECTOR (synergia_net_connector_get_type ())
#define SYNERGIA_NET_CONNECTOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYNERGIA_TYPE_NET_CONNECTOR, SynergiaNetConnector))
#define SYNERGIA_NET_CONNECTOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYNERGIA_TYPE_NET_CONNECTOR, SynergiaNetConnectorClass))
#define SYNERGIA_IS_NET_CONNECTOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYNERGIA_TYPE_NET_CONNECTOR))
#define SYNERGIA_IS_NET_CONNECTOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYNERGIA_TYPE_NET_CONNECTOR))
#define SYNERGIA_NET_CONNECTOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYNERGIA_TYPE_NET_CONNECTOR, SynergiaNetConnectorClass))

typedef struct _SynergiaNetConnector SynergiaNetConnector;
typedef struct _SynergiaNetConnectorClass SynergiaNetConnectorClass;

#define STK_TYPE_WIDGET (stk_widget_get_type ())
#define STK_WIDGET(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), STK_TYPE_WIDGET, StkWidget))
#define STK_WIDGET_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), STK_TYPE_WIDGET, StkWidgetClass))
#define STK_IS_WIDGET(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), STK_TYPE_WIDGET))
#define STK_IS_WIDGET_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), STK_TYPE_WIDGET))
#define STK_WIDGET_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), STK_TYPE_WIDGET, StkWidgetClass))

typedef struct _StkWidget StkWidget;
typedef struct _StkWidgetClass StkWidgetClass;

#define SYNERGIA_TYPE_CHARACTER (synergia_character_get_type ())
#define SYNERGIA_CHARACTER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYNERGIA_TYPE_CHARACTER, SynergiaCharacter))
#define SYNERGIA_CHARACTER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYNERGIA_TYPE_CHARACTER, SynergiaCharacterClass))
#define SYNERGIA_IS_CHARACTER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYNERGIA_TYPE_CHARACTER))
#define SYNERGIA_IS_CHARACTER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYNERGIA_TYPE_CHARACTER))
#define SYNERGIA_CHARACTER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYNERGIA_TYPE_CHARACTER, SynergiaCharacterClass))

typedef struct _SynergiaCharacter SynergiaCharacter;
typedef struct _SynergiaCharacterClass SynergiaCharacterClass;

#define SYNERGIA_TYPE_PLAYER (synergia_player_get_type ())
#define SYNERGIA_PLAYER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYNERGIA_TYPE_PLAYER, SynergiaPlayer))
#define SYNERGIA_PLAYER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYNERGIA_TYPE_PLAYER, SynergiaPlayerClass))
#define SYNERGIA_IS_PLAYER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYNERGIA_TYPE_PLAYER))
#define SYNERGIA_IS_PLAYER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYNERGIA_TYPE_PLAYER))
#define SYNERGIA_PLAYER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYNERGIA_TYPE_PLAYER, SynergiaPlayerClass))

typedef struct _SynergiaPlayer SynergiaPlayer;
typedef struct _SynergiaPlayerClass SynergiaPlayerClass;

#define SYNERGIA_TYPE_MAP (synergia_map_get_type ())
#define SYNERGIA_MAP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYNERGIA_TYPE_MAP, SynergiaMap))
#define SYNERGIA_MAP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYNERGIA_TYPE_MAP, SynergiaMapClass))
#define SYNERGIA_IS_MAP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYNERGIA_TYPE_MAP))
#define SYNERGIA_IS_MAP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYNERGIA_TYPE_MAP))
#define SYNERGIA_MAP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYNERGIA_TYPE_MAP, SynergiaMapClass))

typedef struct _SynergiaMap SynergiaMap;
typedef struct _SynergiaMapClass SynergiaMapClass;

#define STK_TYPE_CONTAINER (stk_container_get_type ())
#define STK_CONTAINER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), STK_TYPE_CONTAINER, StkContainer))
#define STK_CONTAINER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), STK_TYPE_CONTAINER, StkContainerClass))
#define STK_IS_CONTAINER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), STK_TYPE_CONTAINER))
#define STK_IS_CONTAINER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), STK_TYPE_CONTAINER))
#define STK_CONTAINER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), STK_TYPE_CONTAINER, StkContainerClass))

typedef struct _StkContainer StkContainer;
typedef struct _StkContainerClass StkContainerClass;

#define STK_TYPE_WINDOW (stk_window_get_type ())
#define STK_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), STK_TYPE_WINDOW, StkWindow))
#define STK_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), STK_TYPE_WINDOW, StkWindowClass))
#define STK_IS_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), STK_TYPE_WINDOW))
#define STK_IS_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), STK_TYPE_WINDOW))
#define STK_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), STK_TYPE_WINDOW, StkWindowClass))

typedef struct _StkWindow StkWindow;
typedef struct _StkWindowClass StkWindowClass;

#define SYNERGIA_TYPE_CONNECT_WINDOW (synergia_connect_window_get_type ())
#define SYNERGIA_CONNECT_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYNERGIA_TYPE_CONNECT_WINDOW, SynergiaConnectWindow))
#define SYNERGIA_CONNECT_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYNERGIA_TYPE_CONNECT_WINDOW, SynergiaConnectWindowClass))
#define SYNERGIA_IS_CONNECT_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYNERGIA_TYPE_CONNECT_WINDOW))
#define SYNERGIA_IS_CONNECT_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYNERGIA_TYPE_CONNECT_WINDOW))
#define SYNERGIA_CONNECT_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYNERGIA_TYPE_CONNECT_WINDOW, SynergiaConnectWindowClass))

typedef struct _SynergiaConnectWindow SynergiaConnectWindow;
typedef struct _SynergiaConnectWindowClass SynergiaConnectWindowClass;

#define SYNERGIA_TYPE_STATUS_WINDOW (synergia_status_window_get_type ())
#define SYNERGIA_STATUS_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYNERGIA_TYPE_STATUS_WINDOW, SynergiaStatusWindow))
#define SYNERGIA_STATUS_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYNERGIA_TYPE_STATUS_WINDOW, SynergiaStatusWindowClass))
#define SYNERGIA_IS_STATUS_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYNERGIA_TYPE_STATUS_WINDOW))
#define SYNERGIA_IS_STATUS_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYNERGIA_TYPE_STATUS_WINDOW))
#define SYNERGIA_STATUS_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYNERGIA_TYPE_STATUS_WINDOW, SynergiaStatusWindowClass))

typedef struct _SynergiaStatusWindow SynergiaStatusWindow;
typedef struct _SynergiaStatusWindowClass SynergiaStatusWindowClass;

#define STK_TYPE_LABEL (stk_label_get_type ())
#define STK_LABEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), STK_TYPE_LABEL, StkLabel))
#define STK_LABEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), STK_TYPE_LABEL, StkLabelClass))
#define STK_IS_LABEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), STK_TYPE_LABEL))
#define STK_IS_LABEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), STK_TYPE_LABEL))
#define STK_LABEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), STK_TYPE_LABEL, StkLabelClass))

typedef struct _StkLabel StkLabel;
typedef struct _StkLabelClass StkLabelClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _synergia_net_connector_unref0(var) ((var == NULL) ? NULL : (var = (synergia_net_connector_unref (var), NULL)))
typedef struct _SynergiaNetConnectorPrivate SynergiaNetConnectorPrivate;

#define SYNERGIA_TYPE_EVENTS (synergia_events_get_type ())
#define SYNERGIA_EVENTS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYNERGIA_TYPE_EVENTS, SynergiaEvents))
#define SYNERGIA_EVENTS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYNERGIA_TYPE_EVENTS, SynergiaEventsClass))
#define SYNERGIA_IS_EVENTS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYNERGIA_TYPE_EVENTS))
#define SYNERGIA_IS_EVENTS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYNERGIA_TYPE_EVENTS))
#define SYNERGIA_EVENTS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYNERGIA_TYPE_EVENTS, SynergiaEventsClass))

typedef struct _SynergiaEvents SynergiaEvents;
typedef struct _SynergiaEventsClass SynergiaEventsClass;

#define STK_TYPE_EVENTS (stk_events_get_type ())
#define STK_EVENTS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), STK_TYPE_EVENTS, StkEvents))
#define STK_EVENTS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), STK_TYPE_EVENTS, StkEventsClass))
#define STK_IS_EVENTS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), STK_TYPE_EVENTS))
#define STK_IS_EVENTS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), STK_TYPE_EVENTS))
#define STK_EVENTS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), STK_TYPE_EVENTS, StkEventsClass))

typedef struct _StkEvents StkEvents;
typedef struct _StkEventsClass StkEventsClass;

#define STK_TYPE_ALIGNMENT (stk_alignment_get_type ())
typedef struct _StkWidgetPrivate StkWidgetPrivate;
typedef struct _StkLabelPrivate StkLabelPrivate;

#define STK_TYPE_STACK (stk_stack_get_type ())
#define STK_STACK(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), STK_TYPE_STACK, StkStack))
#define STK_STACK_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), STK_TYPE_STACK, StkStackClass))
#define STK_IS_STACK(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), STK_TYPE_STACK))
#define STK_IS_STACK_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), STK_TYPE_STACK))
#define STK_STACK_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), STK_TYPE_STACK, StkStackClass))

typedef struct _StkStack StkStack;
typedef struct _StkStackClass StkStackClass;

#define STK_TYPE_IMAGE (stk_image_get_type ())
#define STK_IMAGE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), STK_TYPE_IMAGE, StkImage))
#define STK_IMAGE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), STK_TYPE_IMAGE, StkImageClass))
#define STK_IS_IMAGE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), STK_TYPE_IMAGE))
#define STK_IS_IMAGE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), STK_TYPE_IMAGE))
#define STK_IMAGE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), STK_TYPE_IMAGE, StkImageClass))

typedef struct _StkImage StkImage;
typedef struct _StkImageClass StkImageClass;
#define _g_free0(var) (var = (g_free (var), NULL))
typedef struct _SynergiaCharacterPrivate SynergiaCharacterPrivate;

#define SYNERGIA_TYPE_ORIENTATION (synergia_orientation_get_type ())
#define _synergia_main_unref0(var) ((var == NULL) ? NULL : (var = (synergia_main_unref (var), NULL)))
typedef struct _SynergiaParamSpecMain SynergiaParamSpecMain;

struct _SynergiaMain {
	GTypeInstance parent_instance;
	volatile int ref_count;
	SynergiaMainPrivate * priv;
	SDL_Surface* screen;
	SynergiaNetConnector* net;
	SynergiaPlayer* self;
	SynergiaMap* map;
};

struct _SynergiaMainClass {
	GTypeClass parent_class;
	void (*finalize) (SynergiaMain *self);
};

struct _SynergiaMainPrivate {
	SynergiaConnectWindow* connect_window;
	SynergiaStatusWindow* status;
	GeeList* characters;
	StkLabel* fpscount;
	gboolean stop;
	gint fps;
};

struct _SynergiaNetConnector {
	GTypeInstance parent_instance;
	volatile int ref_count;
	SynergiaNetConnectorPrivate * priv;
	gchar* address;
	gint port;
	GSocket* socket;
	SynergiaEvents* events;
};

struct _SynergiaNetConnectorClass {
	GTypeClass parent_class;
	void (*finalize) (SynergiaNetConnector *self);
};

typedef enum  {
	STK_ALIGNMENT_LEFT,
	STK_ALIGNMENT_RIGHT,
	STK_ALIGNMENT_CENTER,
	STK_ALIGNMENT_TOP,
	STK_ALIGNMENT_MIDDLE,
	STK_ALIGNMENT_BOTTOM
} StkAlignment;

struct _StkWidget {
	GObject parent_instance;
	StkWidgetPrivate * priv;
	SDL_Rect rect;
	gboolean focused;
};

struct _StkWidgetClass {
	GObjectClass parent_class;
	gboolean (*draw) (StkWidget* self, SDL_Surface* screen);
};

struct _StkLabel {
	StkWidget parent_instance;
	StkLabelPrivate * priv;
	gchar* text;
	gboolean translucent;
	SDL_Color color;
	StkAlignment halign;
	StkAlignment valign;
};

struct _StkLabelClass {
	StkWidgetClass parent_class;
};

typedef enum  {
	SYNERGIA_ORIENTATION_NORTH = 3,
	SYNERGIA_ORIENTATION_SOUTH = 0,
	SYNERGIA_ORIENTATION_EAST = 2,
	SYNERGIA_ORIENTATION_WEST = 1
} SynergiaOrientation;

struct _SynergiaCharacter {
	StkWidget parent_instance;
	SynergiaCharacterPrivate * priv;
	SDL_Surface* sprite;
	SDL_Surface* nameSurface;
	SynergiaOrientation orientation;
	gint frame;
	SDL_Rect pos;
	SDL_Rect offset;
	gint id;
	gint16 motion;
	gchar* name;
	gint16 move_offset;
	SynergiaOrientation move_orientation;
};

struct _SynergiaCharacterClass {
	StkWidgetClass parent_class;
};

struct _SynergiaParamSpecMain {
	GParamSpec parent_instance;
};


static gpointer synergia_main_parent_class = NULL;
extern StkEvents* stk_stk_events;
extern StkStack* stk_stk_workspace;

gpointer synergia_main_ref (gpointer instance);
void synergia_main_unref (gpointer instance);
GParamSpec* synergia_param_spec_main (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void synergia_value_set_main (GValue* value, gpointer v_object);
void synergia_value_take_main (GValue* value, gpointer v_object);
gpointer synergia_value_get_main (const GValue* value);
GType synergia_main_get_type (void) G_GNUC_CONST;
gpointer synergia_net_connector_ref (gpointer instance);
void synergia_net_connector_unref (gpointer instance);
GParamSpec* synergia_param_spec_net_connector (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void synergia_value_set_net_connector (GValue* value, gpointer v_object);
void synergia_value_take_net_connector (GValue* value, gpointer v_object);
gpointer synergia_value_get_net_connector (const GValue* value);
GType synergia_net_connector_get_type (void) G_GNUC_CONST;
GType stk_widget_get_type (void) G_GNUC_CONST;
GType synergia_character_get_type (void) G_GNUC_CONST;
GType synergia_player_get_type (void) G_GNUC_CONST;
GType synergia_map_get_type (void) G_GNUC_CONST;
GType stk_container_get_type (void) G_GNUC_CONST;
GType stk_window_get_type (void) G_GNUC_CONST;
GType synergia_connect_window_get_type (void) G_GNUC_CONST;
GType synergia_status_window_get_type (void) G_GNUC_CONST;
GType stk_label_get_type (void) G_GNUC_CONST;
#define SYNERGIA_MAIN_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), SYNERGIA_TYPE_MAIN, SynergiaMainPrivate))
enum  {
	SYNERGIA_MAIN_DUMMY_PROPERTY
};
#define SYNERGIA_MAIN_SCREEN_WIDTH 640
#define SYNERGIA_MAIN_SCREEN_HEIGHT 480
#define SYNERGIA_MAIN_SCREEN_BPP 32
#define SYNERGIA_MAIN_DELAY 10
SynergiaMain* synergia_main_new (void);
SynergiaMain* synergia_main_construct (GType object_type);
static void synergia_main_init_video (SynergiaMain* self);
static void synergia_main_init_network (SynergiaMain* self);
gpointer synergia_events_ref (gpointer instance);
void synergia_events_unref (gpointer instance);
GParamSpec* synergia_param_spec_events (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void synergia_value_set_events (GValue* value, gpointer v_object);
void synergia_value_take_events (GValue* value, gpointer v_object);
gpointer synergia_value_get_events (const GValue* value);
GType synergia_events_get_type (void) G_GNUC_CONST;
void synergia_main_ErrorEvent (SynergiaMain* self, gint errcode, const gchar* errstr);
static void _synergia_main_ErrorEvent_synergia_events_error (SynergiaEvents* _sender, gint errnum, const gchar* errstr, gpointer self);
void synergia_main_CharacterEvent (SynergiaMain* self, gchar** command, int command_length1);
static void _synergia_main_CharacterEvent_synergia_events_character (SynergiaEvents* _sender, gchar** args, int args_length1, gpointer self);
void synergia_main_CharacterOutEvent (SynergiaMain* self, gchar** command, int command_length1);
static void _synergia_main_CharacterOutEvent_synergia_events_character_out (SynergiaEvents* _sender, gchar** args, int args_length1, gpointer self);
void stk_stk_init (SDL_Surface* screen);
gpointer stk_events_ref (gpointer instance);
void stk_events_unref (gpointer instance);
GParamSpec* stk_param_spec_events (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void stk_value_set_events (GValue* value, gpointer v_object);
void stk_value_take_events (GValue* value, gpointer v_object);
gpointer stk_value_get_events (const GValue* value);
GType stk_events_get_type (void) G_GNUC_CONST;
void synergia_main_quit (SynergiaMain* self);
static void _synergia_main_quit_stk_events_quit (StkEvents* _sender, gpointer self);
void stk_stk_set_font (const gchar* fontfile);
SynergiaPlayer* synergia_player_new (SynergiaNetConnector* net);
SynergiaPlayer* synergia_player_construct (GType object_type, SynergiaNetConnector* net);
SynergiaConnectWindow* synergia_connect_window_new (void);
SynergiaConnectWindow* synergia_connect_window_construct (GType object_type);
StkLabel* stk_label_new_with_text (const gchar* text);
StkLabel* stk_label_construct_with_text (GType object_type, const gchar* text);
GType stk_alignment_get_type (void) G_GNUC_CONST;
static void _synergia_main_quit_synergia_connect_window_quit (SynergiaConnectWindow* _sender, gpointer self);
void synergia_main_authenticate (SynergiaMain* self);
static void _synergia_main_authenticate_synergia_connect_window_validate (SynergiaConnectWindow* _sender, gpointer self);
void synergia_main_update_fps (SynergiaMain* self);
static void _synergia_main_update_fps_stk_events_tick (StkEvents* _sender, gpointer self);
void stk_stk_add_window (StkWindow* w);
GType stk_stack_get_type (void) G_GNUC_CONST;
void stk_container_add (StkContainer* self, StkWidget* w);
StkImage* stk_image_new_from_file (const gchar* file);
StkImage* stk_image_construct_from_file (GType object_type, const gchar* file);
GType stk_image_get_type (void) G_GNUC_CONST;
void synergia_main_run (SynergiaMain* self);
void stk_stk_main_iteration (void);
void synergia_net_connector_execute_commands (SynergiaNetConnector* self);
void synergia_main_clear (SynergiaMain* self);
void synergia_net_connector_close (SynergiaNetConnector* self);
void stk_stk_remove_window (StkWindow* w);
SynergiaStatusWindow* synergia_status_window_new (void);
SynergiaStatusWindow* synergia_status_window_construct (GType object_type);
void synergia_status_window_set_message (SynergiaStatusWindow* self, const gchar* value);
void synergia_net_connector_send (SynergiaNetConnector* self, const gchar* command, gchar** params, int params_length1);
const gchar* synergia_connect_window_get_username (SynergiaConnectWindow* self);
const gchar* synergia_connect_window_get_password (SynergiaConnectWindow* self);
SynergiaMap* synergia_map_new (SynergiaNetConnector* net, SynergiaPlayer* p, GeeList* characters);
SynergiaMap* synergia_map_construct (GType object_type, SynergiaNetConnector* net, SynergiaPlayer* p, GeeList* characters);
void stk_container_clear (StkContainer* self);
gboolean stk_container_contains (StkContainer* self, StkWidget* w);
void stk_container_remove (StkContainer* self, StkWidget* w);
SynergiaCharacter* synergia_character_new (SynergiaNetConnector* net);
SynergiaCharacter* synergia_character_construct (GType object_type, SynergiaNetConnector* net);
GType synergia_orientation_get_type (void) G_GNUC_CONST;
SynergiaNetConnector* synergia_net_connector_new (void);
SynergiaNetConnector* synergia_net_connector_construct (GType object_type);
void synergia_net_connector_set_address (SynergiaNetConnector* self, const gchar* address, gint port);
void synergia_net_connector_connect_server (SynergiaNetConnector* self);
gint synergia_main_main (gchar** args, int args_length1);
static void synergia_main_finalize (SynergiaMain* obj);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);
static gint _vala_array_length (gpointer array);


static void _synergia_main_ErrorEvent_synergia_events_error (SynergiaEvents* _sender, gint errnum, const gchar* errstr, gpointer self) {
	synergia_main_ErrorEvent (self, errnum, errstr);
}


static void _synergia_main_CharacterEvent_synergia_events_character (SynergiaEvents* _sender, gchar** args, int args_length1, gpointer self) {
	synergia_main_CharacterEvent (self, args, args_length1);
}


static void _synergia_main_CharacterOutEvent_synergia_events_character_out (SynergiaEvents* _sender, gchar** args, int args_length1, gpointer self) {
	synergia_main_CharacterOutEvent (self, args, args_length1);
}


static void _synergia_main_quit_stk_events_quit (StkEvents* _sender, gpointer self) {
	synergia_main_quit (self);
}


static void _synergia_main_quit_synergia_connect_window_quit (SynergiaConnectWindow* _sender, gpointer self) {
	synergia_main_quit (self);
}


static void _synergia_main_authenticate_synergia_connect_window_validate (SynergiaConnectWindow* _sender, gpointer self) {
	synergia_main_authenticate (self);
}


static void _synergia_main_update_fps_stk_events_tick (StkEvents* _sender, gpointer self) {
	synergia_main_update_fps (self);
}


SynergiaMain* synergia_main_construct (GType object_type) {
	SynergiaMain* self = NULL;
	SynergiaNetConnector* _tmp0_;
	SynergiaEvents* _tmp1_;
	SynergiaNetConnector* _tmp2_;
	SynergiaEvents* _tmp3_;
	SynergiaNetConnector* _tmp4_;
	SynergiaEvents* _tmp5_;
	SDL_Surface* _tmp6_;
	StkEvents* _tmp7_;
	SynergiaNetConnector* _tmp8_;
	SynergiaPlayer* _tmp9_;
	GeeArrayList* _tmp10_;
	SynergiaConnectWindow* _tmp11_;
	StkLabel* _tmp12_;
	StkLabel* _tmp13_;
	StkLabel* _tmp14_;
	SynergiaConnectWindow* _tmp15_;
	SynergiaConnectWindow* _tmp16_;
	StkEvents* _tmp17_;
	SynergiaConnectWindow* _tmp18_;
	StkStack* _tmp19_;
	StkImage* _tmp20_;
	StkImage* _tmp21_;
	StkStack* _tmp22_;
	StkLabel* _tmp23_;
	self = (SynergiaMain*) g_type_create_instance (object_type);
	synergia_main_init_video (self);
	synergia_main_init_network (self);
	_tmp0_ = self->net;
	_tmp1_ = _tmp0_->events;
	g_signal_connect (_tmp1_, "error", (GCallback) _synergia_main_ErrorEvent_synergia_events_error, self);
	_tmp2_ = self->net;
	_tmp3_ = _tmp2_->events;
	g_signal_connect (_tmp3_, "character", (GCallback) _synergia_main_CharacterEvent_synergia_events_character, self);
	_tmp4_ = self->net;
	_tmp5_ = _tmp4_->events;
	g_signal_connect (_tmp5_, "character-out", (GCallback) _synergia_main_CharacterOutEvent_synergia_events_character_out, self);
	_tmp6_ = self->screen;
	stk_stk_init (_tmp6_);
	_tmp7_ = stk_stk_events;
	g_signal_connect (_tmp7_, "quit", (GCallback) _synergia_main_quit_stk_events_quit, self);
	stk_stk_set_font ("SegoeWP.ttf");
	_tmp8_ = self->net;
	_tmp9_ = synergia_player_new (_tmp8_);
	_g_object_unref0 (self->self);
	self->self = _tmp9_;
	_tmp10_ = gee_array_list_new (SYNERGIA_TYPE_CHARACTER, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL);
	_g_object_unref0 (self->priv->characters);
	self->priv->characters = (GeeList*) _tmp10_;
	_tmp11_ = synergia_connect_window_new ();
	_g_object_unref0 (self->priv->connect_window);
	self->priv->connect_window = _tmp11_;
	_tmp12_ = stk_label_new_with_text ("0");
	_g_object_unref0 (self->priv->fpscount);
	self->priv->fpscount = _tmp12_;
	_tmp13_ = self->priv->fpscount;
	_tmp13_->halign = STK_ALIGNMENT_LEFT;
	_tmp14_ = self->priv->fpscount;
	_tmp14_->valign = STK_ALIGNMENT_TOP;
	_tmp15_ = self->priv->connect_window;
	g_signal_connect (_tmp15_, "quit", (GCallback) _synergia_main_quit_synergia_connect_window_quit, self);
	_tmp16_ = self->priv->connect_window;
	g_signal_connect (_tmp16_, "validate", (GCallback) _synergia_main_authenticate_synergia_connect_window_validate, self);
	_tmp17_ = stk_stk_events;
	g_signal_connect (_tmp17_, "tick", (GCallback) _synergia_main_update_fps_stk_events_tick, self);
	_tmp18_ = self->priv->connect_window;
	stk_stk_add_window ((StkWindow*) _tmp18_);
	_tmp19_ = stk_stk_workspace;
	_tmp20_ = stk_image_new_from_file ("gfx/menu.png");
	_tmp21_ = _tmp20_;
	stk_container_add ((StkContainer*) _tmp19_, (StkWidget*) _tmp21_);
	_g_object_unref0 (_tmp21_);
	_tmp22_ = stk_stk_workspace;
	_tmp23_ = self->priv->fpscount;
	stk_container_add ((StkContainer*) _tmp22_, (StkWidget*) _tmp23_);
	return self;
}


SynergiaMain* synergia_main_new (void) {
	return synergia_main_construct (SYNERGIA_TYPE_MAIN);
}


void synergia_main_run (SynergiaMain* self) {
	g_return_if_fail (self != NULL);
	while (TRUE) {
		gboolean _tmp0_;
		gint _tmp1_;
		SDL_Surface* _tmp2_;
		SynergiaNetConnector* _tmp3_;
		_tmp0_ = self->priv->stop;
		if (!(!_tmp0_)) {
			break;
		}
		_tmp1_ = self->priv->fps;
		self->priv->fps = _tmp1_ + 1;
		stk_stk_main_iteration ();
		_tmp2_ = self->screen;
		SDL_Flip (_tmp2_);
		_tmp3_ = self->net;
		synergia_net_connector_execute_commands (_tmp3_);
		g_usleep ((gulong) 1000);
	}
}


void synergia_main_update_fps (SynergiaMain* self) {
	StkLabel* _tmp0_;
	gint _tmp1_;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_;
	gchar* _tmp4_;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->fpscount;
	_tmp1_ = self->priv->fps;
	_tmp2_ = g_strdup_printf ("%i", _tmp1_);
	_tmp3_ = _tmp2_;
	_tmp4_ = g_strconcat (_tmp3_, " fps", NULL);
	_g_free0 (_tmp0_->text);
	_tmp0_->text = _tmp4_;
	_g_free0 (_tmp3_);
	self->priv->fps = 0;
}


void synergia_main_quit (SynergiaMain* self) {
	g_return_if_fail (self != NULL);
	self->priv->stop = TRUE;
}


void synergia_main_clear (SynergiaMain* self) {
	SynergiaNetConnector* _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->net;
	synergia_net_connector_close (_tmp0_);
	TTF_Quit ();
	SDL_Quit ();
}


void synergia_main_authenticate (SynergiaMain* self) {
	SynergiaConnectWindow* _tmp0_;
	SynergiaStatusWindow* _tmp1_;
	SynergiaStatusWindow* _tmp2_;
	SynergiaStatusWindow* _tmp3_;
	SynergiaNetConnector* _tmp4_;
	SynergiaConnectWindow* _tmp5_;
	const gchar* _tmp6_;
	const gchar* _tmp7_;
	gchar* _tmp8_;
	SynergiaConnectWindow* _tmp9_;
	const gchar* _tmp10_;
	const gchar* _tmp11_;
	gchar* _tmp12_ = NULL;
	gchar** _tmp13_ = NULL;
	gchar** _tmp14_;
	gint _tmp14__length1;
	SynergiaNetConnector* _tmp15_;
	gchar* _tmp16_;
	gchar** _tmp17_ = NULL;
	gchar** _tmp18_;
	gint _tmp18__length1;
	SynergiaNetConnector* _tmp19_;
	SynergiaPlayer* _tmp20_;
	GeeList* _tmp21_;
	SynergiaMap* _tmp22_;
	StkStack* _tmp23_;
	StkStack* _tmp24_;
	SynergiaMap* _tmp25_;
	StkStack* _tmp26_;
	SynergiaPlayer* _tmp27_;
	StkStack* _tmp28_;
	StkLabel* _tmp29_;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->connect_window;
	stk_stk_remove_window ((StkWindow*) _tmp0_);
	_tmp1_ = synergia_status_window_new ();
	_g_object_unref0 (self->priv->status);
	self->priv->status = _tmp1_;
	_tmp2_ = self->priv->status;
	synergia_status_window_set_message (_tmp2_, "Connecting...");
	_tmp3_ = self->priv->status;
	stk_stk_add_window ((StkWindow*) _tmp3_);
	_tmp4_ = self->net;
	_tmp5_ = self->priv->connect_window;
	_tmp6_ = synergia_connect_window_get_username (_tmp5_);
	_tmp7_ = _tmp6_;
	_tmp8_ = g_strdup (_tmp7_);
	_tmp9_ = self->priv->connect_window;
	_tmp10_ = synergia_connect_window_get_password (_tmp9_);
	_tmp11_ = _tmp10_;
	_tmp12_ = g_compute_checksum_for_string (G_CHECKSUM_SHA1, _tmp11_, (gsize) (-1));
	_tmp13_ = g_new0 (gchar*, 2 + 1);
	_tmp13_[0] = _tmp8_;
	_tmp13_[1] = _tmp12_;
	_tmp14_ = _tmp13_;
	_tmp14__length1 = 2;
	synergia_net_connector_send (_tmp4_, "auth", _tmp14_, 2);
	_tmp14_ = (_vala_array_free (_tmp14_, _tmp14__length1, (GDestroyNotify) g_free), NULL);
	_tmp15_ = self->net;
	_tmp16_ = g_strdup ("1");
	_tmp17_ = g_new0 (gchar*, 1 + 1);
	_tmp17_[0] = _tmp16_;
	_tmp18_ = _tmp17_;
	_tmp18__length1 = 1;
	synergia_net_connector_send (_tmp15_, "set-character", _tmp18_, 1);
	_tmp18_ = (_vala_array_free (_tmp18_, _tmp18__length1, (GDestroyNotify) g_free), NULL);
	_tmp19_ = self->net;
	_tmp20_ = self->self;
	_tmp21_ = self->priv->characters;
	_tmp22_ = synergia_map_new (_tmp19_, _tmp20_, _tmp21_);
	_g_object_unref0 (self->map);
	self->map = _tmp22_;
	_tmp23_ = stk_stk_workspace;
	stk_container_clear ((StkContainer*) _tmp23_);
	_tmp24_ = stk_stk_workspace;
	_tmp25_ = self->map;
	stk_container_add ((StkContainer*) _tmp24_, (StkWidget*) _tmp25_);
	_tmp26_ = stk_stk_workspace;
	_tmp27_ = self->self;
	stk_container_add ((StkContainer*) _tmp26_, (StkWidget*) _tmp27_);
	_tmp28_ = stk_stk_workspace;
	_tmp29_ = self->priv->fpscount;
	stk_container_add ((StkContainer*) _tmp28_, (StkWidget*) _tmp29_);
}


void synergia_main_ErrorEvent (SynergiaMain* self, gint errcode, const gchar* errstr) {
	gint _tmp0_;
	StkStack* _tmp1_;
	SynergiaStatusWindow* _tmp2_;
	gboolean _tmp3_ = FALSE;
	SynergiaStatusWindow* _tmp6_;
	SynergiaStatusWindow* _tmp7_;
	gint _tmp8_;
	gchar* _tmp9_ = NULL;
	gchar* _tmp10_;
	gchar* _tmp11_;
	gchar* _tmp12_;
	gchar* _tmp13_;
	gchar* _tmp14_;
	const gchar* _tmp15_;
	gchar* _tmp16_;
	gchar* _tmp17_;
	SynergiaStatusWindow* _tmp18_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (errstr != NULL);
	_tmp0_ = errcode;
	if (_tmp0_ == 5) {
		return;
	}
	_tmp1_ = stk_stk_workspace;
	_tmp2_ = self->priv->status;
	_tmp3_ = stk_container_contains ((StkContainer*) _tmp1_, (StkWidget*) _tmp2_);
	if (_tmp3_) {
		StkStack* _tmp4_;
		SynergiaStatusWindow* _tmp5_;
		_tmp4_ = stk_stk_workspace;
		_tmp5_ = self->priv->status;
		stk_container_remove ((StkContainer*) _tmp4_, (StkWidget*) _tmp5_);
	}
	_tmp6_ = synergia_status_window_new ();
	_g_object_unref0 (self->priv->status);
	self->priv->status = _tmp6_;
	_tmp7_ = self->priv->status;
	_tmp8_ = errcode;
	_tmp9_ = g_strdup_printf ("%i", _tmp8_);
	_tmp10_ = _tmp9_;
	_tmp11_ = g_strconcat ("Error #", _tmp10_, NULL);
	_tmp12_ = _tmp11_;
	_tmp13_ = g_strconcat (_tmp12_, ": ", NULL);
	_tmp14_ = _tmp13_;
	_tmp15_ = errstr;
	_tmp16_ = g_strconcat (_tmp14_, _tmp15_, NULL);
	_tmp17_ = _tmp16_;
	synergia_status_window_set_message (_tmp7_, _tmp17_);
	_g_free0 (_tmp17_);
	_g_free0 (_tmp14_);
	_g_free0 (_tmp12_);
	_g_free0 (_tmp10_);
	_tmp18_ = self->priv->status;
	stk_stk_add_window ((StkWindow*) _tmp18_);
}


void synergia_main_CharacterEvent (SynergiaMain* self, gchar** command, int command_length1) {
	SynergiaNetConnector* _tmp0_;
	SynergiaCharacter* _tmp1_;
	SynergiaCharacter* c;
	gchar** _tmp2_;
	gint _tmp2__length1;
	const gchar* _tmp3_;
	gint _tmp4_ = 0;
	gchar** _tmp5_;
	gint _tmp5__length1;
	const gchar* _tmp6_;
	gchar* _tmp7_;
	gchar** _tmp8_;
	gint _tmp8__length1;
	const gchar* _tmp9_;
	gint _tmp10_ = 0;
	gchar** _tmp11_;
	gint _tmp11__length1;
	const gchar* _tmp12_;
	gint _tmp13_ = 0;
	GeeList* _tmp14_;
	StkStack* _tmp15_;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->net;
	_tmp1_ = synergia_character_new (_tmp0_);
	c = _tmp1_;
	_tmp2_ = command;
	_tmp2__length1 = command_length1;
	_tmp3_ = _tmp2_[0];
	_tmp4_ = atoi (_tmp3_);
	c->id = _tmp4_;
	_tmp5_ = command;
	_tmp5__length1 = command_length1;
	_tmp6_ = _tmp5_[1];
	_tmp7_ = g_strdup (_tmp6_);
	_g_free0 (c->name);
	c->name = _tmp7_;
	_tmp8_ = command;
	_tmp8__length1 = command_length1;
	_tmp9_ = _tmp8_[2];
	_tmp10_ = atoi (_tmp9_);
	c->pos.x = (gint16) ((gshort) _tmp10_);
	_tmp11_ = command;
	_tmp11__length1 = command_length1;
	_tmp12_ = _tmp11_[3];
	_tmp13_ = atoi (_tmp12_);
	c->pos.y = (gint16) ((gshort) _tmp13_);
	_tmp14_ = self->priv->characters;
	gee_collection_add ((GeeCollection*) _tmp14_, c);
	_tmp15_ = stk_stk_workspace;
	stk_container_add ((StkContainer*) _tmp15_, (StkWidget*) c);
	_g_object_unref0 (c);
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


void synergia_main_CharacterOutEvent (SynergiaMain* self, gchar** command, int command_length1) {
	gchar** _tmp0_;
	gint _tmp0__length1;
	const gchar* _tmp1_;
	gint _tmp2_ = 0;
	gint id;
	g_return_if_fail (self != NULL);
	_tmp0_ = command;
	_tmp0__length1 = command_length1;
	_tmp1_ = _tmp0_[0];
	_tmp2_ = atoi (_tmp1_);
	id = _tmp2_;
	{
		GeeList* _tmp3_;
		GeeList* _tmp4_;
		GeeList* _c_list;
		GeeList* _tmp5_;
		gint _tmp6_;
		gint _tmp7_;
		gint _c_size;
		gint _c_index;
		_tmp3_ = self->priv->characters;
		_tmp4_ = _g_object_ref0 (_tmp3_);
		_c_list = _tmp4_;
		_tmp5_ = _c_list;
		_tmp6_ = gee_collection_get_size ((GeeCollection*) _tmp5_);
		_tmp7_ = _tmp6_;
		_c_size = _tmp7_;
		_c_index = -1;
		while (TRUE) {
			gint _tmp8_;
			gint _tmp9_;
			gint _tmp10_;
			GeeList* _tmp11_;
			gint _tmp12_;
			gpointer _tmp13_ = NULL;
			SynergiaCharacter* c;
			SynergiaCharacter* _tmp14_;
			gint _tmp15_;
			gint _tmp16_;
			_tmp8_ = _c_index;
			_c_index = _tmp8_ + 1;
			_tmp9_ = _c_index;
			_tmp10_ = _c_size;
			if (!(_tmp9_ < _tmp10_)) {
				break;
			}
			_tmp11_ = _c_list;
			_tmp12_ = _c_index;
			_tmp13_ = gee_list_get (_tmp11_, _tmp12_);
			c = (SynergiaCharacter*) _tmp13_;
			_tmp14_ = c;
			_tmp15_ = _tmp14_->id;
			_tmp16_ = id;
			if (_tmp15_ == _tmp16_) {
				StkStack* _tmp17_;
				SynergiaCharacter* _tmp18_;
				GeeList* _tmp19_;
				SynergiaCharacter* _tmp20_;
				_tmp17_ = stk_stk_workspace;
				_tmp18_ = c;
				stk_container_remove ((StkContainer*) _tmp17_, (StkWidget*) _tmp18_);
				_tmp19_ = self->priv->characters;
				_tmp20_ = c;
				gee_collection_remove ((GeeCollection*) _tmp19_, _tmp20_);
				_g_object_unref0 (c);
				break;
			}
			_g_object_unref0 (c);
		}
		_g_object_unref0 (_c_list);
	}
}


static void synergia_main_init_network (SynergiaMain* self) {
	SynergiaNetConnector* _tmp0_;
	gchar* buffer = NULL;
	gchar** addr = NULL;
	gint addr_length1 = 0;
	gint _addr_size_ = 0;
	gsize len = 0UL;
	GFile* _tmp1_ = NULL;
	GFile* fp;
	GFile* _tmp2_;
	gboolean _tmp3_ = FALSE;
	SynergiaNetConnector* _tmp21_;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = synergia_net_connector_new ();
	_synergia_net_connector_unref0 (self->net);
	self->net = _tmp0_;
	_tmp1_ = g_file_new_for_path ("address.txt");
	fp = _tmp1_;
	_tmp2_ = fp;
	_tmp3_ = g_file_query_exists (_tmp2_, NULL);
	if (_tmp3_) {
		GFile* _tmp4_;
		GFileInputStream* _tmp5_ = NULL;
		GFileInputStream* stream;
		GFileInputStream* _tmp6_;
		GDataInputStream* _tmp7_;
		GDataInputStream* dataStream;
		GDataInputStream* _tmp8_;
		gsize _tmp9_ = 0UL;
		gchar* _tmp10_ = NULL;
		gchar* _tmp11_;
		const gchar* _tmp12_;
		gchar** _tmp13_;
		gchar** _tmp14_ = NULL;
		SynergiaNetConnector* _tmp15_;
		gchar** _tmp16_;
		gint _tmp16__length1;
		const gchar* _tmp17_;
		gchar** _tmp18_;
		gint _tmp18__length1;
		const gchar* _tmp19_;
		gint _tmp20_ = 0;
		_tmp4_ = fp;
		_tmp5_ = g_file_read (_tmp4_, NULL, &_inner_error_);
		stream = _tmp5_;
		if (_inner_error_ != NULL) {
			_g_object_unref0 (fp);
			addr = (_vala_array_free (addr, addr_length1, (GDestroyNotify) g_free), NULL);
			_g_free0 (buffer);
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return;
		}
		_tmp6_ = stream;
		_tmp7_ = g_data_input_stream_new ((GInputStream*) _tmp6_);
		dataStream = _tmp7_;
		_tmp8_ = dataStream;
		_tmp10_ = g_data_input_stream_read_line (_tmp8_, &_tmp9_, NULL, &_inner_error_);
		len = _tmp9_;
		_tmp11_ = _tmp10_;
		if (_inner_error_ != NULL) {
			_g_object_unref0 (dataStream);
			_g_object_unref0 (stream);
			_g_object_unref0 (fp);
			addr = (_vala_array_free (addr, addr_length1, (GDestroyNotify) g_free), NULL);
			_g_free0 (buffer);
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return;
		}
		_g_free0 (buffer);
		buffer = _tmp11_;
		_tmp12_ = buffer;
		_tmp14_ = _tmp13_ = g_strsplit (_tmp12_, ":", 0);
		addr = (_vala_array_free (addr, addr_length1, (GDestroyNotify) g_free), NULL);
		addr = _tmp14_;
		addr_length1 = _vala_array_length (_tmp13_);
		_addr_size_ = addr_length1;
		_tmp15_ = self->net;
		_tmp16_ = addr;
		_tmp16__length1 = addr_length1;
		_tmp17_ = _tmp16_[0];
		_tmp18_ = addr;
		_tmp18__length1 = addr_length1;
		_tmp19_ = _tmp18_[1];
		_tmp20_ = atoi (_tmp19_);
		synergia_net_connector_set_address (_tmp15_, _tmp17_, _tmp20_);
		_g_object_unref0 (dataStream);
		_g_object_unref0 (stream);
	}
	_tmp21_ = self->net;
	synergia_net_connector_connect_server (_tmp21_);
	_g_object_unref0 (fp);
	addr = (_vala_array_free (addr, addr_length1, (GDestroyNotify) g_free), NULL);
	_g_free0 (buffer);
}


static void synergia_main_init_video (SynergiaMain* self) {
	guint32 video_flags;
	SDL_Surface* _tmp0_ = NULL;
	SDL_Surface* _tmp1_;
	g_return_if_fail (self != NULL);
	SDL_Init ((guint32) SDL_INIT_VIDEO);
	TTF_Init ();
	video_flags = (guint32) ((((SDL_DOUBLEBUF | SDL_ASYNCBLIT) | SDL_HWACCEL) | SDL_HWSURFACE) | SDL_SRCALPHA);
	_tmp0_ = SDL_SetVideoMode (SYNERGIA_MAIN_SCREEN_WIDTH, SYNERGIA_MAIN_SCREEN_HEIGHT, SYNERGIA_MAIN_SCREEN_BPP, video_flags);
	self->screen = _tmp0_;
	_tmp1_ = self->screen;
	if (_tmp1_ == NULL) {
		g_error ("main.vala:185: Could not set video mode.");
	}
	SDL_WM_SetCaption ("Synergia", "");
	SDL_GL_SetAttribute (SDL_GL_SWAP_CONTROL, 1);
}


gint synergia_main_main (gchar** args, int args_length1) {
	gint result = 0;
	gboolean _tmp0_ = FALSE;
	SynergiaMain* _tmp2_;
	SynergiaMain* m;
	SynergiaMain* _tmp3_;
	SynergiaMain* _tmp4_;
	_tmp0_ = g_thread_supported ();
	if (!_tmp0_) {
		FILE* _tmp1_;
		_tmp1_ = stderr;
		fprintf (_tmp1_, "Cannot run without threads.\n");
		result = 1;
		return result;
	}
	_tmp2_ = synergia_main_new ();
	m = _tmp2_;
	_tmp3_ = m;
	synergia_main_run (_tmp3_);
	_tmp4_ = m;
	synergia_main_clear (_tmp4_);
	result = 0;
	_synergia_main_unref0 (m);
	return result;
}


int main (int argc, char ** argv) {
	g_thread_init (NULL);
	g_type_init ();
	return synergia_main_main (argv, argc);
}


static void synergia_value_main_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void synergia_value_main_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		synergia_main_unref (value->data[0].v_pointer);
	}
}


static void synergia_value_main_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = synergia_main_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer synergia_value_main_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* synergia_value_main_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		SynergiaMain* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = synergia_main_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* synergia_value_main_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	SynergiaMain** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = synergia_main_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* synergia_param_spec_main (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	SynergiaParamSpecMain* spec;
	g_return_val_if_fail (g_type_is_a (object_type, SYNERGIA_TYPE_MAIN), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer synergia_value_get_main (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, SYNERGIA_TYPE_MAIN), NULL);
	return value->data[0].v_pointer;
}


void synergia_value_set_main (GValue* value, gpointer v_object) {
	SynergiaMain* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, SYNERGIA_TYPE_MAIN));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, SYNERGIA_TYPE_MAIN));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		synergia_main_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		synergia_main_unref (old);
	}
}


void synergia_value_take_main (GValue* value, gpointer v_object) {
	SynergiaMain* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, SYNERGIA_TYPE_MAIN));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, SYNERGIA_TYPE_MAIN));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		synergia_main_unref (old);
	}
}


static void synergia_main_class_init (SynergiaMainClass * klass) {
	synergia_main_parent_class = g_type_class_peek_parent (klass);
	SYNERGIA_MAIN_CLASS (klass)->finalize = synergia_main_finalize;
	g_type_class_add_private (klass, sizeof (SynergiaMainPrivate));
}


static void synergia_main_instance_init (SynergiaMain * self) {
	self->priv = SYNERGIA_MAIN_GET_PRIVATE (self);
	self->priv->stop = FALSE;
	self->priv->fps = 0;
	self->ref_count = 1;
}


static void synergia_main_finalize (SynergiaMain* obj) {
	SynergiaMain * self;
	self = SYNERGIA_MAIN (obj);
	_g_object_unref0 (self->priv->connect_window);
	_g_object_unref0 (self->priv->status);
	_g_object_unref0 (self->priv->characters);
	_g_object_unref0 (self->priv->fpscount);
	_synergia_net_connector_unref0 (self->net);
	_g_object_unref0 (self->self);
	_g_object_unref0 (self->map);
}


GType synergia_main_get_type (void) {
	static volatile gsize synergia_main_type_id__volatile = 0;
	if (g_once_init_enter (&synergia_main_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { synergia_value_main_init, synergia_value_main_free_value, synergia_value_main_copy_value, synergia_value_main_peek_pointer, "p", synergia_value_main_collect_value, "p", synergia_value_main_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (SynergiaMainClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) synergia_main_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (SynergiaMain), 0, (GInstanceInitFunc) synergia_main_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType synergia_main_type_id;
		synergia_main_type_id = g_type_register_fundamental (g_type_fundamental_next (), "SynergiaMain", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&synergia_main_type_id__volatile, synergia_main_type_id);
	}
	return synergia_main_type_id__volatile;
}


gpointer synergia_main_ref (gpointer instance) {
	SynergiaMain* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void synergia_main_unref (gpointer instance) {
	SynergiaMain* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		SYNERGIA_MAIN_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}


static gint _vala_array_length (gpointer array) {
	int length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}



