/* net.c generated by valac 0.16.0, the Vala compiler
 * generated from net.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gio/gio.h>
#include <stdio.h>
#include <gobject/gvaluecollector.h>


#define SYNERGIA_TYPE_NET_CONNECTOR (synergia_net_connector_get_type ())
#define SYNERGIA_NET_CONNECTOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYNERGIA_TYPE_NET_CONNECTOR, SynergiaNetConnector))
#define SYNERGIA_NET_CONNECTOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYNERGIA_TYPE_NET_CONNECTOR, SynergiaNetConnectorClass))
#define SYNERGIA_IS_NET_CONNECTOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYNERGIA_TYPE_NET_CONNECTOR))
#define SYNERGIA_IS_NET_CONNECTOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYNERGIA_TYPE_NET_CONNECTOR))
#define SYNERGIA_NET_CONNECTOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYNERGIA_TYPE_NET_CONNECTOR, SynergiaNetConnectorClass))

typedef struct _SynergiaNetConnector SynergiaNetConnector;
typedef struct _SynergiaNetConnectorClass SynergiaNetConnectorClass;
typedef struct _SynergiaNetConnectorPrivate SynergiaNetConnectorPrivate;

#define SYNERGIA_TYPE_EVENTS (synergia_events_get_type ())
#define SYNERGIA_EVENTS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYNERGIA_TYPE_EVENTS, SynergiaEvents))
#define SYNERGIA_EVENTS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYNERGIA_TYPE_EVENTS, SynergiaEventsClass))
#define SYNERGIA_IS_EVENTS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYNERGIA_TYPE_EVENTS))
#define SYNERGIA_IS_EVENTS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYNERGIA_TYPE_EVENTS))
#define SYNERGIA_EVENTS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYNERGIA_TYPE_EVENTS, SynergiaEventsClass))

typedef struct _SynergiaEvents SynergiaEvents;
typedef struct _SynergiaEventsClass SynergiaEventsClass;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _synergia_events_unref0(var) ((var == NULL) ? NULL : (var = (synergia_events_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _g_regex_unref0(var) ((var == NULL) ? NULL : (var = (g_regex_unref (var), NULL)))
typedef struct _SynergiaParamSpecNetConnector SynergiaParamSpecNetConnector;

struct _SynergiaNetConnector {
	GTypeInstance parent_instance;
	volatile int ref_count;
	SynergiaNetConnectorPrivate * priv;
	gchar* address;
	gint port;
	GSocket* socket;
	SynergiaEvents* events;
};

struct _SynergiaNetConnectorClass {
	GTypeClass parent_class;
	void (*finalize) (SynergiaNetConnector *self);
};

struct _SynergiaNetConnectorPrivate {
	GThread* readThread;
	gboolean readLock;
	gchar* commands;
};

struct _SynergiaParamSpecNetConnector {
	GParamSpec parent_instance;
};


static gpointer synergia_net_connector_parent_class = NULL;

gpointer synergia_net_connector_ref (gpointer instance);
void synergia_net_connector_unref (gpointer instance);
GParamSpec* synergia_param_spec_net_connector (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void synergia_value_set_net_connector (GValue* value, gpointer v_object);
void synergia_value_take_net_connector (GValue* value, gpointer v_object);
gpointer synergia_value_get_net_connector (const GValue* value);
GType synergia_net_connector_get_type (void) G_GNUC_CONST;
gpointer synergia_events_ref (gpointer instance);
void synergia_events_unref (gpointer instance);
GParamSpec* synergia_param_spec_events (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void synergia_value_set_events (GValue* value, gpointer v_object);
void synergia_value_take_events (GValue* value, gpointer v_object);
gpointer synergia_value_get_events (const GValue* value);
GType synergia_events_get_type (void) G_GNUC_CONST;
#define SYNERGIA_NET_CONNECTOR_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), SYNERGIA_TYPE_NET_CONNECTOR, SynergiaNetConnectorPrivate))
enum  {
	SYNERGIA_NET_CONNECTOR_DUMMY_PROPERTY
};
SynergiaNetConnector* synergia_net_connector_new (void);
SynergiaNetConnector* synergia_net_connector_construct (GType object_type);
SynergiaEvents* synergia_events_new (void);
SynergiaEvents* synergia_events_construct (GType object_type);
void synergia_net_connector_pingEvent (SynergiaNetConnector* self, gchar** args, int args_length1);
static void _synergia_net_connector_pingEvent_synergia_events_ping (SynergiaEvents* _sender, gchar** args, int args_length1, gpointer self);
void synergia_net_connector_connectEvent (SynergiaNetConnector* self, gchar** args, int args_length1);
static void _synergia_net_connector_connectEvent_synergia_events_connect (SynergiaEvents* _sender, gchar** args, int args_length1, gpointer self);
void synergia_net_connector_set_address (SynergiaNetConnector* self, const gchar* address, gint port);
void synergia_net_connector_connect_server (SynergiaNetConnector* self);
void* synergia_net_connector_read (SynergiaNetConnector* self);
static gpointer _synergia_net_connector_read_gthread_func (gpointer self);
void synergia_net_connector_send_direct (SynergiaNetConnector* self, const gchar* command);
void synergia_net_connector_send (SynergiaNetConnector* self, const gchar* command, gchar** params, int params_length1);
void synergia_net_connector_close (SynergiaNetConnector* self);
void synergia_net_connector_execute_commands (SynergiaNetConnector* self);
void synergia_events_raise (SynergiaEvents* self, const gchar* eventName, gchar** command, int command_length1);
static void synergia_net_connector_finalize (SynergiaNetConnector* obj);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);
static gint _vala_array_length (gpointer array);


static void _synergia_net_connector_pingEvent_synergia_events_ping (SynergiaEvents* _sender, gchar** args, int args_length1, gpointer self) {
	synergia_net_connector_pingEvent (self, args, args_length1);
}


static void _synergia_net_connector_connectEvent_synergia_events_connect (SynergiaEvents* _sender, gchar** args, int args_length1, gpointer self) {
	synergia_net_connector_connectEvent (self, args, args_length1);
}


SynergiaNetConnector* synergia_net_connector_construct (GType object_type) {
	SynergiaNetConnector* self = NULL;
	SynergiaEvents* _tmp0_;
	SynergiaEvents* _tmp1_;
	SynergiaEvents* _tmp2_;
	self = (SynergiaNetConnector*) g_type_create_instance (object_type);
	_tmp0_ = synergia_events_new ();
	_synergia_events_unref0 (self->events);
	self->events = _tmp0_;
	_tmp1_ = self->events;
	g_signal_connect (_tmp1_, "ping", (GCallback) _synergia_net_connector_pingEvent_synergia_events_ping, self);
	_tmp2_ = self->events;
	g_signal_connect (_tmp2_, "connect", (GCallback) _synergia_net_connector_connectEvent_synergia_events_connect, self);
	return self;
}


SynergiaNetConnector* synergia_net_connector_new (void) {
	return synergia_net_connector_construct (SYNERGIA_TYPE_NET_CONNECTOR);
}


void synergia_net_connector_set_address (SynergiaNetConnector* self, const gchar* address, gint port) {
	const gchar* _tmp0_;
	gchar* _tmp1_;
	gint _tmp2_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (address != NULL);
	_tmp0_ = address;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->address);
	self->address = _tmp1_;
	_tmp2_ = port;
	self->port = _tmp2_;
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static gpointer _synergia_net_connector_read_gthread_func (gpointer self) {
	gpointer result;
	result = synergia_net_connector_read (self);
	return result;
}


void synergia_net_connector_connect_server (SynergiaNetConnector* self) {
	gboolean _tmp0_ = FALSE;
	const gchar* _tmp1_;
	gboolean _tmp3_;
	GSocketClient* _tmp4_;
	GSocketClient* client;
	GSocketConnection* connection = NULL;
	GSocket* _tmp9_ = NULL;
	GSocket* _tmp10_;
	GSocket* _tmp11_;
	GThread* _tmp12_ = NULL;
	GThread* _tmp13_;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp1_ = self->address;
	if (_tmp1_ == NULL) {
		_tmp0_ = TRUE;
	} else {
		gint _tmp2_;
		_tmp2_ = self->port;
		_tmp0_ = _tmp2_ == 0;
	}
	_tmp3_ = _tmp0_;
	if (_tmp3_) {
		g_error ("net.vala:31: No address or port given.");
	}
	_tmp4_ = g_socket_client_new ();
	client = _tmp4_;
	{
		const gchar* _tmp5_;
		gint _tmp6_;
		GSocketConnection* _tmp7_ = NULL;
		GSocketConnection* _tmp8_;
		_tmp5_ = self->address;
		_tmp6_ = self->port;
		_tmp7_ = g_socket_client_connect_to_host (client, _tmp5_, (guint16) _tmp6_, NULL, &_inner_error_);
		_tmp8_ = _tmp7_;
		if (_inner_error_ != NULL) {
			goto __catch0_g_error;
		}
		_g_object_unref0 (connection);
		connection = _tmp8_;
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* e = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		g_error ("net.vala:41: Can't connect to server.");
		_g_error_free0 (e);
	}
	__finally0:
	if (_inner_error_ != NULL) {
		_g_object_unref0 (connection);
		_g_object_unref0 (client);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp9_ = g_socket_connection_get_socket (connection);
	_tmp10_ = _g_object_ref0 (_tmp9_);
	_g_object_unref0 (self->socket);
	self->socket = _tmp10_;
	_tmp11_ = self->socket;
	g_socket_set_blocking (_tmp11_, FALSE);
	_tmp12_ = g_thread_create (_synergia_net_connector_read_gthread_func, self, TRUE, &_inner_error_);
	_tmp13_ = _tmp12_;
	if (_inner_error_ != NULL) {
		_g_object_unref0 (connection);
		_g_object_unref0 (client);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	self->priv->readThread = _tmp13_;
	_g_object_unref0 (connection);
	_g_object_unref0 (client);
}


static gchar* string_replace (const gchar* self, const gchar* old, const gchar* replacement) {
	gchar* result = NULL;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (old != NULL, NULL);
	g_return_val_if_fail (replacement != NULL, NULL);
	{
		const gchar* _tmp0_;
		gchar* _tmp1_ = NULL;
		gchar* _tmp2_;
		GRegex* _tmp3_;
		GRegex* _tmp4_;
		GRegex* regex;
		GRegex* _tmp5_;
		const gchar* _tmp6_;
		gchar* _tmp7_ = NULL;
		gchar* _tmp8_;
		_tmp0_ = old;
		_tmp1_ = g_regex_escape_string (_tmp0_, -1);
		_tmp2_ = _tmp1_;
		_tmp3_ = g_regex_new (_tmp2_, 0, 0, &_inner_error_);
		_tmp4_ = _tmp3_;
		_g_free0 (_tmp2_);
		regex = _tmp4_;
		if (_inner_error_ != NULL) {
			if (_inner_error_->domain == G_REGEX_ERROR) {
				goto __catch1_g_regex_error;
			}
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
		_tmp5_ = regex;
		_tmp6_ = replacement;
		_tmp7_ = g_regex_replace_literal (_tmp5_, self, (gssize) (-1), 0, _tmp6_, 0, &_inner_error_);
		_tmp8_ = _tmp7_;
		if (_inner_error_ != NULL) {
			_g_regex_unref0 (regex);
			if (_inner_error_->domain == G_REGEX_ERROR) {
				goto __catch1_g_regex_error;
			}
			_g_regex_unref0 (regex);
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
		result = _tmp8_;
		_g_regex_unref0 (regex);
		return result;
	}
	goto __finally1;
	__catch1_g_regex_error:
	{
		GError* e = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		g_assert_not_reached ();
		_g_error_free0 (e);
	}
	__finally1:
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
}


static guint8* string_get_data (const gchar* self, int* result_length1) {
	guint8* result;
	guint8* res;
	gint res_length1;
	gint _res_size_;
	gint _tmp0_;
	gint _tmp1_;
	gint _tmp2_;
	guint8* _tmp3_;
	gint _tmp3__length1;
	guint8* _tmp4_;
	gint _tmp4__length1;
	g_return_val_if_fail (self != NULL, NULL);
	res = (guint8*) self;
	res_length1 = -1;
	_res_size_ = res_length1;
	_tmp0_ = strlen (self);
	_tmp1_ = _tmp0_;
	res_length1 = (gint) _tmp1_;
	_tmp2_ = res_length1;
	_tmp3_ = res;
	_tmp3__length1 = res_length1;
	_tmp4_ = _tmp3_;
	_tmp4__length1 = _tmp3__length1;
	if (result_length1) {
		*result_length1 = _tmp4__length1;
	}
	result = _tmp4_;
	return result;
}


void synergia_net_connector_send_direct (SynergiaNetConnector* self, const gchar* command) {
	GSocket* _tmp0_;
	gboolean _tmp1_ = FALSE;
	const gchar* _tmp2_;
	gchar* _tmp3_;
	gchar* query;
	FILE* _tmp4_;
	const gchar* _tmp5_;
	gchar* _tmp6_ = NULL;
	gchar* _tmp7_;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (command != NULL);
	_tmp0_ = self->socket;
	_tmp1_ = g_socket_is_connected (_tmp0_);
	if (!_tmp1_) {
		return;
	}
	_tmp2_ = command;
	_tmp3_ = g_strconcat (_tmp2_, "\n", NULL);
	query = _tmp3_;
	_tmp4_ = stdout;
	_tmp5_ = query;
	_tmp6_ = string_replace (_tmp5_, "\x7F", ", ");
	_tmp7_ = _tmp6_;
	fprintf (_tmp4_, "--> %s", _tmp7_);
	_g_free0 (_tmp7_);
	{
		GSocket* _tmp8_;
		const gchar* _tmp9_;
		guint8* _tmp10_;
		gint _tmp10__length1;
		guint8* _tmp11_;
		gint _tmp11__length1;
		_tmp8_ = self->socket;
		_tmp9_ = query;
		_tmp10_ = string_get_data (_tmp9_, &_tmp10__length1);
		_tmp11_ = _tmp10_;
		_tmp11__length1 = _tmp10__length1;
		g_socket_send (_tmp8_, _tmp11_, (gsize) _tmp11__length1, NULL, &_inner_error_);
		if (_inner_error_ != NULL) {
			goto __catch2_g_error;
		}
	}
	goto __finally2;
	__catch2_g_error:
	{
		GError* e = NULL;
		FILE* _tmp12_;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp12_ = stdout;
		fprintf (_tmp12_, "Can't send data.\n");
		_g_error_free0 (e);
	}
	__finally2:
	if (_inner_error_ != NULL) {
		_g_free0 (query);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_g_free0 (query);
}


void synergia_net_connector_send (SynergiaNetConnector* self, const gchar* command, gchar** params, int params_length1) {
	const gchar* _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_;
	gchar** _tmp3_;
	gint _tmp3__length1;
	gchar* _tmp4_ = NULL;
	gchar* _tmp5_;
	gchar* _tmp6_;
	gchar* _tmp7_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (command != NULL);
	_tmp0_ = command;
	_tmp1_ = g_strconcat (_tmp0_, ":", NULL);
	_tmp2_ = _tmp1_;
	_tmp3_ = params;
	_tmp3__length1 = params_length1;
	_tmp4_ = g_strjoinv ("\x7F", _tmp3_);
	_tmp5_ = _tmp4_;
	_tmp6_ = g_strconcat (_tmp2_, _tmp5_, NULL);
	_tmp7_ = _tmp6_;
	synergia_net_connector_send_direct (self, _tmp7_);
	_g_free0 (_tmp7_);
	_g_free0 (_tmp5_);
	_g_free0 (_tmp2_);
}


void synergia_net_connector_close (SynergiaNetConnector* self) {
	GSocket* _tmp0_;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	synergia_net_connector_send_direct (self, "quit");
	_tmp0_ = self->socket;
	g_socket_close (_tmp0_, &_inner_error_);
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
}


void* synergia_net_connector_read (SynergiaNetConnector* self) {
	void* result = NULL;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	while (TRUE) {
		gchar* _tmp0_;
		gchar* reply;
		guint8* buffer = NULL;
		gint buffer_length1 = 0;
		gint _buffer_size_ = 0;
		gssize len;
		const gchar* _tmp15_;
		gint _tmp16_;
		gint _tmp17_;
		_tmp0_ = g_strdup ("");
		reply = _tmp0_;
		len = (gssize) 0;
		{
			gboolean _tmp1_;
			_tmp1_ = TRUE;
			while (TRUE) {
				gboolean _tmp2_;
				GSocket* _tmp4_;
				gboolean _tmp5_ = FALSE;
				gboolean _tmp6_;
				_tmp2_ = _tmp1_;
				if (!_tmp2_) {
					gssize _tmp3_;
					_tmp3_ = len;
					if (!(_tmp3_ > ((gssize) 0))) {
						break;
					}
				}
				_tmp1_ = FALSE;
				_tmp4_ = self->socket;
				_tmp5_ = g_socket_is_connected (_tmp4_);
				if (!_tmp5_) {
					g_thread_exit (NULL);
				}
				_tmp6_ = self->priv->readLock;
				if (_tmp6_ == FALSE) {
					guint8* _tmp7_ = NULL;
					const gchar* _tmp12_;
					guint8* _tmp13_;
					gint _tmp13__length1;
					gchar* _tmp14_;
					_tmp7_ = g_new0 (guint8, 1024);
					buffer = (g_free (buffer), NULL);
					buffer = _tmp7_;
					buffer_length1 = 1024;
					_buffer_size_ = buffer_length1;
					{
						GSocket* _tmp8_;
						guint8* _tmp9_;
						gint _tmp9__length1;
						gssize _tmp10_ = 0L;
						gssize _tmp11_;
						_tmp8_ = self->socket;
						_tmp9_ = buffer;
						_tmp9__length1 = buffer_length1;
						_tmp10_ = g_socket_receive (_tmp8_, (gchar*) _tmp9_, (gsize) _tmp9__length1, NULL, &_inner_error_);
						_tmp11_ = _tmp10_;
						if (_inner_error_ != NULL) {
							goto __catch3_g_error;
						}
						len = _tmp11_;
					}
					goto __finally3;
					__catch3_g_error:
					{
						GError* e = NULL;
						e = _inner_error_;
						_inner_error_ = NULL;
						_g_error_free0 (e);
						break;
					}
					__finally3:
					if (_inner_error_ != NULL) {
						buffer = (g_free (buffer), NULL);
						_g_free0 (reply);
						g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
						g_clear_error (&_inner_error_);
						return NULL;
					}
					_tmp12_ = self->priv->commands;
					_tmp13_ = buffer;
					_tmp13__length1 = buffer_length1;
					_tmp14_ = g_strconcat (_tmp12_, (const gchar*) _tmp13_, NULL);
					_g_free0 (self->priv->commands);
					self->priv->commands = _tmp14_;
				}
				g_usleep ((gulong) 5000);
			}
		}
		_tmp15_ = reply;
		_tmp16_ = strlen (_tmp15_);
		_tmp17_ = _tmp16_;
		if (_tmp17_ == 0) {
			buffer = (g_free (buffer), NULL);
			_g_free0 (reply);
			continue;
		}
		buffer = (g_free (buffer), NULL);
		_g_free0 (reply);
	}
	return result;
}


void synergia_net_connector_execute_commands (SynergiaNetConnector* self) {
	const gchar* _tmp0_;
	gchar** _tmp1_;
	gchar** _tmp2_ = NULL;
	gchar** commandList;
	gint commandList_length1;
	gint _commandList_size_;
	gchar* _tmp3_;
	gint i;
	gchar** _tmp4_;
	gint _tmp4__length1;
	g_return_if_fail (self != NULL);
	self->priv->readLock = TRUE;
	_tmp0_ = self->priv->commands;
	_tmp2_ = _tmp1_ = g_strsplit (_tmp0_, "\n", 0);
	commandList = _tmp2_;
	commandList_length1 = _vala_array_length (_tmp1_);
	_commandList_size_ = commandList_length1;
	_tmp3_ = g_strdup ("");
	_g_free0 (self->priv->commands);
	self->priv->commands = _tmp3_;
	i = 0;
	_tmp4_ = commandList;
	_tmp4__length1 = commandList_length1;
	{
		gchar** cmd_collection = NULL;
		gint cmd_collection_length1 = 0;
		gint _cmd_collection_size_ = 0;
		gint cmd_it = 0;
		cmd_collection = _tmp4_;
		cmd_collection_length1 = _tmp4__length1;
		for (cmd_it = 0; cmd_it < _tmp4__length1; cmd_it = cmd_it + 1) {
			gchar* _tmp5_;
			gchar* cmd = NULL;
			_tmp5_ = g_strdup (cmd_collection[cmd_it]);
			cmd = _tmp5_;
			{
				gint _tmp6_;
				gboolean _tmp7_ = FALSE;
				const gchar* _tmp8_;
				gint _tmp9_;
				gint _tmp10_;
				gboolean _tmp13_;
				_tmp6_ = i;
				i = _tmp6_ + 1;
				_tmp8_ = cmd;
				_tmp9_ = strlen (_tmp8_);
				_tmp10_ = _tmp9_;
				if (_tmp10_ > 0) {
					gint _tmp11_;
					gchar** _tmp12_;
					gint _tmp12__length1;
					_tmp11_ = i;
					_tmp12_ = commandList;
					_tmp12__length1 = commandList_length1;
					_tmp7_ = _tmp11_ != _tmp12__length1;
				} else {
					_tmp7_ = FALSE;
				}
				_tmp13_ = _tmp7_;
				if (_tmp13_) {
					FILE* _tmp14_;
					const gchar* _tmp15_;
					gchar* _tmp16_ = NULL;
					gchar* _tmp17_;
					const gchar* _tmp18_;
					gchar** _tmp19_;
					gchar** _tmp20_ = NULL;
					gchar** command;
					gint command_length1;
					gint _command_size_;
					SynergiaEvents* _tmp21_;
					gchar** _tmp22_;
					gint _tmp22__length1;
					const gchar* _tmp23_;
					gchar** _tmp24_;
					gint _tmp24__length1;
					const gchar* _tmp25_;
					gchar** _tmp26_;
					gchar** _tmp27_ = NULL;
					gchar** _tmp28_;
					gint _tmp28__length1;
					_tmp14_ = stdout;
					_tmp15_ = cmd;
					_tmp16_ = string_replace (_tmp15_, "\x7F", ", ");
					_tmp17_ = _tmp16_;
					fprintf (_tmp14_, "<-- %s\n", _tmp17_);
					_g_free0 (_tmp17_);
					_tmp18_ = cmd;
					_tmp20_ = _tmp19_ = g_strsplit (_tmp18_, ":", 2);
					command = _tmp20_;
					command_length1 = _vala_array_length (_tmp19_);
					_command_size_ = command_length1;
					_tmp21_ = self->events;
					_tmp22_ = command;
					_tmp22__length1 = command_length1;
					_tmp23_ = _tmp22_[0];
					_tmp24_ = command;
					_tmp24__length1 = command_length1;
					_tmp25_ = _tmp24_[1];
					_tmp27_ = _tmp26_ = g_strsplit (_tmp25_, "\x7F", 0);
					_tmp28_ = _tmp27_;
					_tmp28__length1 = _vala_array_length (_tmp26_);
					synergia_events_raise (_tmp21_, _tmp23_, _tmp28_, _vala_array_length (_tmp26_));
					_tmp28_ = (_vala_array_free (_tmp28_, _tmp28__length1, (GDestroyNotify) g_free), NULL);
					command = (_vala_array_free (command, command_length1, (GDestroyNotify) g_free), NULL);
				} else {
					gboolean _tmp29_ = FALSE;
					gint _tmp30_;
					gchar** _tmp31_;
					gint _tmp31__length1;
					gboolean _tmp35_;
					_tmp30_ = i;
					_tmp31_ = commandList;
					_tmp31__length1 = commandList_length1;
					if (_tmp30_ == _tmp31__length1) {
						const gchar* _tmp32_;
						gint _tmp33_;
						gint _tmp34_;
						_tmp32_ = cmd;
						_tmp33_ = strlen (_tmp32_);
						_tmp34_ = _tmp33_;
						_tmp29_ = _tmp34_ > 0;
					} else {
						_tmp29_ = FALSE;
					}
					_tmp35_ = _tmp29_;
					if (_tmp35_) {
						const gchar* _tmp36_;
						const gchar* _tmp37_;
						gchar* _tmp38_;
						_tmp36_ = self->priv->commands;
						_tmp37_ = cmd;
						_tmp38_ = g_strconcat (_tmp36_, _tmp37_, NULL);
						_g_free0 (self->priv->commands);
						self->priv->commands = _tmp38_;
					}
				}
				_g_free0 (cmd);
			}
		}
	}
	self->priv->readLock = FALSE;
	commandList = (_vala_array_free (commandList, commandList_length1, (GDestroyNotify) g_free), NULL);
}


void synergia_net_connector_pingEvent (SynergiaNetConnector* self, gchar** args, int args_length1) {
	gchar** _tmp0_;
	gint _tmp0__length1;
	g_return_if_fail (self != NULL);
	_tmp0_ = args;
	_tmp0__length1 = args_length1;
	synergia_net_connector_send (self, "pong", _tmp0_, _tmp0__length1);
}


void synergia_net_connector_connectEvent (SynergiaNetConnector* self, gchar** args, int args_length1) {
	gchar** _tmp0_;
	gint _tmp0__length1;
	const gchar* _tmp1_;
	gchar** _tmp2_;
	gint _tmp2__length1;
	const gchar* _tmp3_;
	gint _tmp4_ = 0;
	gchar** _tmp5_;
	gint _tmp5__length1;
	const gchar* _tmp6_;
	gchar* _tmp7_;
	gchar** _tmp8_ = NULL;
	gchar** _tmp9_;
	gint _tmp9__length1;
	g_return_if_fail (self != NULL);
	synergia_net_connector_close (self);
	_tmp0_ = args;
	_tmp0__length1 = args_length1;
	_tmp1_ = _tmp0_[1];
	_tmp2_ = args;
	_tmp2__length1 = args_length1;
	_tmp3_ = _tmp2_[2];
	_tmp4_ = atoi (_tmp3_);
	synergia_net_connector_set_address (self, _tmp1_, _tmp4_);
	synergia_net_connector_connect_server (self);
	_tmp5_ = args;
	_tmp5__length1 = args_length1;
	_tmp6_ = _tmp5_[0];
	_tmp7_ = g_strdup (_tmp6_);
	_tmp8_ = g_new0 (gchar*, 1 + 1);
	_tmp8_[0] = _tmp7_;
	_tmp9_ = _tmp8_;
	_tmp9__length1 = 1;
	synergia_net_connector_send (self, "auth", _tmp9_, 1);
	_tmp9_ = (_vala_array_free (_tmp9_, _tmp9__length1, (GDestroyNotify) g_free), NULL);
}


static void synergia_value_net_connector_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void synergia_value_net_connector_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		synergia_net_connector_unref (value->data[0].v_pointer);
	}
}


static void synergia_value_net_connector_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = synergia_net_connector_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer synergia_value_net_connector_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* synergia_value_net_connector_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		SynergiaNetConnector* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = synergia_net_connector_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* synergia_value_net_connector_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	SynergiaNetConnector** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = synergia_net_connector_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* synergia_param_spec_net_connector (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	SynergiaParamSpecNetConnector* spec;
	g_return_val_if_fail (g_type_is_a (object_type, SYNERGIA_TYPE_NET_CONNECTOR), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer synergia_value_get_net_connector (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, SYNERGIA_TYPE_NET_CONNECTOR), NULL);
	return value->data[0].v_pointer;
}


void synergia_value_set_net_connector (GValue* value, gpointer v_object) {
	SynergiaNetConnector* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, SYNERGIA_TYPE_NET_CONNECTOR));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, SYNERGIA_TYPE_NET_CONNECTOR));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		synergia_net_connector_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		synergia_net_connector_unref (old);
	}
}


void synergia_value_take_net_connector (GValue* value, gpointer v_object) {
	SynergiaNetConnector* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, SYNERGIA_TYPE_NET_CONNECTOR));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, SYNERGIA_TYPE_NET_CONNECTOR));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		synergia_net_connector_unref (old);
	}
}


static void synergia_net_connector_class_init (SynergiaNetConnectorClass * klass) {
	synergia_net_connector_parent_class = g_type_class_peek_parent (klass);
	SYNERGIA_NET_CONNECTOR_CLASS (klass)->finalize = synergia_net_connector_finalize;
	g_type_class_add_private (klass, sizeof (SynergiaNetConnectorPrivate));
}


static void synergia_net_connector_instance_init (SynergiaNetConnector * self) {
	self->priv = SYNERGIA_NET_CONNECTOR_GET_PRIVATE (self);
	self->priv->readLock = FALSE;
	self->ref_count = 1;
}


static void synergia_net_connector_finalize (SynergiaNetConnector* obj) {
	SynergiaNetConnector * self;
	self = SYNERGIA_NET_CONNECTOR (obj);
	_g_free0 (self->address);
	_g_object_unref0 (self->socket);
	_g_free0 (self->priv->commands);
	_synergia_events_unref0 (self->events);
}


GType synergia_net_connector_get_type (void) {
	static volatile gsize synergia_net_connector_type_id__volatile = 0;
	if (g_once_init_enter (&synergia_net_connector_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { synergia_value_net_connector_init, synergia_value_net_connector_free_value, synergia_value_net_connector_copy_value, synergia_value_net_connector_peek_pointer, "p", synergia_value_net_connector_collect_value, "p", synergia_value_net_connector_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (SynergiaNetConnectorClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) synergia_net_connector_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (SynergiaNetConnector), 0, (GInstanceInitFunc) synergia_net_connector_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType synergia_net_connector_type_id;
		synergia_net_connector_type_id = g_type_register_fundamental (g_type_fundamental_next (), "SynergiaNetConnector", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&synergia_net_connector_type_id__volatile, synergia_net_connector_type_id);
	}
	return synergia_net_connector_type_id__volatile;
}


gpointer synergia_net_connector_ref (gpointer instance) {
	SynergiaNetConnector* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void synergia_net_connector_unref (gpointer instance) {
	SynergiaNetConnector* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		SYNERGIA_NET_CONNECTOR_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}


static gint _vala_array_length (gpointer array) {
	int length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}



