/* player.c generated by valac 0.16.0, the Vala compiler
 * generated from player.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <SDL.h>
#include <stdlib.h>
#include <string.h>
#include <gio/gio.h>
#include <SDL_keysym.h>


#define STK_TYPE_WIDGET (stk_widget_get_type ())
#define STK_WIDGET(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), STK_TYPE_WIDGET, StkWidget))
#define STK_WIDGET_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), STK_TYPE_WIDGET, StkWidgetClass))
#define STK_IS_WIDGET(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), STK_TYPE_WIDGET))
#define STK_IS_WIDGET_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), STK_TYPE_WIDGET))
#define STK_WIDGET_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), STK_TYPE_WIDGET, StkWidgetClass))

typedef struct _StkWidget StkWidget;
typedef struct _StkWidgetClass StkWidgetClass;
typedef struct _StkWidgetPrivate StkWidgetPrivate;

#define SYNERGIA_TYPE_CHARACTER (synergia_character_get_type ())
#define SYNERGIA_CHARACTER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYNERGIA_TYPE_CHARACTER, SynergiaCharacter))
#define SYNERGIA_CHARACTER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYNERGIA_TYPE_CHARACTER, SynergiaCharacterClass))
#define SYNERGIA_IS_CHARACTER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYNERGIA_TYPE_CHARACTER))
#define SYNERGIA_IS_CHARACTER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYNERGIA_TYPE_CHARACTER))
#define SYNERGIA_CHARACTER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYNERGIA_TYPE_CHARACTER, SynergiaCharacterClass))

typedef struct _SynergiaCharacter SynergiaCharacter;
typedef struct _SynergiaCharacterClass SynergiaCharacterClass;
typedef struct _SynergiaCharacterPrivate SynergiaCharacterPrivate;

#define SYNERGIA_TYPE_ORIENTATION (synergia_orientation_get_type ())

#define SYNERGIA_TYPE_PLAYER (synergia_player_get_type ())
#define SYNERGIA_PLAYER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYNERGIA_TYPE_PLAYER, SynergiaPlayer))
#define SYNERGIA_PLAYER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYNERGIA_TYPE_PLAYER, SynergiaPlayerClass))
#define SYNERGIA_IS_PLAYER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYNERGIA_TYPE_PLAYER))
#define SYNERGIA_IS_PLAYER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYNERGIA_TYPE_PLAYER))
#define SYNERGIA_PLAYER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYNERGIA_TYPE_PLAYER, SynergiaPlayerClass))

typedef struct _SynergiaPlayer SynergiaPlayer;
typedef struct _SynergiaPlayerClass SynergiaPlayerClass;
typedef struct _SynergiaPlayerPrivate SynergiaPlayerPrivate;

#define SYNERGIA_TYPE_NET_CONNECTOR (synergia_net_connector_get_type ())
#define SYNERGIA_NET_CONNECTOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYNERGIA_TYPE_NET_CONNECTOR, SynergiaNetConnector))
#define SYNERGIA_NET_CONNECTOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYNERGIA_TYPE_NET_CONNECTOR, SynergiaNetConnectorClass))
#define SYNERGIA_IS_NET_CONNECTOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYNERGIA_TYPE_NET_CONNECTOR))
#define SYNERGIA_IS_NET_CONNECTOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYNERGIA_TYPE_NET_CONNECTOR))
#define SYNERGIA_NET_CONNECTOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYNERGIA_TYPE_NET_CONNECTOR, SynergiaNetConnectorClass))

typedef struct _SynergiaNetConnector SynergiaNetConnector;
typedef struct _SynergiaNetConnectorClass SynergiaNetConnectorClass;
#define _synergia_net_connector_unref0(var) ((var == NULL) ? NULL : (var = (synergia_net_connector_unref (var), NULL)))
typedef struct _SynergiaNetConnectorPrivate SynergiaNetConnectorPrivate;

#define SYNERGIA_TYPE_EVENTS (synergia_events_get_type ())
#define SYNERGIA_EVENTS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYNERGIA_TYPE_EVENTS, SynergiaEvents))
#define SYNERGIA_EVENTS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYNERGIA_TYPE_EVENTS, SynergiaEventsClass))
#define SYNERGIA_IS_EVENTS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYNERGIA_TYPE_EVENTS))
#define SYNERGIA_IS_EVENTS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYNERGIA_TYPE_EVENTS))
#define SYNERGIA_EVENTS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYNERGIA_TYPE_EVENTS, SynergiaEventsClass))

typedef struct _SynergiaEvents SynergiaEvents;
typedef struct _SynergiaEventsClass SynergiaEventsClass;

#define STK_TYPE_EVENTS (stk_events_get_type ())
#define STK_EVENTS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), STK_TYPE_EVENTS, StkEvents))
#define STK_EVENTS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), STK_TYPE_EVENTS, StkEventsClass))
#define STK_IS_EVENTS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), STK_TYPE_EVENTS))
#define STK_IS_EVENTS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), STK_TYPE_EVENTS))
#define STK_EVENTS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), STK_TYPE_EVENTS, StkEventsClass))

typedef struct _StkEvents StkEvents;
typedef struct _StkEventsClass StkEventsClass;
#define _g_free0(var) (var = (g_free (var), NULL))

struct _StkWidget {
	GObject parent_instance;
	StkWidgetPrivate * priv;
	SDL_Rect rect;
	gboolean focused;
};

struct _StkWidgetClass {
	GObjectClass parent_class;
	gboolean (*draw) (StkWidget* self, SDL_Surface* screen);
};

typedef enum  {
	SYNERGIA_ORIENTATION_NORTH = 3,
	SYNERGIA_ORIENTATION_SOUTH = 0,
	SYNERGIA_ORIENTATION_EAST = 2,
	SYNERGIA_ORIENTATION_WEST = 1
} SynergiaOrientation;

struct _SynergiaCharacter {
	StkWidget parent_instance;
	SynergiaCharacterPrivate * priv;
	SDL_Surface* sprite;
	SDL_Surface* nameSurface;
	SynergiaOrientation orientation;
	gint frame;
	SDL_Rect pos;
	SDL_Rect offset;
	gint id;
	gint16 motion;
	gchar* name;
	gint16 move_offset;
	SynergiaOrientation move_orientation;
};

struct _SynergiaCharacterClass {
	StkWidgetClass parent_class;
};

struct _SynergiaPlayer {
	SynergiaCharacter parent_instance;
	SynergiaPlayerPrivate * priv;
};

struct _SynergiaPlayerClass {
	SynergiaCharacterClass parent_class;
};

struct _SynergiaPlayerPrivate {
	SynergiaNetConnector* net;
};

struct _SynergiaNetConnector {
	GTypeInstance parent_instance;
	volatile int ref_count;
	SynergiaNetConnectorPrivate * priv;
	gchar* address;
	gint port;
	GSocket* socket;
	SynergiaEvents* events;
};

struct _SynergiaNetConnectorClass {
	GTypeClass parent_class;
	void (*finalize) (SynergiaNetConnector *self);
};


static gpointer synergia_player_parent_class = NULL;
extern StkEvents* stk_stk_events;
extern gint stk_stk_ticks;

GType stk_widget_get_type (void) G_GNUC_CONST;
GType synergia_character_get_type (void) G_GNUC_CONST;
GType synergia_orientation_get_type (void) G_GNUC_CONST;
GType synergia_player_get_type (void) G_GNUC_CONST;
gpointer synergia_net_connector_ref (gpointer instance);
void synergia_net_connector_unref (gpointer instance);
GParamSpec* synergia_param_spec_net_connector (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void synergia_value_set_net_connector (GValue* value, gpointer v_object);
void synergia_value_take_net_connector (GValue* value, gpointer v_object);
gpointer synergia_value_get_net_connector (const GValue* value);
GType synergia_net_connector_get_type (void) G_GNUC_CONST;
#define SYNERGIA_PLAYER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), SYNERGIA_TYPE_PLAYER, SynergiaPlayerPrivate))
enum  {
	SYNERGIA_PLAYER_DUMMY_PROPERTY
};
SynergiaPlayer* synergia_player_new (SynergiaNetConnector* net);
SynergiaPlayer* synergia_player_construct (GType object_type, SynergiaNetConnector* net);
SynergiaCharacter* synergia_character_new (SynergiaNetConnector* net);
SynergiaCharacter* synergia_character_construct (GType object_type, SynergiaNetConnector* net);
gpointer synergia_events_ref (gpointer instance);
void synergia_events_unref (gpointer instance);
GParamSpec* synergia_param_spec_events (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void synergia_value_set_events (GValue* value, gpointer v_object);
void synergia_value_take_events (GValue* value, gpointer v_object);
gpointer synergia_value_get_events (const GValue* value);
GType synergia_events_get_type (void) G_GNUC_CONST;
void synergia_player_PlayerCharacterEvent (SynergiaPlayer* self, gchar** command, int command_length1);
static void _synergia_player_PlayerCharacterEvent_synergia_events_player_character (SynergiaEvents* _sender, gchar** args, int args_length1, gpointer self);
gpointer stk_events_ref (gpointer instance);
void stk_events_unref (gpointer instance);
GParamSpec* stk_param_spec_events (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void stk_value_set_events (GValue* value, gpointer v_object);
void stk_value_take_events (GValue* value, gpointer v_object);
gpointer stk_value_get_events (const GValue* value);
GType stk_events_get_type (void) G_GNUC_CONST;
void synergia_player_OnKeydown (SynergiaPlayer* self, SDL_KeyboardEvent* e);
static void _synergia_player_OnKeydown_stk_events_keydown (StkEvents* _sender, SDL_KeyboardEvent* e, gpointer self);
void synergia_net_connector_send_direct (SynergiaNetConnector* self, const gchar* command);
void stk_stk_clear_windows (void);
static gboolean synergia_player_real_draw (StkWidget* base, SDL_Surface* screen);
static void synergia_player_finalize (GObject* obj);


static gpointer _synergia_net_connector_ref0 (gpointer self) {
	return self ? synergia_net_connector_ref (self) : NULL;
}


static void _synergia_player_PlayerCharacterEvent_synergia_events_player_character (SynergiaEvents* _sender, gchar** args, int args_length1, gpointer self) {
	synergia_player_PlayerCharacterEvent (self, args, args_length1);
}


static void _synergia_player_OnKeydown_stk_events_keydown (StkEvents* _sender, SDL_KeyboardEvent* e, gpointer self) {
	synergia_player_OnKeydown (self, e);
}


SynergiaPlayer* synergia_player_construct (GType object_type, SynergiaNetConnector* net) {
	SynergiaPlayer * self = NULL;
	SynergiaNetConnector* _tmp0_;
	SynergiaNetConnector* _tmp1_;
	SynergiaNetConnector* _tmp2_;
	SynergiaNetConnector* _tmp3_;
	SynergiaEvents* _tmp4_;
	StkEvents* _tmp5_;
	g_return_val_if_fail (net != NULL, NULL);
	_tmp0_ = net;
	self = (SynergiaPlayer*) synergia_character_construct (object_type, _tmp0_);
	_tmp1_ = net;
	_tmp2_ = _synergia_net_connector_ref0 (_tmp1_);
	_synergia_net_connector_unref0 (self->priv->net);
	self->priv->net = _tmp2_;
	_tmp3_ = net;
	_tmp4_ = _tmp3_->events;
	g_signal_connect_object (_tmp4_, "player-character", (GCallback) _synergia_player_PlayerCharacterEvent_synergia_events_player_character, self, 0);
	_tmp5_ = stk_stk_events;
	g_signal_connect_object (_tmp5_, "keydown", (GCallback) _synergia_player_OnKeydown_stk_events_keydown, self, 0);
	return self;
}


SynergiaPlayer* synergia_player_new (SynergiaNetConnector* net) {
	return synergia_player_construct (SYNERGIA_TYPE_PLAYER, net);
}


void synergia_player_OnKeydown (SynergiaPlayer* self, SDL_KeyboardEvent* e) {
	gint16 _tmp0_;
	SDL_KeyboardEvent _tmp1_;
	SDL_keysym _tmp2_;
	int _tmp3_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (e != NULL);
	_tmp0_ = ((SynergiaCharacter*) self)->motion;
	if (((gint) _tmp0_) != 0) {
		return;
	}
	_tmp1_ = *e;
	_tmp2_ = _tmp1_.keysym;
	_tmp3_ = _tmp2_.sym;
	switch (_tmp3_) {
		case SDLK_UP:
		{
			gint16 _tmp4_;
			SynergiaNetConnector* _tmp5_;
			_tmp4_ = ((SynergiaCharacter*) self)->pos.y;
			((SynergiaCharacter*) self)->pos.y = _tmp4_ - 1;
			((SynergiaCharacter*) self)->orientation = SYNERGIA_ORIENTATION_NORTH;
			_tmp5_ = self->priv->net;
			synergia_net_connector_send_direct (_tmp5_, "moveup");
			break;
		}
		case SDLK_DOWN:
		{
			gint16 _tmp6_;
			SynergiaNetConnector* _tmp7_;
			_tmp6_ = ((SynergiaCharacter*) self)->pos.y;
			((SynergiaCharacter*) self)->pos.y = _tmp6_ + 1;
			((SynergiaCharacter*) self)->orientation = SYNERGIA_ORIENTATION_SOUTH;
			_tmp7_ = self->priv->net;
			synergia_net_connector_send_direct (_tmp7_, "movedown");
			break;
		}
		case SDLK_LEFT:
		{
			gint16 _tmp8_;
			SynergiaNetConnector* _tmp9_;
			_tmp8_ = ((SynergiaCharacter*) self)->pos.x;
			((SynergiaCharacter*) self)->pos.x = _tmp8_ - 1;
			((SynergiaCharacter*) self)->orientation = SYNERGIA_ORIENTATION_WEST;
			_tmp9_ = self->priv->net;
			synergia_net_connector_send_direct (_tmp9_, "moveleft");
			break;
		}
		case SDLK_RIGHT:
		{
			gint16 _tmp10_;
			SynergiaNetConnector* _tmp11_;
			_tmp10_ = ((SynergiaCharacter*) self)->pos.x;
			((SynergiaCharacter*) self)->pos.x = _tmp10_ + 1;
			((SynergiaCharacter*) self)->orientation = SYNERGIA_ORIENTATION_EAST;
			_tmp11_ = self->priv->net;
			synergia_net_connector_send_direct (_tmp11_, "moveright");
			break;
		}
		default:
		{
			return;
		}
	}
	((SynergiaCharacter*) self)->motion = (gint16) 32;
}


void synergia_player_PlayerCharacterEvent (SynergiaPlayer* self, gchar** command, int command_length1) {
	gchar** _tmp0_;
	gint _tmp0__length1;
	const gchar* _tmp1_;
	gchar* _tmp2_;
	gchar** _tmp3_;
	gint _tmp3__length1;
	const gchar* _tmp4_;
	gint _tmp5_ = 0;
	SynergiaNetConnector* _tmp6_;
	SynergiaNetConnector* _tmp7_;
	g_return_if_fail (self != NULL);
	_tmp0_ = command;
	_tmp0__length1 = command_length1;
	_tmp1_ = _tmp0_[1];
	_tmp2_ = g_strdup (_tmp1_);
	_g_free0 (((SynergiaCharacter*) self)->name);
	((SynergiaCharacter*) self)->name = _tmp2_;
	_tmp3_ = command;
	_tmp3__length1 = command_length1;
	_tmp4_ = _tmp3_[0];
	_tmp5_ = atoi (_tmp4_);
	((SynergiaCharacter*) self)->id = _tmp5_;
	stk_stk_clear_windows ();
	_tmp6_ = self->priv->net;
	synergia_net_connector_send_direct (_tmp6_, "get-position");
	_tmp7_ = self->priv->net;
	synergia_net_connector_send_direct (_tmp7_, "getmap");
}


static gboolean synergia_player_real_draw (StkWidget* base, SDL_Surface* screen) {
	SynergiaPlayer * self;
	gboolean result = FALSE;
	SDL_Rect src = {0};
	SDL_Rect dst = {0};
	gint16 _tmp0_;
	gint _tmp4_;
	SynergiaOrientation _tmp5_;
	SDL_Rect _tmp6_;
	gint16 _tmp7_;
	SDL_Rect _tmp8_;
	gint16 _tmp9_;
	SDL_Rect _tmp10_;
	gint16 _tmp11_;
	SDL_Rect _tmp12_;
	gint16 _tmp13_;
	SDL_Surface* _tmp14_;
	SDL_Rect _tmp15_;
	SDL_Surface* _tmp16_;
	SDL_Rect _tmp17_;
	gint16 _tmp18_;
	SDL_Rect _tmp20_;
	gint16 _tmp21_;
	SDL_Rect _tmp22_;
	gint16 _tmp23_;
	self = (SynergiaPlayer*) base;
	g_return_val_if_fail (screen != NULL, FALSE);
	memset (&src, 0, sizeof (SDL_Rect));
	memset (&dst, 0, sizeof (SDL_Rect));
	src.w = (guint16) 32;
	src.h = (guint16) 32;
	dst.w = (guint16) 32;
	dst.h = (guint16) 32;
	_tmp0_ = ((SynergiaCharacter*) self)->motion;
	if (((gint) _tmp0_) > 0) {
		gint _tmp1_;
		_tmp1_ = stk_stk_ticks;
		((SynergiaCharacter*) self)->frame = (_tmp1_ / 8) % 4;
	} else {
		gint _tmp2_;
		gint _tmp3_;
		_tmp2_ = stk_stk_ticks;
		_tmp3_ = stk_stk_ticks;
		if (((_tmp2_ / 8) % 4) != (((_tmp3_ - 1) / 8) % 4)) {
			((SynergiaCharacter*) self)->frame = 0;
		}
	}
	_tmp4_ = ((SynergiaCharacter*) self)->frame;
	src.x = (gint16) (32 * _tmp4_);
	_tmp5_ = ((SynergiaCharacter*) self)->orientation;
	src.y = (gint16) (32 * _tmp5_);
	_tmp6_ = ((SynergiaCharacter*) self)->pos;
	_tmp7_ = _tmp6_.x;
	_tmp8_ = ((SynergiaCharacter*) self)->offset;
	_tmp9_ = _tmp8_.x;
	dst.x = (gint16) (32 * (_tmp7_ - _tmp9_));
	_tmp10_ = ((SynergiaCharacter*) self)->pos;
	_tmp11_ = _tmp10_.y;
	_tmp12_ = ((SynergiaCharacter*) self)->offset;
	_tmp13_ = _tmp12_.y;
	dst.y = (gint16) (32 * (_tmp11_ - _tmp13_));
	_tmp14_ = ((SynergiaCharacter*) self)->sprite;
	_tmp15_ = src;
	_tmp16_ = screen;
	_tmp17_ = dst;
	SDL_UpperBlit (_tmp14_, &_tmp15_, _tmp16_, &_tmp17_);
	_tmp18_ = ((SynergiaCharacter*) self)->motion;
	if (((gint) _tmp18_) > 0) {
		gint16 _tmp19_;
		_tmp19_ = ((SynergiaCharacter*) self)->motion;
		((SynergiaCharacter*) self)->motion = _tmp19_ - 1;
	}
	_tmp20_ = dst;
	_tmp21_ = _tmp20_.x;
	((StkWidget*) self)->rect.x = _tmp21_;
	_tmp22_ = dst;
	_tmp23_ = _tmp22_.y;
	((StkWidget*) self)->rect.y = _tmp23_;
	((StkWidget*) self)->rect.w = (guint16) 32;
	((StkWidget*) self)->rect.h = (guint16) 32;
	result = TRUE;
	return result;
}


static void synergia_player_class_init (SynergiaPlayerClass * klass) {
	synergia_player_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (SynergiaPlayerPrivate));
	STK_WIDGET_CLASS (klass)->draw = synergia_player_real_draw;
	G_OBJECT_CLASS (klass)->finalize = synergia_player_finalize;
}


static void synergia_player_instance_init (SynergiaPlayer * self) {
	self->priv = SYNERGIA_PLAYER_GET_PRIVATE (self);
}


static void synergia_player_finalize (GObject* obj) {
	SynergiaPlayer * self;
	self = SYNERGIA_PLAYER (obj);
	_synergia_net_connector_unref0 (self->priv->net);
	G_OBJECT_CLASS (synergia_player_parent_class)->finalize (obj);
}


GType synergia_player_get_type (void) {
	static volatile gsize synergia_player_type_id__volatile = 0;
	if (g_once_init_enter (&synergia_player_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (SynergiaPlayerClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) synergia_player_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (SynergiaPlayer), 0, (GInstanceInitFunc) synergia_player_instance_init, NULL };
		GType synergia_player_type_id;
		synergia_player_type_id = g_type_register_static (SYNERGIA_TYPE_CHARACTER, "SynergiaPlayer", &g_define_type_info, 0);
		g_once_init_leave (&synergia_player_type_id__volatile, synergia_player_type_id);
	}
	return synergia_player_type_id__volatile;
}



