/* status_window.c generated by valac 0.16.0, the Vala compiler
 * generated from status_window.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <SDL.h>
#include <gee.h>
#include <stdlib.h>
#include <string.h>


#define STK_TYPE_WIDGET (stk_widget_get_type ())
#define STK_WIDGET(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), STK_TYPE_WIDGET, StkWidget))
#define STK_WIDGET_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), STK_TYPE_WIDGET, StkWidgetClass))
#define STK_IS_WIDGET(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), STK_TYPE_WIDGET))
#define STK_IS_WIDGET_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), STK_TYPE_WIDGET))
#define STK_WIDGET_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), STK_TYPE_WIDGET, StkWidgetClass))

typedef struct _StkWidget StkWidget;
typedef struct _StkWidgetClass StkWidgetClass;
typedef struct _StkWidgetPrivate StkWidgetPrivate;

#define STK_TYPE_CONTAINER (stk_container_get_type ())
#define STK_CONTAINER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), STK_TYPE_CONTAINER, StkContainer))
#define STK_CONTAINER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), STK_TYPE_CONTAINER, StkContainerClass))
#define STK_IS_CONTAINER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), STK_TYPE_CONTAINER))
#define STK_IS_CONTAINER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), STK_TYPE_CONTAINER))
#define STK_CONTAINER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), STK_TYPE_CONTAINER, StkContainerClass))

typedef struct _StkContainer StkContainer;
typedef struct _StkContainerClass StkContainerClass;
typedef struct _StkContainerPrivate StkContainerPrivate;

#define STK_TYPE_WINDOW (stk_window_get_type ())
#define STK_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), STK_TYPE_WINDOW, StkWindow))
#define STK_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), STK_TYPE_WINDOW, StkWindowClass))
#define STK_IS_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), STK_TYPE_WINDOW))
#define STK_IS_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), STK_TYPE_WINDOW))
#define STK_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), STK_TYPE_WINDOW, StkWindowClass))

typedef struct _StkWindow StkWindow;
typedef struct _StkWindowClass StkWindowClass;
typedef struct _StkWindowPrivate StkWindowPrivate;

#define SYNERGIA_TYPE_STATUS_WINDOW (synergia_status_window_get_type ())
#define SYNERGIA_STATUS_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYNERGIA_TYPE_STATUS_WINDOW, SynergiaStatusWindow))
#define SYNERGIA_STATUS_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYNERGIA_TYPE_STATUS_WINDOW, SynergiaStatusWindowClass))
#define SYNERGIA_IS_STATUS_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYNERGIA_TYPE_STATUS_WINDOW))
#define SYNERGIA_IS_STATUS_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYNERGIA_TYPE_STATUS_WINDOW))
#define SYNERGIA_STATUS_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYNERGIA_TYPE_STATUS_WINDOW, SynergiaStatusWindowClass))

typedef struct _SynergiaStatusWindow SynergiaStatusWindow;
typedef struct _SynergiaStatusWindowClass SynergiaStatusWindowClass;
typedef struct _SynergiaStatusWindowPrivate SynergiaStatusWindowPrivate;

#define STK_TYPE_LABEL (stk_label_get_type ())
#define STK_LABEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), STK_TYPE_LABEL, StkLabel))
#define STK_LABEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), STK_TYPE_LABEL, StkLabelClass))
#define STK_IS_LABEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), STK_TYPE_LABEL))
#define STK_IS_LABEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), STK_TYPE_LABEL))
#define STK_LABEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), STK_TYPE_LABEL, StkLabelClass))

typedef struct _StkLabel StkLabel;
typedef struct _StkLabelClass StkLabelClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _StkLabelPrivate StkLabelPrivate;

#define STK_TYPE_ALIGNMENT (stk_alignment_get_type ())
#define _g_free0(var) (var = (g_free (var), NULL))

struct _StkWidget {
	GObject parent_instance;
	StkWidgetPrivate * priv;
	SDL_Rect rect;
	gboolean focused;
};

struct _StkWidgetClass {
	GObjectClass parent_class;
	gboolean (*draw) (StkWidget* self, SDL_Surface* screen);
};

struct _StkContainer {
	StkWidget parent_instance;
	StkContainerPrivate * priv;
	GeeList* widgets;
};

struct _StkContainerClass {
	StkWidgetClass parent_class;
};

struct _StkWindow {
	StkContainer parent_instance;
	StkWindowPrivate * priv;
	SDL_Color background;
	SDL_Color titlebg;
	SDL_Color border;
	gchar* title;
	guchar opacity;
	gboolean bubble;
};

struct _StkWindowClass {
	StkContainerClass parent_class;
};

struct _SynergiaStatusWindow {
	StkWindow parent_instance;
	SynergiaStatusWindowPrivate * priv;
};

struct _SynergiaStatusWindowClass {
	StkWindowClass parent_class;
};

struct _SynergiaStatusWindowPrivate {
	StkLabel* label;
};

typedef enum  {
	STK_ALIGNMENT_LEFT,
	STK_ALIGNMENT_RIGHT,
	STK_ALIGNMENT_CENTER,
	STK_ALIGNMENT_TOP,
	STK_ALIGNMENT_MIDDLE,
	STK_ALIGNMENT_BOTTOM
} StkAlignment;

struct _StkLabel {
	StkWidget parent_instance;
	StkLabelPrivate * priv;
	gchar* text;
	gboolean translucent;
	SDL_Color color;
	StkAlignment halign;
	StkAlignment valign;
};

struct _StkLabelClass {
	StkWidgetClass parent_class;
};


static gpointer synergia_status_window_parent_class = NULL;

GType stk_widget_get_type (void) G_GNUC_CONST;
GType stk_container_get_type (void) G_GNUC_CONST;
GType stk_window_get_type (void) G_GNUC_CONST;
GType synergia_status_window_get_type (void) G_GNUC_CONST;
GType stk_label_get_type (void) G_GNUC_CONST;
#define SYNERGIA_STATUS_WINDOW_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), SYNERGIA_TYPE_STATUS_WINDOW, SynergiaStatusWindowPrivate))
enum  {
	SYNERGIA_STATUS_WINDOW_DUMMY_PROPERTY,
	SYNERGIA_STATUS_WINDOW_MESSAGE
};
SynergiaStatusWindow* synergia_status_window_new (void);
SynergiaStatusWindow* synergia_status_window_construct (GType object_type);
StkWindow* stk_window_new (void);
StkWindow* stk_window_construct (GType object_type);
StkLabel* stk_label_new (void);
StkLabel* stk_label_construct (GType object_type);
void stk_container_add (StkContainer* self, StkWidget* w);
void stk_window_set_size (StkWindow* self, gint width, gint height);
void stk_window_set_position (StkWindow* self, gint x, gint y);
const gchar* synergia_status_window_get_message (SynergiaStatusWindow* self);
GType stk_alignment_get_type (void) G_GNUC_CONST;
void synergia_status_window_set_message (SynergiaStatusWindow* self, const gchar* value);
static void synergia_status_window_finalize (GObject* obj);
static void _vala_synergia_status_window_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_synergia_status_window_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


SynergiaStatusWindow* synergia_status_window_construct (GType object_type) {
	SynergiaStatusWindow * self = NULL;
	StkLabel* _tmp0_;
	StkLabel* _tmp1_;
	self = (SynergiaStatusWindow*) stk_window_construct (object_type);
	_tmp0_ = stk_label_new ();
	_g_object_unref0 (self->priv->label);
	self->priv->label = _tmp0_;
	_tmp1_ = self->priv->label;
	stk_container_add ((StkContainer*) self, (StkWidget*) _tmp1_);
	stk_window_set_size ((StkWindow*) self, 400, 140);
	stk_window_set_position ((StkWindow*) self, 120, 180);
	return self;
}


SynergiaStatusWindow* synergia_status_window_new (void) {
	return synergia_status_window_construct (SYNERGIA_TYPE_STATUS_WINDOW);
}


const gchar* synergia_status_window_get_message (SynergiaStatusWindow* self) {
	const gchar* result;
	StkLabel* _tmp0_;
	const gchar* _tmp1_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->label;
	_tmp1_ = _tmp0_->text;
	result = _tmp1_;
	return result;
}


void synergia_status_window_set_message (SynergiaStatusWindow* self, const gchar* value) {
	StkLabel* _tmp0_;
	const gchar* _tmp1_;
	gchar* _tmp2_;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->label;
	_tmp1_ = value;
	_tmp2_ = g_strdup (_tmp1_);
	_g_free0 (_tmp0_->text);
	_tmp0_->text = _tmp2_;
	g_object_notify ((GObject *) self, "message");
}


static void synergia_status_window_class_init (SynergiaStatusWindowClass * klass) {
	synergia_status_window_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (SynergiaStatusWindowPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_synergia_status_window_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_synergia_status_window_set_property;
	G_OBJECT_CLASS (klass)->finalize = synergia_status_window_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), SYNERGIA_STATUS_WINDOW_MESSAGE, g_param_spec_string ("message", "message", "message", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
}


static void synergia_status_window_instance_init (SynergiaStatusWindow * self) {
	self->priv = SYNERGIA_STATUS_WINDOW_GET_PRIVATE (self);
}


static void synergia_status_window_finalize (GObject* obj) {
	SynergiaStatusWindow * self;
	self = SYNERGIA_STATUS_WINDOW (obj);
	_g_object_unref0 (self->priv->label);
	G_OBJECT_CLASS (synergia_status_window_parent_class)->finalize (obj);
}


GType synergia_status_window_get_type (void) {
	static volatile gsize synergia_status_window_type_id__volatile = 0;
	if (g_once_init_enter (&synergia_status_window_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (SynergiaStatusWindowClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) synergia_status_window_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (SynergiaStatusWindow), 0, (GInstanceInitFunc) synergia_status_window_instance_init, NULL };
		GType synergia_status_window_type_id;
		synergia_status_window_type_id = g_type_register_static (STK_TYPE_WINDOW, "SynergiaStatusWindow", &g_define_type_info, 0);
		g_once_init_leave (&synergia_status_window_type_id__volatile, synergia_status_window_type_id);
	}
	return synergia_status_window_type_id__volatile;
}


static void _vala_synergia_status_window_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	SynergiaStatusWindow * self;
	self = SYNERGIA_STATUS_WINDOW (object);
	switch (property_id) {
		case SYNERGIA_STATUS_WINDOW_MESSAGE:
		g_value_set_string (value, synergia_status_window_get_message (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_synergia_status_window_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	SynergiaStatusWindow * self;
	self = SYNERGIA_STATUS_WINDOW (object);
	switch (property_id) {
		case SYNERGIA_STATUS_WINDOW_MESSAGE:
		synergia_status_window_set_message (self, g_value_get_string (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



