/* tile.c generated by valac 0.16.0, the Vala compiler
 * generated from tile.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>


#define SYNERGIA_TYPE_TILE (synergia_tile_get_type ())
typedef struct _SynergiaTile SynergiaTile;
#define _g_free0(var) (var = (g_free (var), NULL))

struct _SynergiaTile {
	gchar* value;
	gboolean crossable;
	gboolean set;
};



GType synergia_tile_get_type (void) G_GNUC_CONST;
SynergiaTile* synergia_tile_dup (const SynergiaTile* self);
void synergia_tile_free (SynergiaTile* self);
void synergia_tile_copy (const SynergiaTile* self, SynergiaTile* dest);
void synergia_tile_destroy (SynergiaTile* self);


void synergia_tile_copy (const SynergiaTile* self, SynergiaTile* dest) {
	const gchar* _tmp0_;
	gchar* _tmp1_;
	gboolean _tmp2_;
	gboolean _tmp3_;
	_tmp0_ = (*self).value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 ((*dest).value);
	(*dest).value = _tmp1_;
	_tmp2_ = (*self).crossable;
	(*dest).crossable = _tmp2_;
	_tmp3_ = (*self).set;
	(*dest).set = _tmp3_;
}


void synergia_tile_destroy (SynergiaTile* self) {
	_g_free0 ((*self).value);
}


SynergiaTile* synergia_tile_dup (const SynergiaTile* self) {
	SynergiaTile* dup;
	dup = g_new0 (SynergiaTile, 1);
	synergia_tile_copy (self, dup);
	return dup;
}


void synergia_tile_free (SynergiaTile* self) {
	synergia_tile_destroy (self);
	g_free (self);
}


GType synergia_tile_get_type (void) {
	static volatile gsize synergia_tile_type_id__volatile = 0;
	if (g_once_init_enter (&synergia_tile_type_id__volatile)) {
		GType synergia_tile_type_id;
		synergia_tile_type_id = g_boxed_type_register_static ("SynergiaTile", (GBoxedCopyFunc) synergia_tile_dup, (GBoxedFreeFunc) synergia_tile_free);
		g_once_init_leave (&synergia_tile_type_id__volatile, synergia_tile_type_id);
	}
	return synergia_tile_type_id__volatile;
}



