/* button.c generated by valac 0.16.0, the Vala compiler
 * generated from button.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <SDL.h>
#include <stdlib.h>
#include <string.h>
#include <SDL_gfxPrimitives.h>


#define STK_TYPE_WIDGET (stk_widget_get_type ())
#define STK_WIDGET(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), STK_TYPE_WIDGET, StkWidget))
#define STK_WIDGET_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), STK_TYPE_WIDGET, StkWidgetClass))
#define STK_IS_WIDGET(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), STK_TYPE_WIDGET))
#define STK_IS_WIDGET_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), STK_TYPE_WIDGET))
#define STK_WIDGET_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), STK_TYPE_WIDGET, StkWidgetClass))

typedef struct _StkWidget StkWidget;
typedef struct _StkWidgetClass StkWidgetClass;
typedef struct _StkWidgetPrivate StkWidgetPrivate;

#define STK_TYPE_BUTTON (stk_button_get_type ())
#define STK_BUTTON(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), STK_TYPE_BUTTON, StkButton))
#define STK_BUTTON_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), STK_TYPE_BUTTON, StkButtonClass))
#define STK_IS_BUTTON(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), STK_TYPE_BUTTON))
#define STK_IS_BUTTON_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), STK_TYPE_BUTTON))
#define STK_BUTTON_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), STK_TYPE_BUTTON, StkButtonClass))

typedef struct _StkButton StkButton;
typedef struct _StkButtonClass StkButtonClass;
typedef struct _StkButtonPrivate StkButtonPrivate;

#define STK_TYPE_LABEL (stk_label_get_type ())
#define STK_LABEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), STK_TYPE_LABEL, StkLabel))
#define STK_LABEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), STK_TYPE_LABEL, StkLabelClass))
#define STK_IS_LABEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), STK_TYPE_LABEL))
#define STK_IS_LABEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), STK_TYPE_LABEL))
#define STK_LABEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), STK_TYPE_LABEL, StkLabelClass))

typedef struct _StkLabel StkLabel;
typedef struct _StkLabelClass StkLabelClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define STK_TYPE_EVENTS (stk_events_get_type ())
#define STK_EVENTS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), STK_TYPE_EVENTS, StkEvents))
#define STK_EVENTS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), STK_TYPE_EVENTS, StkEventsClass))
#define STK_IS_EVENTS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), STK_TYPE_EVENTS))
#define STK_IS_EVENTS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), STK_TYPE_EVENTS))
#define STK_EVENTS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), STK_TYPE_EVENTS, StkEventsClass))

typedef struct _StkEvents StkEvents;
typedef struct _StkEventsClass StkEventsClass;
typedef struct _StkLabelPrivate StkLabelPrivate;

#define STK_TYPE_ALIGNMENT (stk_alignment_get_type ())

struct _StkWidget {
	GObject parent_instance;
	StkWidgetPrivate * priv;
	SDL_Rect rect;
	gboolean focused;
};

struct _StkWidgetClass {
	GObjectClass parent_class;
	gboolean (*draw) (StkWidget* self, SDL_Surface* screen);
};

struct _StkButton {
	StkWidget parent_instance;
	StkButtonPrivate * priv;
	StkLabel* label;
	SDL_Color border;
	SDL_Color background;
};

struct _StkButtonClass {
	StkWidgetClass parent_class;
};

typedef enum  {
	STK_ALIGNMENT_LEFT,
	STK_ALIGNMENT_RIGHT,
	STK_ALIGNMENT_CENTER,
	STK_ALIGNMENT_TOP,
	STK_ALIGNMENT_MIDDLE,
	STK_ALIGNMENT_BOTTOM
} StkAlignment;

struct _StkLabel {
	StkWidget parent_instance;
	StkLabelPrivate * priv;
	gchar* text;
	gboolean translucent;
	SDL_Color color;
	StkAlignment halign;
	StkAlignment valign;
};

struct _StkLabelClass {
	StkWidgetClass parent_class;
};


static gpointer stk_button_parent_class = NULL;
extern StkEvents* stk_stk_events;

GType stk_widget_get_type (void) G_GNUC_CONST;
GType stk_button_get_type (void) G_GNUC_CONST;
GType stk_label_get_type (void) G_GNUC_CONST;
enum  {
	STK_BUTTON_DUMMY_PROPERTY
};
StkButton* stk_button_new (void);
StkButton* stk_button_construct (GType object_type);
StkWidget* stk_widget_new (void);
StkWidget* stk_widget_construct (GType object_type);
gpointer stk_events_ref (gpointer instance);
void stk_events_unref (gpointer instance);
GParamSpec* stk_param_spec_events (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void stk_value_set_events (GValue* value, gpointer v_object);
void stk_value_take_events (GValue* value, gpointer v_object);
gpointer stk_value_get_events (const GValue* value);
GType stk_events_get_type (void) G_GNUC_CONST;
void stk_button_onclick (StkButton* self, SDL_MouseButtonEvent* e);
static void _stk_button_onclick_stk_events_mouseleft (StkEvents* _sender, SDL_MouseButtonEvent* e, gpointer self);
void stk_button_onmousedown (StkButton* self, SDL_MouseButtonEvent* e);
static void _stk_button_onmousedown_stk_events_mousedown (StkEvents* _sender, SDL_MouseButtonEvent* e, gpointer self);
void stk_button_onmouseup (StkButton* self, SDL_MouseButtonEvent* e);
static void _stk_button_onmouseup_stk_events_mouseup (StkEvents* _sender, SDL_MouseButtonEvent* e, gpointer self);
void stk_button_onfocus (StkButton* self);
static void _stk_button_onfocus_stk_widget_focus (StkWidget* _sender, gpointer self);
void stk_button_onblur (StkButton* self);
static void _stk_button_onblur_stk_widget_blur (StkWidget* _sender, gpointer self);
StkButton* stk_button_new_with_text (const gchar* text);
StkButton* stk_button_construct_with_text (GType object_type, const gchar* text);
StkLabel* stk_label_new_with_text (const gchar* text);
StkLabel* stk_label_construct_with_text (GType object_type, const gchar* text);
GType stk_alignment_get_type (void) G_GNUC_CONST;
gboolean stk_widget_collides (StkWidget* self, gint x, gint y);
static gboolean stk_button_real_draw (StkWidget* base, SDL_Surface* screen);
gboolean stk_widget_draw (StkWidget* self, SDL_Surface* screen);
guint32 stk_stk_color_to_uint32 (SDL_Color c);
static void stk_button_finalize (GObject* obj);


static void _stk_button_onclick_stk_events_mouseleft (StkEvents* _sender, SDL_MouseButtonEvent* e, gpointer self) {
	stk_button_onclick (self, e);
}


static void _stk_button_onmousedown_stk_events_mousedown (StkEvents* _sender, SDL_MouseButtonEvent* e, gpointer self) {
	stk_button_onmousedown (self, e);
}


static void _stk_button_onmouseup_stk_events_mouseup (StkEvents* _sender, SDL_MouseButtonEvent* e, gpointer self) {
	stk_button_onmouseup (self, e);
}


static void _stk_button_onfocus_stk_widget_focus (StkWidget* _sender, gpointer self) {
	stk_button_onfocus (self);
}


static void _stk_button_onblur_stk_widget_blur (StkWidget* _sender, gpointer self) {
	stk_button_onblur (self);
}


StkButton* stk_button_construct (GType object_type) {
	StkButton * self = NULL;
	SDL_Color _tmp0_ = {0};
	SDL_Color _tmp1_ = {0};
	StkEvents* _tmp2_;
	StkEvents* _tmp3_;
	StkEvents* _tmp4_;
	self = (StkButton*) stk_widget_construct (object_type);
	_tmp0_.r = (guchar) 0;
	_tmp0_.g = (guchar) 0;
	_tmp0_.b = (guchar) 0;
	_tmp0_.unused = (guchar) 255;
	self->border = _tmp0_;
	_tmp1_.r = (guchar) 255;
	_tmp1_.g = (guchar) 255;
	_tmp1_.b = (guchar) 255;
	_tmp1_.unused = (guchar) 255;
	self->background = _tmp1_;
	_tmp2_ = stk_stk_events;
	g_signal_connect_object (_tmp2_, "mouseleft", (GCallback) _stk_button_onclick_stk_events_mouseleft, self, 0);
	_tmp3_ = stk_stk_events;
	g_signal_connect_object (_tmp3_, "mousedown", (GCallback) _stk_button_onmousedown_stk_events_mousedown, self, 0);
	_tmp4_ = stk_stk_events;
	g_signal_connect_object (_tmp4_, "mouseup", (GCallback) _stk_button_onmouseup_stk_events_mouseup, self, 0);
	g_signal_connect_object ((StkWidget*) self, "focus", (GCallback) _stk_button_onfocus_stk_widget_focus, self, 0);
	g_signal_connect_object ((StkWidget*) self, "blur", (GCallback) _stk_button_onblur_stk_widget_blur, self, 0);
	return self;
}


StkButton* stk_button_new (void) {
	return stk_button_construct (STK_TYPE_BUTTON);
}


StkButton* stk_button_construct_with_text (GType object_type, const gchar* text) {
	StkButton * self = NULL;
	const gchar* _tmp0_;
	StkLabel* _tmp1_;
	StkLabel* _tmp2_;
	g_return_val_if_fail (text != NULL, NULL);
	self = (StkButton*) stk_button_construct (object_type);
	_tmp0_ = text;
	_tmp1_ = stk_label_new_with_text (_tmp0_);
	_g_object_unref0 (self->label);
	self->label = _tmp1_;
	_tmp2_ = self->label;
	_tmp2_->translucent = TRUE;
	return self;
}


StkButton* stk_button_new_with_text (const gchar* text) {
	return stk_button_construct_with_text (STK_TYPE_BUTTON, text);
}


void stk_button_onclick (StkButton* self, SDL_MouseButtonEvent* e) {
	SDL_MouseButtonEvent _tmp0_;
	guint16 _tmp1_;
	SDL_MouseButtonEvent _tmp2_;
	guint16 _tmp3_;
	gboolean _tmp4_ = FALSE;
	g_return_if_fail (self != NULL);
	g_return_if_fail (e != NULL);
	_tmp0_ = *e;
	_tmp1_ = _tmp0_.x;
	_tmp2_ = *e;
	_tmp3_ = _tmp2_.y;
	_tmp4_ = stk_widget_collides ((StkWidget*) self, (gint) _tmp1_, (gint) _tmp3_);
	if (_tmp4_) {
		g_signal_emit_by_name (self, "clicked");
	}
}


void stk_button_onmousedown (StkButton* self, SDL_MouseButtonEvent* e) {
	gboolean _tmp0_ = FALSE;
	SDL_MouseButtonEvent _tmp1_;
	guchar _tmp2_;
	gboolean _tmp8_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (e != NULL);
	_tmp1_ = *e;
	_tmp2_ = _tmp1_.button;
	if (_tmp2_ == SDL_BUTTON_LEFT) {
		SDL_MouseButtonEvent _tmp3_;
		guint16 _tmp4_;
		SDL_MouseButtonEvent _tmp5_;
		guint16 _tmp6_;
		gboolean _tmp7_ = FALSE;
		_tmp3_ = *e;
		_tmp4_ = _tmp3_.x;
		_tmp5_ = *e;
		_tmp6_ = _tmp5_.y;
		_tmp7_ = stk_widget_collides ((StkWidget*) self, (gint) _tmp4_, (gint) _tmp6_);
		_tmp0_ = _tmp7_;
	} else {
		_tmp0_ = FALSE;
	}
	_tmp8_ = _tmp0_;
	if (_tmp8_) {
		StkLabel* _tmp9_;
		SDL_Color _tmp10_ = {0};
		SDL_Color _tmp11_ = {0};
		SDL_Color _tmp12_ = {0};
		_tmp9_ = self->label;
		_tmp10_.r = (guchar) 255;
		_tmp10_.g = (guchar) 255;
		_tmp10_.b = (guchar) 255;
		_tmp10_.unused = (guchar) 255;
		_tmp9_->color = _tmp10_;
		_tmp11_.r = (guchar) 0;
		_tmp11_.g = (guchar) 0;
		_tmp11_.b = (guchar) 0;
		_tmp11_.unused = (guchar) 255;
		self->border = _tmp11_;
		_tmp12_.r = (guchar) 0;
		_tmp12_.g = (guchar) 0;
		_tmp12_.b = (guchar) 0;
		_tmp12_.unused = (guchar) 255;
		self->background = _tmp12_;
	}
}


void stk_button_onmouseup (StkButton* self, SDL_MouseButtonEvent* e) {
	SDL_MouseButtonEvent _tmp0_;
	guchar _tmp1_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (e != NULL);
	_tmp0_ = *e;
	_tmp1_ = _tmp0_.button;
	if (_tmp1_ == SDL_BUTTON_LEFT) {
		gboolean _tmp2_;
		SDL_Color _tmp9_ = {0};
		_tmp2_ = ((StkWidget*) self)->focused;
		if (_tmp2_) {
			SDL_Color _tmp3_ = {0};
			StkLabel* _tmp4_;
			SDL_Color _tmp5_ = {0};
			_tmp3_.r = (guchar) 128;
			_tmp3_.g = (guchar) 128;
			_tmp3_.b = (guchar) 128;
			_tmp3_.unused = (guchar) 255;
			self->border = _tmp3_;
			_tmp4_ = self->label;
			_tmp5_.r = (guchar) 128;
			_tmp5_.g = (guchar) 128;
			_tmp5_.b = (guchar) 128;
			_tmp5_.unused = (guchar) 255;
			_tmp4_->color = _tmp5_;
		} else {
			StkLabel* _tmp6_;
			SDL_Color _tmp7_ = {0};
			SDL_Color _tmp8_ = {0};
			_tmp6_ = self->label;
			_tmp7_.r = (guchar) 0;
			_tmp7_.g = (guchar) 0;
			_tmp7_.b = (guchar) 0;
			_tmp7_.unused = (guchar) 255;
			_tmp6_->color = _tmp7_;
			_tmp8_.r = (guchar) 0;
			_tmp8_.g = (guchar) 0;
			_tmp8_.b = (guchar) 0;
			_tmp8_.unused = (guchar) 255;
			self->border = _tmp8_;
		}
		_tmp9_.r = (guchar) 255;
		_tmp9_.g = (guchar) 255;
		_tmp9_.b = (guchar) 255;
		_tmp9_.unused = (guchar) 255;
		self->background = _tmp9_;
	}
}


void stk_button_onfocus (StkButton* self) {
	SDL_Color _tmp0_ = {0};
	StkLabel* _tmp1_;
	SDL_Color _tmp2_ = {0};
	g_return_if_fail (self != NULL);
	_tmp0_.r = (guchar) 128;
	_tmp0_.g = (guchar) 128;
	_tmp0_.b = (guchar) 128;
	_tmp0_.unused = (guchar) 255;
	self->border = _tmp0_;
	_tmp1_ = self->label;
	_tmp2_.r = (guchar) 128;
	_tmp2_.g = (guchar) 128;
	_tmp2_.b = (guchar) 128;
	_tmp2_.unused = (guchar) 255;
	_tmp1_->color = _tmp2_;
}


void stk_button_onblur (StkButton* self) {
	SDL_Color _tmp0_ = {0};
	StkLabel* _tmp1_;
	SDL_Color _tmp2_ = {0};
	g_return_if_fail (self != NULL);
	_tmp0_.r = (guchar) 0;
	_tmp0_.g = (guchar) 0;
	_tmp0_.b = (guchar) 0;
	_tmp0_.unused = (guchar) 255;
	self->border = _tmp0_;
	_tmp1_ = self->label;
	_tmp2_.r = (guchar) 0;
	_tmp2_.g = (guchar) 0;
	_tmp2_.b = (guchar) 0;
	_tmp2_.unused = (guchar) 255;
	_tmp1_->color = _tmp2_;
}


static gboolean stk_button_real_draw (StkWidget* base, SDL_Surface* screen) {
	StkButton * self;
	gboolean result = FALSE;
	SDL_Surface* _tmp0_;
	SDL_Surface* _tmp1_;
	StkLabel* _tmp2_;
	SDL_Rect _tmp3_;
	gint16 _tmp4_;
	StkLabel* _tmp5_;
	SDL_Rect _tmp6_;
	gint16 _tmp7_;
	StkLabel* _tmp8_;
	SDL_Rect _tmp9_;
	gint16 _tmp10_;
	StkLabel* _tmp11_;
	SDL_Rect _tmp12_;
	guint16 _tmp13_;
	StkLabel* _tmp14_;
	SDL_Rect _tmp15_;
	gint16 _tmp16_;
	StkLabel* _tmp17_;
	SDL_Rect _tmp18_;
	guint16 _tmp19_;
	SDL_Color _tmp20_;
	guint32 _tmp21_ = 0U;
	StkLabel* _tmp22_;
	SDL_Surface* _tmp23_;
	SDL_Surface* _tmp24_;
	StkLabel* _tmp25_;
	SDL_Rect _tmp26_;
	gint16 _tmp27_;
	StkLabel* _tmp28_;
	SDL_Rect _tmp29_;
	gint16 _tmp30_;
	StkLabel* _tmp31_;
	SDL_Rect _tmp32_;
	gint16 _tmp33_;
	StkLabel* _tmp34_;
	SDL_Rect _tmp35_;
	guint16 _tmp36_;
	StkLabel* _tmp37_;
	SDL_Rect _tmp38_;
	gint16 _tmp39_;
	StkLabel* _tmp40_;
	SDL_Rect _tmp41_;
	guint16 _tmp42_;
	SDL_Color _tmp43_;
	guint32 _tmp44_ = 0U;
	SDL_Surface* _tmp45_;
	StkLabel* _tmp46_;
	SDL_Rect _tmp47_;
	gint16 _tmp48_;
	StkLabel* _tmp49_;
	SDL_Rect _tmp50_;
	gint16 _tmp51_;
	StkLabel* _tmp52_;
	SDL_Rect _tmp53_;
	gint16 _tmp54_;
	StkLabel* _tmp55_;
	SDL_Rect _tmp56_;
	guint16 _tmp57_;
	StkLabel* _tmp58_;
	SDL_Rect _tmp59_;
	gint16 _tmp60_;
	StkLabel* _tmp61_;
	SDL_Rect _tmp62_;
	guint16 _tmp63_;
	SDL_Color _tmp64_;
	guint32 _tmp65_ = 0U;
	StkLabel* _tmp66_;
	SDL_Rect _tmp67_;
	gint16 _tmp68_;
	StkLabel* _tmp69_;
	SDL_Rect _tmp70_;
	gint16 _tmp71_;
	StkLabel* _tmp72_;
	SDL_Rect _tmp73_;
	guint16 _tmp74_;
	StkLabel* _tmp75_;
	SDL_Rect _tmp76_;
	guint16 _tmp77_;
	self = (StkButton*) base;
	g_return_val_if_fail (screen != NULL, FALSE);
	_tmp0_ = screen;
	STK_WIDGET_CLASS (stk_button_parent_class)->draw (STK_WIDGET (self), _tmp0_);
	_tmp1_ = screen;
	_tmp2_ = self->label;
	_tmp3_ = ((StkWidget*) _tmp2_)->rect;
	_tmp4_ = _tmp3_.x;
	_tmp5_ = self->label;
	_tmp6_ = ((StkWidget*) _tmp5_)->rect;
	_tmp7_ = _tmp6_.y;
	_tmp8_ = self->label;
	_tmp9_ = ((StkWidget*) _tmp8_)->rect;
	_tmp10_ = _tmp9_.x;
	_tmp11_ = self->label;
	_tmp12_ = ((StkWidget*) _tmp11_)->rect;
	_tmp13_ = _tmp12_.w;
	_tmp14_ = self->label;
	_tmp15_ = ((StkWidget*) _tmp14_)->rect;
	_tmp16_ = _tmp15_.y;
	_tmp17_ = self->label;
	_tmp18_ = ((StkWidget*) _tmp17_)->rect;
	_tmp19_ = _tmp18_.h;
	_tmp20_ = self->background;
	_tmp21_ = stk_stk_color_to_uint32 (_tmp20_);
	boxColor (_tmp1_, (gint16) (_tmp4_ - 10), (gint16) (_tmp7_ - 4), (gint16) ((_tmp10_ + _tmp13_) + 10), (gint16) ((_tmp16_ + _tmp19_) + 2), _tmp21_);
	_tmp22_ = self->label;
	_tmp23_ = screen;
	stk_widget_draw ((StkWidget*) _tmp22_, _tmp23_);
	_tmp24_ = screen;
	_tmp25_ = self->label;
	_tmp26_ = ((StkWidget*) _tmp25_)->rect;
	_tmp27_ = _tmp26_.x;
	_tmp28_ = self->label;
	_tmp29_ = ((StkWidget*) _tmp28_)->rect;
	_tmp30_ = _tmp29_.y;
	_tmp31_ = self->label;
	_tmp32_ = ((StkWidget*) _tmp31_)->rect;
	_tmp33_ = _tmp32_.x;
	_tmp34_ = self->label;
	_tmp35_ = ((StkWidget*) _tmp34_)->rect;
	_tmp36_ = _tmp35_.w;
	_tmp37_ = self->label;
	_tmp38_ = ((StkWidget*) _tmp37_)->rect;
	_tmp39_ = _tmp38_.y;
	_tmp40_ = self->label;
	_tmp41_ = ((StkWidget*) _tmp40_)->rect;
	_tmp42_ = _tmp41_.h;
	_tmp43_ = self->border;
	_tmp44_ = stk_stk_color_to_uint32 (_tmp43_);
	rectangleColor (_tmp24_, (gint16) (_tmp27_ - 10), (gint16) (_tmp30_ - 4), (gint16) ((_tmp33_ + _tmp36_) + 10), (gint16) ((_tmp39_ + _tmp42_) + 2), _tmp44_);
	_tmp45_ = screen;
	_tmp46_ = self->label;
	_tmp47_ = ((StkWidget*) _tmp46_)->rect;
	_tmp48_ = _tmp47_.x;
	_tmp49_ = self->label;
	_tmp50_ = ((StkWidget*) _tmp49_)->rect;
	_tmp51_ = _tmp50_.y;
	_tmp52_ = self->label;
	_tmp53_ = ((StkWidget*) _tmp52_)->rect;
	_tmp54_ = _tmp53_.x;
	_tmp55_ = self->label;
	_tmp56_ = ((StkWidget*) _tmp55_)->rect;
	_tmp57_ = _tmp56_.w;
	_tmp58_ = self->label;
	_tmp59_ = ((StkWidget*) _tmp58_)->rect;
	_tmp60_ = _tmp59_.y;
	_tmp61_ = self->label;
	_tmp62_ = ((StkWidget*) _tmp61_)->rect;
	_tmp63_ = _tmp62_.h;
	_tmp64_ = self->border;
	_tmp65_ = stk_stk_color_to_uint32 (_tmp64_);
	rectangleColor (_tmp45_, (gint16) (_tmp48_ - 9), (gint16) (_tmp51_ - 3), (gint16) ((_tmp54_ + _tmp57_) + 9), (gint16) ((_tmp60_ + _tmp63_) + 1), _tmp65_);
	_tmp66_ = self->label;
	_tmp67_ = ((StkWidget*) _tmp66_)->rect;
	_tmp68_ = _tmp67_.x;
	((StkWidget*) self)->rect.x = (gint16) (_tmp68_ - 12);
	_tmp69_ = self->label;
	_tmp70_ = ((StkWidget*) _tmp69_)->rect;
	_tmp71_ = _tmp70_.y;
	((StkWidget*) self)->rect.y = (gint16) (_tmp71_ - 6);
	_tmp72_ = self->label;
	_tmp73_ = ((StkWidget*) _tmp72_)->rect;
	_tmp74_ = _tmp73_.w;
	((StkWidget*) self)->rect.w = (guint16) (_tmp74_ + 26);
	_tmp75_ = self->label;
	_tmp76_ = ((StkWidget*) _tmp75_)->rect;
	_tmp77_ = _tmp76_.h;
	((StkWidget*) self)->rect.h = (guint16) (_tmp77_ + 10);
	result = FALSE;
	return result;
}


static void stk_button_class_init (StkButtonClass * klass) {
	stk_button_parent_class = g_type_class_peek_parent (klass);
	STK_WIDGET_CLASS (klass)->draw = stk_button_real_draw;
	G_OBJECT_CLASS (klass)->finalize = stk_button_finalize;
	g_signal_new ("clicked", STK_TYPE_BUTTON, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
}


static void stk_button_instance_init (StkButton * self) {
}


static void stk_button_finalize (GObject* obj) {
	StkButton * self;
	self = STK_BUTTON (obj);
	_g_object_unref0 (self->label);
	G_OBJECT_CLASS (stk_button_parent_class)->finalize (obj);
}


GType stk_button_get_type (void) {
	static volatile gsize stk_button_type_id__volatile = 0;
	if (g_once_init_enter (&stk_button_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (StkButtonClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) stk_button_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (StkButton), 0, (GInstanceInitFunc) stk_button_instance_init, NULL };
		GType stk_button_type_id;
		stk_button_type_id = g_type_register_static (STK_TYPE_WIDGET, "StkButton", &g_define_type_info, 0);
		g_once_init_leave (&stk_button_type_id__volatile, stk_button_type_id);
	}
	return stk_button_type_id__volatile;
}



