/* events.c generated by valac 0.16.0, the Vala compiler
 * generated from events.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <string.h>
#include <SDL.h>
#include <gobject/gvaluecollector.h>


#define STK_TYPE_EVENTS (stk_events_get_type ())
#define STK_EVENTS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), STK_TYPE_EVENTS, StkEvents))
#define STK_EVENTS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), STK_TYPE_EVENTS, StkEventsClass))
#define STK_IS_EVENTS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), STK_TYPE_EVENTS))
#define STK_IS_EVENTS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), STK_TYPE_EVENTS))
#define STK_EVENTS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), STK_TYPE_EVENTS, StkEventsClass))

typedef struct _StkEvents StkEvents;
typedef struct _StkEventsClass StkEventsClass;
typedef struct _StkEventsPrivate StkEventsPrivate;
typedef struct _StkParamSpecEvents StkParamSpecEvents;

struct _StkEvents {
	GTypeInstance parent_instance;
	volatile int ref_count;
	StkEventsPrivate * priv;
};

struct _StkEventsClass {
	GTypeClass parent_class;
	void (*finalize) (StkEvents *self);
};

struct _StkEventsPrivate {
	guint32 mod;
};

struct _StkParamSpecEvents {
	GParamSpec parent_instance;
};


static gpointer stk_events_parent_class = NULL;

gpointer stk_events_ref (gpointer instance);
void stk_events_unref (gpointer instance);
GParamSpec* stk_param_spec_events (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void stk_value_set_events (GValue* value, gpointer v_object);
void stk_value_take_events (GValue* value, gpointer v_object);
gpointer stk_value_get_events (const GValue* value);
GType stk_events_get_type (void) G_GNUC_CONST;
#define STK_EVENTS_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), STK_TYPE_EVENTS, StkEventsPrivate))
enum  {
	STK_EVENTS_DUMMY_PROPERTY
};
void stk_events_process (StkEvents* self);
StkEvents* stk_events_new (void);
StkEvents* stk_events_construct (GType object_type);
static void stk_events_finalize (StkEvents* obj);


void stk_events_process (StkEvents* self) {
	SDL_Event event = {0};
	guint32 _tmp17_ = 0U;
	guint32 _tmp18_;
	g_return_if_fail (self != NULL);
	memset (&event, 0, sizeof (SDL_Event));
	while (TRUE) {
		SDL_Event _tmp0_ = {0};
		gint _tmp1_ = 0;
		SDL_Event _tmp2_;
		guchar _tmp3_;
		_tmp1_ = SDL_PollEvent (&_tmp0_);
		event = _tmp0_;
		if (!(_tmp1_ == 1)) {
			break;
		}
		_tmp2_ = event;
		_tmp3_ = _tmp2_.type;
		switch (_tmp3_) {
			case SDL_MOUSEMOTION:
			{
				SDL_Event _tmp4_;
				SDL_MouseMotionEvent _tmp5_;
				_tmp4_ = event;
				_tmp5_ = _tmp4_.motion;
				g_signal_emit_by_name (self, "mousemove", &_tmp5_);
				break;
			}
			case SDL_MOUSEBUTTONDOWN:
			{
				SDL_Event _tmp6_;
				SDL_MouseButtonEvent _tmp7_;
				_tmp6_ = event;
				_tmp7_ = _tmp6_.button;
				g_signal_emit_by_name (self, "mousedown", &_tmp7_);
				break;
			}
			case SDL_MOUSEBUTTONUP:
			{
				SDL_Event _tmp8_;
				SDL_MouseButtonEvent _tmp9_;
				SDL_Event _tmp10_;
				SDL_MouseButtonEvent _tmp11_;
				guchar _tmp12_;
				_tmp8_ = event;
				_tmp9_ = _tmp8_.button;
				g_signal_emit_by_name (self, "mouseup", &_tmp9_);
				_tmp10_ = event;
				_tmp11_ = _tmp10_.button;
				_tmp12_ = _tmp11_.button;
				switch (_tmp12_) {
					case SDL_BUTTON_LEFT:
					{
						SDL_Event _tmp13_;
						SDL_MouseButtonEvent _tmp14_;
						_tmp13_ = event;
						_tmp14_ = _tmp13_.button;
						g_signal_emit_by_name (self, "mouseleft", &_tmp14_);
						break;
					}
					default:
					break;
				}
				break;
			}
			case SDL_QUIT:
			{
				g_signal_emit_by_name (self, "quit");
				break;
			}
			case SDL_KEYDOWN:
			{
				SDL_Event _tmp15_;
				SDL_KeyboardEvent _tmp16_;
				_tmp15_ = event;
				_tmp16_ = _tmp15_.key;
				g_signal_emit_by_name (self, "keydown", &_tmp16_);
				break;
			}
			default:
			break;
		}
	}
	_tmp17_ = SDL_GetTicks ();
	_tmp18_ = self->priv->mod;
	if (((_tmp17_ / 1000) % 2) != _tmp18_) {
		guint32 _tmp19_ = 0U;
		_tmp19_ = SDL_GetTicks ();
		self->priv->mod = (_tmp19_ / 1000) % 2;
		g_signal_emit_by_name (self, "tick");
	}
}


StkEvents* stk_events_construct (GType object_type) {
	StkEvents* self = NULL;
	self = (StkEvents*) g_type_create_instance (object_type);
	return self;
}


StkEvents* stk_events_new (void) {
	return stk_events_construct (STK_TYPE_EVENTS);
}


static void stk_value_events_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void stk_value_events_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		stk_events_unref (value->data[0].v_pointer);
	}
}


static void stk_value_events_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = stk_events_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer stk_value_events_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* stk_value_events_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		StkEvents* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = stk_events_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* stk_value_events_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	StkEvents** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = stk_events_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* stk_param_spec_events (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	StkParamSpecEvents* spec;
	g_return_val_if_fail (g_type_is_a (object_type, STK_TYPE_EVENTS), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer stk_value_get_events (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, STK_TYPE_EVENTS), NULL);
	return value->data[0].v_pointer;
}


void stk_value_set_events (GValue* value, gpointer v_object) {
	StkEvents* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, STK_TYPE_EVENTS));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, STK_TYPE_EVENTS));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		stk_events_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		stk_events_unref (old);
	}
}


void stk_value_take_events (GValue* value, gpointer v_object) {
	StkEvents* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, STK_TYPE_EVENTS));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, STK_TYPE_EVENTS));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		stk_events_unref (old);
	}
}


static void stk_events_class_init (StkEventsClass * klass) {
	stk_events_parent_class = g_type_class_peek_parent (klass);
	STK_EVENTS_CLASS (klass)->finalize = stk_events_finalize;
	g_type_class_add_private (klass, sizeof (StkEventsPrivate));
	g_signal_new ("mouseleft", STK_TYPE_EVENTS, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__POINTER, G_TYPE_NONE, 1, G_TYPE_POINTER);
	g_signal_new ("mousedown", STK_TYPE_EVENTS, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__POINTER, G_TYPE_NONE, 1, G_TYPE_POINTER);
	g_signal_new ("mouseup", STK_TYPE_EVENTS, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__POINTER, G_TYPE_NONE, 1, G_TYPE_POINTER);
	g_signal_new ("mousemove", STK_TYPE_EVENTS, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__POINTER, G_TYPE_NONE, 1, G_TYPE_POINTER);
	g_signal_new ("keydown", STK_TYPE_EVENTS, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__POINTER, G_TYPE_NONE, 1, G_TYPE_POINTER);
	g_signal_new ("quit", STK_TYPE_EVENTS, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
	g_signal_new ("tick", STK_TYPE_EVENTS, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
}


static void stk_events_instance_init (StkEvents * self) {
	self->priv = STK_EVENTS_GET_PRIVATE (self);
	self->priv->mod = (guint32) 0;
	self->ref_count = 1;
}


static void stk_events_finalize (StkEvents* obj) {
	StkEvents * self;
	self = STK_EVENTS (obj);
}


GType stk_events_get_type (void) {
	static volatile gsize stk_events_type_id__volatile = 0;
	if (g_once_init_enter (&stk_events_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { stk_value_events_init, stk_value_events_free_value, stk_value_events_copy_value, stk_value_events_peek_pointer, "p", stk_value_events_collect_value, "p", stk_value_events_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (StkEventsClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) stk_events_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (StkEvents), 0, (GInstanceInitFunc) stk_events_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType stk_events_type_id;
		stk_events_type_id = g_type_register_fundamental (g_type_fundamental_next (), "StkEvents", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&stk_events_type_id__volatile, stk_events_type_id);
	}
	return stk_events_type_id__volatile;
}


gpointer stk_events_ref (gpointer instance) {
	StkEvents* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void stk_events_unref (gpointer instance) {
	StkEvents* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		STK_EVENTS_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}



