/* image.c generated by valac 0.16.0, the Vala compiler
 * generated from image.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <SDL.h>
#include <stdlib.h>
#include <string.h>
#include <SDL_image.h>


#define STK_TYPE_WIDGET (stk_widget_get_type ())
#define STK_WIDGET(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), STK_TYPE_WIDGET, StkWidget))
#define STK_WIDGET_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), STK_TYPE_WIDGET, StkWidgetClass))
#define STK_IS_WIDGET(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), STK_TYPE_WIDGET))
#define STK_IS_WIDGET_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), STK_TYPE_WIDGET))
#define STK_WIDGET_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), STK_TYPE_WIDGET, StkWidgetClass))

typedef struct _StkWidget StkWidget;
typedef struct _StkWidgetClass StkWidgetClass;
typedef struct _StkWidgetPrivate StkWidgetPrivate;

#define STK_TYPE_IMAGE (stk_image_get_type ())
#define STK_IMAGE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), STK_TYPE_IMAGE, StkImage))
#define STK_IMAGE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), STK_TYPE_IMAGE, StkImageClass))
#define STK_IS_IMAGE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), STK_TYPE_IMAGE))
#define STK_IS_IMAGE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), STK_TYPE_IMAGE))
#define STK_IMAGE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), STK_TYPE_IMAGE, StkImageClass))

typedef struct _StkImage StkImage;
typedef struct _StkImageClass StkImageClass;
typedef struct _StkImagePrivate StkImagePrivate;
#define _SDL_FreeSurface0(var) ((var == NULL) ? NULL : (var = (SDL_FreeSurface (var), NULL)))

struct _StkWidget {
	GObject parent_instance;
	StkWidgetPrivate * priv;
	SDL_Rect rect;
	gboolean focused;
};

struct _StkWidgetClass {
	GObjectClass parent_class;
	gboolean (*draw) (StkWidget* self, SDL_Surface* screen);
};

struct _StkImage {
	StkWidget parent_instance;
	StkImagePrivate * priv;
};

struct _StkImageClass {
	StkWidgetClass parent_class;
};

struct _StkImagePrivate {
	SDL_Surface* image;
};


static gpointer stk_image_parent_class = NULL;

GType stk_widget_get_type (void) G_GNUC_CONST;
GType stk_image_get_type (void) G_GNUC_CONST;
#define STK_IMAGE_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), STK_TYPE_IMAGE, StkImagePrivate))
enum  {
	STK_IMAGE_DUMMY_PROPERTY
};
StkImage* stk_image_new (void);
StkImage* stk_image_construct (GType object_type);
StkWidget* stk_widget_new (void);
StkWidget* stk_widget_construct (GType object_type);
StkImage* stk_image_new_from_file (const gchar* file);
StkImage* stk_image_construct_from_file (GType object_type, const gchar* file);
static gboolean stk_image_real_draw (StkWidget* base, SDL_Surface* screen);
gboolean stk_widget_draw (StkWidget* self, SDL_Surface* screen);
static void stk_image_finalize (GObject* obj);


StkImage* stk_image_construct (GType object_type) {
	StkImage * self = NULL;
	self = (StkImage*) stk_widget_construct (object_type);
	return self;
}


StkImage* stk_image_new (void) {
	return stk_image_construct (STK_TYPE_IMAGE);
}


StkImage* stk_image_construct_from_file (GType object_type, const gchar* file) {
	StkImage * self = NULL;
	const gchar* _tmp0_;
	SDL_Surface* _tmp1_ = NULL;
	g_return_val_if_fail (file != NULL, NULL);
	self = (StkImage*) stk_widget_construct (object_type);
	_tmp0_ = file;
	_tmp1_ = IMG_Load (_tmp0_);
	_SDL_FreeSurface0 (self->priv->image);
	self->priv->image = _tmp1_;
	return self;
}


StkImage* stk_image_new_from_file (const gchar* file) {
	return stk_image_construct_from_file (STK_TYPE_IMAGE, file);
}


static gboolean stk_image_real_draw (StkWidget* base, SDL_Surface* screen) {
	StkImage * self;
	gboolean result = FALSE;
	SDL_Surface* _tmp0_;
	SDL_Surface* _tmp1_;
	self = (StkImage*) base;
	g_return_val_if_fail (screen != NULL, FALSE);
	_tmp0_ = screen;
	STK_WIDGET_CLASS (stk_image_parent_class)->draw (STK_WIDGET (self), _tmp0_);
	_tmp1_ = self->priv->image;
	if (_tmp1_ != NULL) {
		SDL_Surface* _tmp2_;
		gint _tmp3_;
		SDL_Surface* _tmp4_;
		gint _tmp5_;
		SDL_Surface* _tmp6_;
		gint _tmp7_;
		SDL_Surface* _tmp8_;
		gint _tmp9_;
		SDL_Rect _tmp10_ = {0};
		SDL_Rect dst;
		SDL_Surface* _tmp11_;
		SDL_Surface* _tmp12_;
		SDL_Surface* _tmp13_;
		SDL_Rect _tmp14_;
		_tmp2_ = screen;
		_tmp3_ = _tmp2_->w;
		_tmp4_ = self->priv->image;
		_tmp5_ = _tmp4_->w;
		_tmp6_ = screen;
		_tmp7_ = _tmp6_->h;
		_tmp8_ = self->priv->image;
		_tmp9_ = _tmp8_->h;
		_tmp10_.x = (gint16) ((_tmp3_ / 2) - (_tmp5_ / 2));
		_tmp10_.y = (gint16) ((_tmp7_ / 2) - (_tmp9_ / 2));
		dst = _tmp10_;
		_tmp11_ = self->priv->image;
		SDL_SetAlpha (_tmp11_, (guint32) 0, (guchar) 0);
		_tmp12_ = self->priv->image;
		_tmp13_ = screen;
		_tmp14_ = dst;
		SDL_UpperBlit (_tmp12_, NULL, _tmp13_, &_tmp14_);
	}
	result = TRUE;
	return result;
}


static void stk_image_class_init (StkImageClass * klass) {
	stk_image_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (StkImagePrivate));
	STK_WIDGET_CLASS (klass)->draw = stk_image_real_draw;
	G_OBJECT_CLASS (klass)->finalize = stk_image_finalize;
}


static void stk_image_instance_init (StkImage * self) {
	self->priv = STK_IMAGE_GET_PRIVATE (self);
}


static void stk_image_finalize (GObject* obj) {
	StkImage * self;
	self = STK_IMAGE (obj);
	_SDL_FreeSurface0 (self->priv->image);
	G_OBJECT_CLASS (stk_image_parent_class)->finalize (obj);
}


GType stk_image_get_type (void) {
	static volatile gsize stk_image_type_id__volatile = 0;
	if (g_once_init_enter (&stk_image_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (StkImageClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) stk_image_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (StkImage), 0, (GInstanceInitFunc) stk_image_instance_init, NULL };
		GType stk_image_type_id;
		stk_image_type_id = g_type_register_static (STK_TYPE_WIDGET, "StkImage", &g_define_type_info, 0);
		g_once_init_leave (&stk_image_type_id__volatile, stk_image_type_id);
	}
	return stk_image_type_id__volatile;
}



